### ISSUE TITLE
TIFF PlanarConfiguration 2 (planar) mistaken for interleaved

### ISSUE THREAD

**Issue by nicolas-f** [haraldk/TwelveMonkeys#184] opened 2015-10-12 08:47 UTC
Hi,

We use your library in open source project OrbisGIS to read TIFF files. However there is a problem with a TIFF file.

The TIFF file is successfully read, however it shows a greyscale image with duplicated image. May be the bands are merged together ?

Here some info about the file
```
identify -verbose /mnt/stock/raster/raster/Nantes_Ouest_lambert2.tif
Image: /mnt/stock/raster/raster/Nantes_Ouest_lambert2.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 17115x30810+0+0
  Units: PixelsPerInch
  Type: TrueColor
  Base type: TrueColor
  Endianess: LSB
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Pixels: 527313150
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 86.9599 (0.341019)
      standard deviation: 88.8267 (0.34834)
      kurtosis: -1.50411
      skewness: 0.299257
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 37.1403 (0.145648)
      standard deviation: 60.5394 (0.23741)
      kurtosis: 4.01027
      skewness: 2.14245
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 43.2769 (0.169713)
      standard deviation: 61.8433 (0.242523)
      kurtosis: 2.93259
      skewness: 1.84273
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 55.7924 (0.218794)
      standard deviation: 71.6003 (0.280785)
      kurtosis: 0.820791
      skewness: 1.39108
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 17115x30810+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: TopLeft
  Properties:
    date:create: 2015-10-09T16:30:34+02:00
    date:modify: 2015-10-09T16:30:34+02:00
    signature: 75e5e167bcd0b3e19e55fc08def01eaf63ea175acd7f9eb81b193dddce8fb747
    tiff:endian: lsb
    tiff:photometric: RGB
    tiff:rows-per-strip: 1
  Artifacts:
    filename: /mnt/stock/raster/raster/Nantes_Ouest_lambert2.tif
    verbose: true
  Tainted: False
  Filesize: 1.5834GB
  Number pixels: 527.3M
  Pixels per second: 161.8MB
  User time: 3.260u
  Elapsed time: 0:04.259
  Version: ImageMagick 6.8.9-8 Q16 x86_64 2014-11-18 http://www.imagemagick.org
```

What we get:

http://imgur.com/VbCfDTo

**Comment by haraldk** [comment] 2015-10-12 12:12
Hi Nicholas,

Thanks foe reporting!

That does indeed look a little strange. Can you please share a sample file that has the same problem (but preferably something smaller than 1.5 GB)? I can also use a download link to your, and try to recreate a (smaller) test file for a test case. 

Looks to me like planar/channeled data interpreted as interleaved. But without being able to reproduce, I'm just guessing. :-)


Beest regards,

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-12 12:19
Hi,

This image is not publicly available, and this is a special case. In order to further investigate, do you have a GUI that use your library with some debugging features ?

Thanks,

**Comment by haraldk** [comment] 2015-10-12 12:36
I understand. 

You could try the following command to have output the TIFF IFDs (metadata in the file):

    java -cp <paths-to-necessary-jars> -Dcom.twelvemonkeys.imageio.plugins.tiff.debug=true com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader <your-troublesome.tif>

(You might need to specify extra max heap to to actually display the image, but the debug output is the most interesting).

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-12 12:45
I run your command. Here the output:
```
Reading using: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@21800bc                                                                                                   
Byte order: LITTLE_ENDIAN                                                                                                                                                       
Number of images: 1                                                                                                                                                             
IFD 0: IFD[256/ImageWidth: 17115 (SHORT), 257/ImageHeight: 30810 (SHORT), 258/BitsPerSample: [8, 8, 8] (SHORT), 259/Compression: 1 (SHORT), 262/PhotometricInterpretation: 2 (SHORT), 273/StripOffsets: [739598, 756713, 773828, 790943 ... 1582610588, 1582627703, 1582644818, 1582661933] (92430) (LONG), 277/SamplesPerPixels: 3 (SHORT), 278/RowsPerStrip: 1 (SHORT), 279/StripByteCounts: [17115, 17115, 17115, 17115 ... 17115, 17115, 17115, 17115] (92430) (LONG), 284/PlanarConfiguration: 2 (SHORT), 339/SampleFormat: [1, 1, 1] (SHORT), 33550: [2.5005306206152853, 2.5005306206152853, 0.0] (DOUBLE), 33922: [0.0, 0.0, 0.0, 265774.9588095063, 2292220.6637689555, 0.0] (DOUBLE), 34735: [1, 1, 0, 7 ... 3076, 0, 1, 9001] (32) (SHORT), 34737: NTF (Paris) / France II|NTF (Paris)| (ASCII)]
Read time: 3190 ms
image: BufferedImage@75bf48de: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@61492336 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 17115 height = 30810 #numDataElements 3 dataOff[0] = 2
```

The rendered image is exactly the same as the screenshot previously posted.

**Comment by haraldk** [comment] 2015-10-12 13:18
Thanks,

As I guessed, this is a planar image (PlanarConfiguration: 2). It seems to be mistaken for interleaved/chunky (PlanarConfiguration: 1). I'll investigate.


Best regards,

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-12 15:00
There is a TODO [here][1]
``` // TODO: Support PlanarConfiguration 2, look at PCXImageReader```

[1]: https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReader.java#L124

**Comment by haraldk** [comment] 2015-10-12 16:02
Ouch... :-P

Looking at the code, it's not all that bad, but there seems to be some work left to support planar data.

I'll fix!

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-13 12:39
Hi,

Nice, thank you.

regards,

**Comment by haraldk** [comment] 2015-10-14 14:13
Ok, 

I have it fixed now locally, hope to push a change soon. Just need to clean up some mess I created along the way... 

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-14 14:17
Great ! We eagerly await the patch :)

**Comment by haraldk** [comment] 2015-10-15 16:45
Fixed in b6e44c5.

**Closed by haraldk** 2015-10-15 16:45 UTC
Labels: Bug

**Comment by nicolas-f** [comment] 2015-10-20 07:43
Hello,

I run your lib with snapshot version. It seems to work now. Thank you.

regards,

**Comment by haraldk** [comment] 2015-10-20 17:17
Good stuff!

Thanks for confirming.

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-23 11:02
Hi,

I'm sorry but the duplicate image stuff is fixed. However I still have a Greyscale image.
Here the new metadata:
```
5.2.0-SNAPSHOT> $JAVA_HOME/bin/java -cp twelvemonkeys-osgi-5.2.0-SNAPSHOT.jar -Xmx4000M -Dcom.twelvemonkeys.imageio.plugins.tiff.debug=true com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader /mnt/stock/raster/raster/Nantes_Ouest_lambert2.tif
Reading using: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader@7796649
Byte order: LITTLE_ENDIAN
Number of images: 1
IFD 0: IFD[256/ImageWidth: 17115 (SHORT), 257/ImageHeight: 30810 (SHORT), 258/BitsPerSample: [8, 8, 8] (SHORT), 259/Compression: 1 (SHORT), 262/PhotometricInterpretation: 2 (SHORT), 273/StripOffsets: [739598, 756713, 773828, 790943 ... 1582610588, 1582627703, 1582644818, 1582661933] (92430) (LONG), 277/SamplesPerPixels: 3 (SHORT), 278/RowsPerStrip: 1 (SHORT), 279/StripByteCounts: [17115, 17115, 17115, 17115 ... 17115, 17115, 17115, 17115] (92430) (LONG), 284/PlanarConfiguration: 2 (SHORT), 339/SampleFormat: [1, 1, 1] (SHORT), 33550: [2.5005306206152853, 2.5005306206152853, 0.0] (DOUBLE), 33922: [0.0, 0.0, 0.0, 265774.9588095063, 2292220.6637689555, 0.0] (DOUBLE), 34735: [1, 1, 0, 7 ... 3076, 0, 1, 9001] (32) (SHORT), 34737: NTF (Paris) / France II|NTF (Paris)| (ASCII)]
[..............................................................................]
Read time: 33073 ms
image: BufferedImage@277c3833: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@4c4db085 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 17115 height = 30810 #numDataElements 3 dataOff[0] = 2
```

I will see with my supervisor if I can send you privately the problematic file. Or found another tif with the same color problem.

**Comment by haraldk** [comment] 2015-10-23 11:21
Hi Nicholas,

Are you saying that the image above is shown as all gray, even though it is RGB (for grayscale/single channel images, planar configuration doesn't make much sense)? 
Can you post two images (excerpts are fine :-) ), showing how it is currently displayed, and how it *should* be displayed?

Apart from the GeoTIFF tags (which I ignore for image data), I don't see anything special about this TIFF (or it's IFD).

-- 
Harald K

**Comment by nicolas-f** [comment] 2015-10-23 11:33
Here a sceenshot of a scaled part of the image. i open it with Gimp on the left, and the view shown by your jar with the same command as before.

![tm_greyscale](https://cloud.githubusercontent.com/assets/1382241/10691595/8e5bc0f6-798a-11e5-9797-63403b3f2ade.jpg)

**Comment by haraldk** [comment] 2015-10-23 12:07
Strange indeed. 

If you send me a download link for the image (I will not share it, unless you give me permission), I'll have a look at it, but it's not obvious to me what is going wrong here. 

I'm using gmail, user harald dot kuhr. 


Best regards,

-- 
Harald K
