### ISSUE TITLE
TIFF - wrong colours

### ISSUE THREAD

**Issue by stealman** [haraldk/TwelveMonkeys#319] opened 2017-02-06 18:24 UTC
Hello I am using TwelveMoneys for opening multipage TIF files (source is scanner). These files typicaly contains printed contracts with QR code.

The problem is, that originally black text on white paper is opened via library as gray text on RED background. Somehow white paper is interpreted as RED (light red) colour. My QR code reader thus unable to read QR code properly.

I would like to attach that source file but it is not supported. 
I have at least attached image that is result (saved as file after opening via this library)

![image5](https://cloud.githubusercontent.com/assets/25592527/22660513/2729162c-eca2-11e6-9293-9442653baf52.jpg)

Thanx in advance for some advices.

**Comment by haraldk** [comment] 2017-02-06 20:29
Hi,

Thanks for reporting!

This looks very much like a typical YCbCr/RGB color space mixup... The most common source of this problem, is an input containing ARGB or RGBA samples, and then writing it as JPEG. If the image looks good if you write it as PNG, this is the problem, and the remedy is to remove the alpha channel  (convert it to a `BufferedImage.TYPE_3BYTE_BGR` or `TYPE_INT_RGB` image) before writing as JPEG.  If the image looks the same if you write it as a PNG, the issue is somewhere in the TIFF reader, and I need to look into it.

I will investigate, but in the mean time, please attach the original source file. You can attach it by renaming it to .png or similar. It won't show up in the issue tracker, but I can download it and rename it back.  

Also, what version of the library are you using? 


Best regards,

-- 
Harald K

**Comment by stealman** [comment] 2017-02-06 23:54
Hello thanx for reply. I was using older version 3.2.1. now I have upgraded to latest version 3.3.2. and it is slightly better - colors are not mixed so badly.

Result on version 3.3.2 after convert to BufferedImage.TYPE_3BYTE_BGR

![scan](https://cloud.githubusercontent.com/assets/25592527/22671562/3aa23cf6-eccf-11e6-8b14-386d1b7276df.jpg)

On this latest version I was able to process some more TIFs but still not all of them. Somehow this "pink" color is problem for QR library to read.

Interesting fact is that source TIF has 8 pages .. 6 of them are only grayscale while 2 of them are colored (pen written signatures - blue) and ONLY these 2 pages are "pinked" this way. Pages with only grayscale content are absolutely ok with white background being really white.

I would provide that source files but I would rather do it via email becuase it contents some private data that shall not be shared on general public. I it possible for you to give me your email address ? 

Thanx very much !!

**Comment by haraldk** [comment] 2017-02-07 07:45
Okay, 

Good!

Seems the YCbCr -> RGB conversion is now mostly okay. The pink/purple tint is probably because the scanner software used some custom coefficients in the encoding, or that the paper really reflects this color... I'll know more when I see the original TIFF. Please email to harald dot. kuhr at gmail , com

I think a quick fix for "helping" the QR library could be to convert the image to gray scale, and increase the contrast a little. Or even convert to pure black/white. 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2017-02-14 13:10
@stealman I can't do anything more about this issue without the original TIFF file, so I will close the issue in a few days. Feel free to reopen once you have emailed me the file.

-- 
Harald K

**Closed** 2017-02-21 12:16 UTC
Labels: Trouble-shooting
