### ISSUE TITLE
Some malformed PSD images never return from `ImageIO.read()` using 3.10.0

### ISSUE THREAD

**Issue by tc-wleite** [haraldk/TwelveMonkeys#860] opened 2023-11-06 21:51 UTC
**Describe the bug**
Testing release 3.10.0, I found a few malformed PSD images that never return from `ImageIO.read()` (once the reading function is called, no exception is thrown but it never returns). Using 3.9.4, an exception was thrown, as expected.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use:
**3.10.0**. It also happens using the master branch.

2. The exact output of `java --version`: 
    openjdk version "11.0.13" 2021-10-19 LTS
    OpenJDK Runtime Environment (build 11.0.13+8-LTS)
    OpenJDK 64-Bit Server VM (build 11.0.13+8-LTS, mixed mode, sharing)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. 
I tested it on Windows 11. 

**To Reproduce**
Run a simple standalone program (below), using the PSD ImageIO plugin 3.10.0.

**Expected behavior**
As the sample images are malformed/incomplete, an exception should be thrown.

**Example code**
```java
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class PSDReadTest {
    public static void main(String[] args) throws IOException {
        File input = new File("1.psd"); // Input image
        File output = new File("1.png"); // Output image
        BufferedImage image = ImageIO.read(input);
        ImageIO.write(image, "png", output);
    }
}
```

**Sample files**
[sample-psd-images.zip](https://github.com/haraldk/TwelveMonkeys/files/13272494/sample-psd-images.zip)

**Stack trace**
Running with the test program using **3.10.0**, no exception is thrown and the program never finishes.

Running with **3.9.4**, I got the following exception, which was expected because the sample images are malformed/incomplete.
```text
Exception in thread "main" java.io.EOFException: Unexpected end of PackBits stream
	at com.twelvemonkeys.io.enc.PackBitsDecoder.readFully(PackBitsDecoder.java:186)
	at com.twelvemonkeys.io.enc.PackBitsDecoder.decode(PackBitsDecoder.java:143)
	at com.twelvemonkeys.io.enc.DecoderStream.fill(DecoderStream.java:179)
	at com.twelvemonkeys.io.enc.DecoderStream.read(DecoderStream.java:123)
	at java.base/java.io.SequenceInputStream.read(SequenceInputStream.java:199)
	at com.twelvemonkeys.imageio.stream.DirectImageInputStream.read(DirectImageInputStream.java:73)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:351)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read8bitChannel(PSDImageReader.java:656)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readImageData(PSDImageReader.java:480)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:429)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1315)
	at PSDReadTest.main(PSDReadTest.java:11)
```

**Additional context**
I found these 4 sample images that trigger the issue, testing with a set with 1,500 PSD files, collected from different sources, so it seems a somewhat rare issue.

Trying to trace down what is going on, I found out that the execution stops during `stream.readFully(rowData, 0, channelWidth);` in `read8bitChannel` method of `PSDImageReader` class. Not sure why, but it seems that `readFully` is waiting forever for bytes not available.

**Comment by haraldk** [comment] 2023-11-07 11:10
Thanks for the report and sample files! 👍🏻 

I can reproduce, the problem is related to some stream-optimizations I did. I'm writing a few tests, will have a fix soon.

**Comment by haraldk** [comment] 2023-11-07 13:13
Fixed in lastest SNAPSHOT. There will be a 3.10.1 bug fix release soon.

**Closed by haraldk** 2023-11-07 13:13 UTC
Labels: Confirmed bug, Reported bug
