### ISSUE TITLE
EOFException reading TIFFfile

### ISSUE THREAD

**Issue by piranhaj** [haraldk/TwelveMonkeys#324] opened 2017-02-17 08:40 UTC
Hi,

I'm getting an EOFException when trying to read the attached tiff (note the extension has been changed to txt so it can be uploaded here). 

Stack trace produced is 
```
java.io.EOFException: Unexpected end of PackBits stream
	at com.twelvemonkeys.io.enc.PackBitsDecoder.readFully(PackBitsDecoder.java:200) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.io.enc.PackBitsDecoder.decode(PackBitsDecoder.java:156) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.io.enc.DecoderStream.fill(DecoderStream.java:178) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.io.enc.DecoderStream.read(DecoderStream.java:122) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:423) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:396) ~[common-io-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1508) ~[imageio-tiff-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:934) ~[imageio-tiff-3.3.2.jar:3.3.2]
```

[sample.txt](https://github.com/haraldk/TwelveMonkeys/files/782640/sample.txt)

I can read similar TIFF images that are in portrait orientation but cannot read ones like the one attached that is in landscape orientation. Don't know if that's got anything to do with the problem though.

**Comment by haraldk** [comment] 2017-02-17 09:14
Hi James,

Thanks for reporting!

I can reproduce the issue using your sample file. I'll look into this as soon as possible, 

Best regards,

-- 
Harald K

**Comment by piranhaj** [comment] 2017-02-17 16:05
Hi Harold, 

The one I attached is landscape. A similar one that works is attached and is portrait. It is `FillOrder` 2 but is compressed with `CCITT Group 4` rather than `PackBits`. 

[portraitSample.txt](https://github.com/haraldk/TwelveMonkeys/files/783648/portraitSample.txt)

**Comment by haraldk** [comment] 2017-08-23 10:32
Hi @piranhaj ,

Sorry for taking so long, I haven't had time to focus on the project for a while... Trying to see if this is something that can be fixed in the 3.4 timeline.

Just to verify, do you have other software that can open and display the first file you sent? If that's the case, can you convert it to PNG or take a screenshot of it, just so I have an idea of what it should look like? I can do a partial read of the file, but it all looks like rubbish that makes no sense at the moment...

-- 
Harald K

**Comment by haraldk** [comment] 2017-08-23 13:07
Never mind, figured it out. 

The bits after PackBits compression is written reversed... This doesn't make much sense to me, but then again, maybe it does, as someone actually created an encoder that writes the data in this way...

-- 
Harald K

**Comment by piranhaj** [comment] 2017-08-23 13:42
Thanks @haraldk, let me know if you need anything from me. Look forwards to testing it out.

**Comment by haraldk** [comment] 2017-12-19 18:33
Fixed in latest master. Sorry about the delay...

.k

**Closed by haraldk** 2017-12-19 18:33 UTC
Labels: Trouble-shooting

**Comment by piranhaj** [comment] 2017-12-20 10:38
Thanks @haraldk. I'll take a look when I get a moment.

**Comment by piranhaj** [comment] 2018-01-12 12:30
Hi @haraldk, I've tested this now and can confirm it's working perfectly. Thanks for fixing this.
