### ISSUE TITLE
tiff save issue in v3.2.1

### ISSUE THREAD

**Issue by gregkotsaftis** [haraldk/TwelveMonkeys#264] opened 2016-06-07 08:09 UTC
This issue did not happen in v3.1.2!
1) Open a tiff
2)  Display it - it shows ok
3)  Invert it upside down and save it
4)  load and display it again - corrupt image displays!
5) open the saved file with Photoshop, the image shows up correctly (inverted)!

See attached files.
[images.zip](https://github.com/haraldk/TwelveMonkeys/files/302080/images.zip)

**Comment by Schmidor** [comment] 2016-06-07 12:22
Could be related to #220

**Comment by gregkotsaftis** [comment] 2016-06-07 13:06
It certainly looks like it!
Can anyone point me to a dev bin build so I can test it?
I got the "head" source but I cannot begin to built all the required libs....

**Comment by Schmidor** [comment] 2016-06-07 13:56
You can try a snapshot build I did yesterday. The snapshot does contain some other changes from my pull requests which are not yet in the master:
https://github.com/Schmidor/TwelveMonkeys/releases/tag/3.3-SNAPSHOT3

**Comment by gregkotsaftis** [comment] 2016-06-07 15:58
Yes, the issue is resolved in v3.3-snapshot it now works properly!
Awaiting the new version!
Thanks!

**Comment by haraldk** [comment] 2016-06-08 07:50
Excellent!

Thank you both for resolving this! 

I'm closing as duplicate of #220 and try to create a new release soon.

-- 
Harald K

**Closed by haraldk** 2016-06-08 07:50 UTC
