### ISSUE TITLE
Image Rotation

### ISSUE THREAD

**Issue by MrZaremba** [haraldk/TwelveMonkeys#594] opened 2021-03-01 21:57 UTC
Hi,

I made a class to rotate images and copy the meta data.  It was working great until some images (cell phone selfie camera only) gave me this exception:

javax.imageio.IIOException: JFIF APP0 must be first marker after SOI

Your library solved this issue.  

However, my rotation code that worked fine started to break.  The pixels are not being rotated correctly anymore.  I am getting black stripes down the sides.  It does not work for all images not just cell phone selfie images.

Here is code (I am an amateur so forgive me if it seems like I do not know what I am talking about):

`
import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.ImageWriter;
import javax.imageio.metadata.IIOMetadata;
import javax.imageio.stream.ImageInputStream;
import javax.imageio.stream.ImageOutputStream;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Iterator;

public class Rotate{
    public static int ROTATERIGHT = 0;
    public static int ROTATELEFT = 1;
    private int rotate;
    File image;
    private String name;

    public Rotate(File image, int rotate){
        this.rotate = rotate;
        this.image = image;
        name = image.getName();
        copyMetaData();
    }
    private void rotateRight(){
        try(FileInputStream stream = new FileInputStream(image);
            ImageInputStream iis = ImageIO.createImageInputStream(image);
        ){
            BufferedImage src = ImageIO.read(stream);
            assert src != null;
            int width = src.getWidth();
            int height = src.getHeight();

            BufferedImage dest = new BufferedImage(height, width, src.getType());
            Graphics2D graphics2D = dest.createGraphics();
            graphics2D.translate((height - width) / 2, (height - width) / 2);
            graphics2D.rotate(Math.PI / 2, height / 2, width / 2);
            graphics2D.drawRenderedImage(src, null);
            Iterator<ImageReader> iterator = ImageIO.getImageReaders(iis);
            ImageReader reader = iterator.next();
            String format = reader.getFormatName();
            ImageIO.write(dest,format,image);
        }catch(IOException e){
            e.printStackTrace();
        }

    }

    private void rotateleft(){
        try(FileInputStream stream = new FileInputStream(image);
            ImageInputStream iis = ImageIO.createImageInputStream(image);){
            BufferedImage src = ImageIO.read(stream);
            assert src != null;
            int width = src.getWidth();
            int height = src.getHeight();

            BufferedImage dest = new BufferedImage(height, width, src.getType());

            Graphics2D graphics2D = dest.createGraphics();
            graphics2D.translate((width - height) / 2, (width - height) / 2);
            graphics2D.rotate(3*Math.PI / 2, height / 2, width / 2);
            graphics2D.drawRenderedImage(src, null);

            Iterator<ImageReader> iterator = ImageIO.getImageReaders(iis);
            ImageReader reader = iterator.next();
            String format = reader.getFormatName();
            ImageIO.write(dest,format,image);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
    private void copyMetaData(){
        try(ImageOutputStream ios = ImageIO.createImageOutputStream(image);
            ImageInputStream inputStream = ImageIO.createImageInputStream(image);
        ){
            ImageReader reader = ImageIO.getImageReadersBySuffix("jpg").next();
            reader.setInput(inputStream);
            IIOMetadata metadata = reader.getImageMetadata(0);
            if(rotate == ROTATERIGHT) rotateRight();
            else if(rotate == ROTATELEFT) rotateleft();
            BufferedImage bi = reader.read(0);
            Iterator<ImageWriter> iter = ImageIO.getImageWritersByFormatName("jpeg");
            ImageWriter writer = iter.next();
            writer.setOutput(ios);
            writer.write(null,new IIOImage(bi, null, metadata), null);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

}
`

**Comment by haraldk** [comment] 2021-03-02 15:16
Hi Paul

I tried your code with some random JPEG images, and did not experience any black stripes as you describe. So I'm closing as not reproducible. 

Feel free to reopen though, if you can create a test case that reproduces this behavior!

That said, I would really advice against using your code as-is, as you'll experience generational JPEG loss due to two re-encodings, and you could have much better performance if you did the read, rotate and write in one go instead of two. The in-place manipulation of the same file using different streams, may also be problematic on some platforms/file systems. 


PS:  If you just want to rotate JPEG images, it's also possible to do this as a lossless operation, using the `jpegtran` utility. I think a Java version exists too. 

The TwelveMonkeys library contains utility code that can rotate (or flip) any image, and also read JPEG images with Exif orientation automatically applied. See the `EXIFUtilities.readWithOrienation` and `TIFFUtilities.applyOrientation` methods in the `contrib` module. 


Best regards,

-- 
Harald K

**Closed by haraldk** 2021-03-02 15:16 UTC

**Comment by MrZaremba** [comment] 2021-03-02 17:09
Thank your for taking the time to write this.  I appreciate you telling me about the general JPEG loss and pointing me in the direction to fix it.
