### ISSUE TITLE
3.9.0 breaks ImageIO when used inside an ObjectInputStream

### ISSUE THREAD

**Issue by lbalazscs** [haraldk/TwelveMonkeys#705] opened 2022-10-17 21:18 UTC
**Describe the bug**
If I upgrade TwelveMonkeys from 3.8.3 to 3.9.0, then the WebP support works fine (which is wonderful!), but some other code breaks. It's quite strange because the broken code only uses ImageIO with the PNG format (with the default JDK decoder), so it shouldn't be affected. Perhaps some global state is modified inside ImageIO?

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.9.0

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 

openjdk version "19" 2022-09-20
OpenJDK Runtime Environment Temurin-19+36 (build 19+36)
OpenJDK 64-Bit Server VM Temurin-19+36 (build 19+36, mixed mode, sharing)

**Example code**
```java	
public class Reproducer {
	public static void main(String[] args) throws IOException, ClassNotFoundException {
		File file = new File("test.dat");
		if (file.exists()) {
			// make sure the test file is re-created
			file.delete();
		}

                // create test file (a gzipped serialized object)
		try (FileOutputStream fos = new FileOutputStream(file)) {
			try (GZIPOutputStream gz = new GZIPOutputStream(fos)) {
				try (ObjectOutputStream oos = new ObjectOutputStream(gz)) {
					oos.writeObject(new B());
					oos.flush();
				}
			}
		}

		// read it back
		try (InputStream is = new FileInputStream(file)) {
			try (GZIPInputStream gs = new GZIPInputStream(is)) {
				try (ObjectInputStream ois = new ObjectInputStream(gs)) {
					B b = (B) ois.readObject();
				}
			}
		}
	}

	static class A implements Serializable {
		private static final long serialVersionUID = 1L;

                // since BufferedImage is not serializable, declare it transient, and write it via ImageIO
		transient BufferedImage img = new BufferedImage(10, 10, BufferedImage.TYPE_BYTE_GRAY);

		private void writeObject(ObjectOutputStream out) throws IOException {
			out.defaultWriteObject();
			ImageIO.write(img, "PNG", out);
		}

		private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
			in.defaultReadObject();
			img = ImageIO.read(in);
		}
	}

	static class B extends A {
		private static final long serialVersionUID = 1L;
		int foo = 3;
	}
}
```

**Stack trace**
```
Exception in thread "main" java.io.IOException: Stream closed
	at java.base/java.util.zip.GZIPInputStream.ensureOpen(GZIPInputStream.java:62)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:113)
	at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2922)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.read(ObjectInputStream.java:3359)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readFully(ObjectInputStream.java:3383)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2613)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2476)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2280)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1760)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:538)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:496)
	at pixelitor.Reproducer.main(Reproducer.java:47)
```

**Comment by haraldk** [comment] 2022-10-18 08:10
Thanks for reporting and creating a reproducible example!

This is likely a bug in the new stream providers, that has shown improved performance in my tests. But there seems to be some wrinkles at least... 😕

Can you try replacing `imageio-core.jar` with [`imageio-core-3.9.0-20221010.122121-45.jar`](https://oss.sonatype.org/content/repositories/snapshots/com/twelvemonkeys/imageio/imageio-core/3.9.0-SNAPSHOT/imageio-core-3.9.0-20221010.122121-45.jar) and see if that removes the issue (I pushed the new stream providers on Sunday)? 

I'll test your example, and report back when I can.

PS: You probably know this, but: When serializing using `ImageIO` inside an `ObjectInput/OutputStream`, it's generally recommended to write an explicit length field *before* the image, and either buffer or us a ranged sub-stream when reading, to avoid alignment issues. There's no guarantee that the reader plugin consumes exactly the same amount of bytes the writer plugin wrote (it could read more or less).

PPS: I had some problems building on JDK 19, but I believe this is mainly a test issue, as I mock some classes that are now sealed, which causes some headache... But I don't think it's a problem running on JDK 19.

**Comment by lbalazscs** [comment] 2022-10-18 09:29
Yes, if I hack my local Maven repository to use this jar, then the exception isn't thrown. I also tested with Java 8, and the issue can be reproduced with it.

I didn't know about the alignment issues you mentioned (I assumed that all image formats already contain some form of length information in the header, and the reader simply uses that to consume the correct number of bytes. I use this only in simple cases - one image in PNG format). But since Pixelitor users will expect to be able to open existing pxc files, I can't work around this issue by tracking the image size explicitly.

**Comment by haraldk** [comment] 2022-10-18 13:32
Thanks for testing! Then at least we have strong indication of what the problem is. 

About the alignment issue, see for example [this SO question](https://stackoverflow.com/q/32094497/1428606).

**Comment by haraldk** [comment] 2022-10-18 15:03
Okay... Found the bug. The problem is that my new streams always close the underlying stream, even when the stream was not created by us... 

This means the first `in.read()` after `ImageIO.read(in)`will fail with `java.io.IOException: Stream closed` as you see. I'll fix.

**Comment by sghpjuikit** [comment] 2022-10-18 21:57
@lbalazscs I have a question. I tried to persist Loaded image on disk for later reading to improve loading speed by removing the need to read, decode and postprocess the image every time. But I realized I didnt know how to serialize BufferedImage. I take it you serialize it to OutputStream as you showed in your code. Do you have any comments about this approach?

**Comment by haraldk** [comment] 2022-10-19 19:18
Closing this. New release is built, and will be arrive on Maven Central shortly.

**Closed by haraldk** 2022-10-19 19:18 UTC
Labels: Confirmed bug, Reported bug

**Comment by lbalazscs** [comment] 2022-10-20 18:19
Hi @sghpjuikit , I serialize images (In my [Pixelitor](https://github.com/lbalazscs/Pixelitor/) project) only for the "pxc format", which uses serialization anyway. If I just had to persist an image, then I would just use a standard lossless image format. If you use ImageIO to write the image into the serialization stream, then you don't save any time, because it will be decoded/encoded anyway. It's also possible to write the raw array behind a BufferedImage, but I don't think it's worth it.

@haraldk I just upgraded to 3.9.3, everything works great now (including the WebP reading), thanks!

**Comment by sghpjuikit** [comment] 2022-10-21 06:27
@lbalazscs Yes that's what I thought - there's no point serializing through ImageIO writers and yes, serializing the final image's raw bytes was my intention, but I got confused about the various image in-memory formats so I dropped this idea for now. Thx for the answer.

More here https://github.com/haraldk/TwelveMonkeys/issues/709
