### ISSUE TITLE
Write JPEG Image creates image with red background

### ISSUE THREAD

**Issue by tausendschoen** [haraldk/TwelveMonkeys#604] opened 2021-04-26 10:00 UTC
I extract some images from an PDF document and write that images to file. If i use PNG or GIF as export format, the image is displayed correclty. If I change to the JPEG format, the image gets a red background. I change the compression leven (0.1-1) without any effect. 

I will attache the PDF (see page 29), the PNG and the corresponding JPEG images.

[
![page-29](https://user-images.githubusercontent.com/9352257/116065068-e9024280-a686-11eb-8455-2ae8671e7aa8.png)
![page-29](https://user-images.githubusercontent.com/9352257/116065080-ec95c980-a686-11eb-9069-cf5f08543e49.jpg)
[Schwarz-Weiß-Bilder.pdf](https://github.com/haraldk/TwelveMonkeys/files/6376094/Schwarz-Weiss-Bilder.pdf)

](url)

**Comment by haraldk** [comment] 2021-04-26 10:12
Hi Michael,

I don't know the code you are using, so I can't say anything about *why* this happens... But, if I read the file using the TwelveMonkeys ImageIO JPEGImageReader, the JPEG looks just like your PNG. However, it does contain an alpha channel (transparency information) that is normally not supported by JPEG software (on my Mac, I don't see a red background, only a totally black image, as it thinks your image is in a CMYK color space).

Try exporting the image again, without the alpha channel, and you should be good. 


Best regards,

-- 
Harald K

**Comment by tausendschoen** [comment] 2021-04-27 05:13
Hello Harald, thanks for your reply. 

I am a novice to area of image processing, so I I try to solve most of my problems by adapting the examples. What I did was to read the PNG file and to write it back as JPEG. I expected, that I will receive nearly the same result (taken the data loss by JPEG compression into concern). 

If you use the code below with the first image, you will get the red colored result image. 

Here is the stripped code:

    public static void main(String[] args) {
        try {
            File inFile = new File("src/main/resources/test.png");
            BufferedImage image = ImageIO.read(inFile);
            String format = "JPEG";

            File outFile = new File( "src/main/resources/test-out." + format.toLowerCase() );
            ImageIO.write(image, format, outFile);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

**Comment by haraldk** [comment] 2021-04-27 06:59
Hi again,

As I said in the previous comment, your image has an alpha channel. If I read the JPEG file using the TwelveMonkeys ImageIO JPEGImageReader, the JPEG looks just like your PNG, because I have added extra alpha channel support there for backwards compatibility with earlier Java versions. I get the same image when converting using the code sample you provided, as with the original image you attached. 

The problem is that alpha channels are not commonly supported by JPEG software. You need to remove the alpha channel, even if there are no transparent parts in your image. If you need help implementing this and other features, I suggest a general Q & A forum, like StackOverflow. For example, have a look at [Removing transparency in PNG BufferedImage](https://stackoverflow.com/a/26918760/1428606). Hope that helps!

I'm closing this for now.

Best regards,

-- 
Harald K

**Closed by haraldk** 2021-04-27 06:59 UTC
Labels: Trouble-shooting
