### ISSUE TITLE
TIFFImageReader: Invalid JPEG file structure: missing SOS marker

### ISSUE THREAD

**Issue by PatrickRi** [haraldk/TwelveMonkeys#265] opened 2016-06-17 05:58 UTC
Hi,

there is an issue with the TIFFImageReader or the imageio-JPEGImageReader and some TIFF files I need to convert. Because when I'm trying to read the TIFF I get the following error:

```javax.imageio.IIOException: Invalid JPEG file structure: missing SOS marker
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:347)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:481)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:602)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1059)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1086)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)```

I'm just tryin to read the file with:
```java
BufferedImage image = ImageIO.read(new File(tiffPath));
if (!ImageIO.write(image, "JPEG", new File("C:\\Users\\Test\\Downloads\\abc.jpg"))) {
      System.out.println("Could not write out JPEG image");
}
```
Unfortunately the TIFF has the compression type Old-style JPEG and I tried various things, but I couldn't figure out what's wrong with that file or with my code?

[WAG160615_020021_001.zip](https://github.com/haraldk/TwelveMonkeys/files/319854/WAG160615_020021_001.zip)

**Comment by haraldk** [comment] 2016-06-17 08:57
Hi Patrick,

Thanks for reporting! 

Your code is fine, it should work as-is.

The problem is the "old-style" JPEG compression (6) in this particular TIFF file. The problem with "old-style" JPEG is that the specification was flawed, so different software implemented it in different ways, and this is the reason most software don't support or use it any more, and instead has moved to "new style" JPEG compression (7).

This means, even though the `TIFFImageReader` does its best at attempting to read an old-style JPEG compressed TIFF, we still can't (and probably never will be able to) read the files from all the different implementations. Now that I have your sample file though, I will look into it, and see if we can add support for this particular flavor at some point.

In the meantime, try to get another copy of the file using a different compression, or try using another tool to convert it.


Best regards,

-- 
Harald K

**Comment by PatrickRi** [comment] 2016-06-17 09:23
Hi,

thanks for the fast response. I know about the problems with the "old-style" JPEG type. However I have to convert these files and they are only available with this type in the archive. 
I analyzed an multipaged one a few days ago and wasn't able to find any errors with the format, for every JPEG there was an SOS marker and so on.

I hope you are able to find a solution, how the TIFFReader could manage these "broken" files.
Thanks.

**Comment by haraldk** [comment] 2016-06-17 09:32
I see. 

Well, I will give it a shot. 

If you have more of these files, it would be nice to have a few more samples, to make sure I can create a general solution, not one that works just for the one file. :-)

-- 
Harald K

**Comment by haraldk** [comment] 2016-06-17 09:44
Ok.. 

That was easy. :-)

The problem with the files is that they define a bogus value for tag `514/JPEGInterchangeFormatLength` (634 in this case), which resulted in the reader creating a "sub" stream ending prematurely just before the JPEG SOS marker. If I can only find a way to properly detect this special case, we should be good.

If you want to test for yourself, you can download the source, open `TIFFImageReader.java` and change [line 1058](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/main/java/com/twelvemonkeys/imageio/plugins/tiff/TIFFImageReader.java#L1058) to read just

``````java
int jpegLenght = -1;
``````

Build and test. :-)

-- 
Harald K

**Comment by haraldk** [comment] 2016-06-17 14:12
Fixed in c2aa7e3.

Will be included in 3.3 release, in the meantime, you can build your own version and test.

-- 
Harald K

**Closed by haraldk** 2016-06-17 14:12 UTC
Labels: New feature, Trouble-shooting

**Comment by PatrickRi** [comment] 2016-06-22 07:44
Hi,

sorry I was on vacation the last few days. 
Thank you so much for the quick solution. I tried your fix already with a multipage one and it works without any problems. So it seems all my images have the same problem. 

Thanks for your help,
Patrick

**Comment by haraldk** [comment] 2016-06-22 07:57
Excellent!

Thanks for the feedback!

-- 
Harald K
