### ISSUE TITLE
IPTCEntry IPTCDirectory must be a public class

### ISSUE THREAD

**Issue by not3** [haraldk/TwelveMonkeys#235] opened 2016-05-02 12:39 UTC
Can't use the metadata
the error is "Cannot access 'IPTCEntry': it is 'public/*package*/' in 'iptc'"

**Comment by haraldk** [comment] 2016-05-02 13:18
Hi,

This is by design. You should only need to access it as an `Entry` (the interface it implements).

Hope that helps,

-- 
Harald K

**Comment by not3** [comment] 2016-05-02 13:32
I cannot understand at all, can you give me some samples, thank you

**Comment by haraldk** [comment] 2016-05-02 14:23
Hi again,

My problem is exactly that, I don't understand *the problem*... You have just posted an error message, out of context, which don't really make a lot of sense to me. So, for better help, tell me some background on what you are trying to achieve, possible posting some code, etc, to help me understand. :-)

Anyway, the normal way of using an `Entry` (which just happens to be an `IPTCEntry`), is as follows:

``````java
Directory iptc = new IPTCReader().read(yourIPTCData);

for (Entry iptcEntry : iptc) {
    // Process each iptcEntry
)
``````

**Comment by not3** [comment] 2016-05-03 02:19
Thanks for your answer, now I get it now

**Comment by haraldk** [comment] 2016-05-06 12:44
Great!

Closing this issue for now.

-- 
Harald K

**Closed by haraldk** 2016-05-06 12:44 UTC
Labels: Trouble-shooting
