### ISSUE TITLE
endless loop attempting to read meta in jpeg

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#119] opened 2015-03-19 17:10 UTC
reader.getImageMetadata(0) on the attached (broken) jpeg file never comes back.
(The attached file is a renamed ZIP file, the jpeg is within)

![endless zip](https://cloud.githubusercontent.com/assets/6665575/6736113/1ec8ace0-ce63-11e4-94d8-63cb06accee1.jpg)

**Comment by haraldk** [comment] 2015-03-19 17:40
Thanks for reporting! 

I can reproduce the bug.
Seems to be one of the fixes for an earlier bug, that introduced this... :-(

I'll fix!


Regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-03-19 20:34
Fixed in 11f33741d496aaccb495877ccca4cb13f7fd3fa0.

**Closed by haraldk** 2015-03-19 20:34 UTC
Labels: Bug
