### ISSUE TITLE
SVG ImageReader returns blurred pictures for SVGs with Viewbox height and width less than the default values

### ISSUE THREAD

**Issue by RishabhS66** [haraldk/TwelveMonkeys#671] opened 2022-04-11 11:34 UTC
The [read()](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java#L121) function in [SVGImageReader.java](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java) returns blurred images if both the height and width obtained from the Viewbox of SVG are less than the defaultHeight and defaultWidth. 

The ZIP file [SVGTestFiles.zip](https://github.com/haraldk/TwelveMonkeys/files/8463557/SVGTestFiles.zip) contains 2 images - **testasset.svg** and **sampleSVG.svg**. File **testasset.svg** has viewbox parameters [0 0 65 65], and produces a blurred image when [read()](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java#L121) function is used (as 65 is less than the default parameters), while **sampleSVG.svg** has viewbox parameters [0 0 2014 1674.641] and thus produces desired image.

The issue occurs in all versions after 3.4.2. A similar issue reported because of updates in v3.4.2 is [this](https://github.com/haraldk/TwelveMonkeys/issues/518).

**Comment by haraldk** [comment] 2022-04-11 15:58
Hi @RishabhS66 ,

I'm not sure I understand what you mean by the `viewBox` dimensions being smaller than the "default" dimensions? What dimensions are these? Where do they come from?

Inside the reader, the `viewBox` dimensions are assigned to `defaultHeight` and  `defaultWidth` as a default, if there are no other ways to determine the size.  

As SVG is scalable, you can request a rendering at the exact size you want, bu providing a source render size to the `ImageReadParam`:

```java
ImageReadParam param = new SVGReadParam();
param.setSourceRenderSize(new Dimension(400, 400));

BufferedImage image = reader.read(0, param);
```

-- 
Harald K

**Comment by RishabhS66** [comment] 2022-04-11 18:42
I am not fully versed with how the code runs for **SVGImageReader.java**, but I have observed the issue whenever the viewBox height and width parameters are less than 400.

I will explain by an example. [Demo.zip](https://github.com/haraldk/TwelveMonkeys/files/8466798/Demo.zip) contains 2 SVGs - **Demo.svg** and **Demo2.svg**.

Code for **Demo.svg** :
```
<svg viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="100%" height="100%"/>
  <circle cx="50%" cy="50%" r="100" fill="white"/>
</svg>
```
This file has viewBox dimensions as 500, and was able to produce proper image when using [read()](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java#L121) function.

Output for ```BufferedImage image = reader.read(0, param);``` -
<div align="center">
    <kbd>
        <img width="895" alt="DemoProper" src="https://user-images.githubusercontent.com/39689610/162806936-698e8703-4724-4562-a0e8-5425450c8cf9.png">
    </kbd>
</div>
<br>

Code for **Demo2.svg** :
```
<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
  <rect x="0" y="0" width="100%" height="100%"/>
  <circle cx="50%" cy="50%" r="20" fill="white"/>
</svg>
```
This file has viewBox dimensions as 100 (less than 400), and produced **blurred** image when using [read()](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java#L121) function. (Can be better observed if you zoom the pictures)

Output for ```BufferedImage image = reader.read(0, param);``` -
<div align="center">
    <kbd>
        <img width="893" alt="DemoFail" src="https://user-images.githubusercontent.com/39689610/162807256-93400e88-f7f6-4f19-8303-c61988d6c9a1.png">
    </kbd>
</div>
<br>

**Comment by RishabhS66** [comment] 2022-04-12 09:41
Hi Harald,

I am working on AEM Assets, and it has a module which generates thumbnails for SVGs in different dimensions when the SVG is uploaded. While running it in debug mode, I observe the BufferedImage *image* variable in IntelliJ, which has the option "Show Image", and I have attached those images as reference. 

On using ```param.setSourceRenderSize(new Dimension(500, 500));```, the pictures are generated properly, but on using ```param.setSourceRenderSize(new Dimension(100, 100));```, the pictures are blurred. Also, ```param.setSourceRenderSize(new Dimension(x, y));``` sets the dimensions of the final image to be displayed a x*y, but we want it to be equal to the original dimensions only.

Could you tell how were the pictures generated by you? Are they obtained after saving the *image* variable in a file? It might give me some perspective of what I am doing wrong, or whether there is some mistake in the module code.

**Comment by haraldk** [comment] 2022-04-12 11:15
> but we want it to be equal to the original dimensions only.

I believe the main problem here is a misconception... 😀 You think there is such a thing as *original dimensions*. However, SVG is *scalable* and your SVG files does not contain any dimensions. Only a `viewBox`, but these are logical coordinates, not pixels. 

In the reader, we need some kind of fallback to be able to render the image, so we use this information as the "size", but only as a fallback, and mainly to get the aspect ratio correct. But this does not mean the the image is *intended* to be displayed in this size. We simply don't know/can't tell...

If you create/generate the SVGs, you can add `width` and `height` attributes to the `svg` root element. This is pixel size, and will make the reader read in this specific size (unless you override using the param). Otherwise, the option is to do as I said above, and specify the output size you want. 

My images are just screenshots made from a Swing application, displaying the `BufferedImage` from the reader as an `ImageIcon`, inside a `JLabel` in a `JFrame` (due to macOS scaling the screenshots are 2x the size they appear on screen,  however, the important part is that they are equal, regardless of the `viewBox` size). 

I wasn't aware that there was a "Show image" debugging option in IntelliJ, but that's useful. Just make sure you compare apples to apples. 😉 

-- 
Harald K

**Comment by RishabhS66** [comment] 2022-04-13 03:57
Hi Harald,

I have to rescale the SVG in different sizes and save it in png and jpeg formats. Using ```param.setSourceRenderSize(new Dimension(x, y));``` only works properly if **x** and **y** match the viewBox height and width parameters (considering height and width are not provided explicitly in SVG file).

**Comment by haraldk** [comment] 2022-04-13 07:41
Yes,

There were code changes at some point, could be around 3.4.2, to use the `viewBox` size as a fallback, instead of the hardcoded 400x400. For some SVGs this change caused different default dimensions. If you mean this is a regression, please add a failing test case or provide a suggestion on how to fix. 

Still, I don't see what the problem with the `setSourceRenderSize(new Dimension(width, height))` solution is... Can you elaborate?

Of course, you need to set the size to something reasonable to keep the aspect ratio. There are methods in the reader to get both the default render size (`reader.getWidth(0)` and `reader.getHeight(0)`) and the aspect ratio directly (`reader.getAspectRatio(0)`). These methods are standard API for all `ImageReader` implementations. 

As an example, to generate a rendering/thumbnail with a maximum size of 256x256, I would use:

```java
int thumbSize = 256;
float aspectRatio = reader.getAspectRatio(0);

ImageReadParam param = new SVGReadParam();
param.setSourceRenderSize(aspectRatio > 1f ? new Dimension(thumbSize, (int) Math.ceil(thumbSize / aspectRatio))
                                           : new Dimension((int) Math.ceil(thumbSize * aspectRatio), thumbSize));

BufferedImage image = reader.read(0, param);
```

Can you please try to explain *why* such a solution is not feasible? What solution (other than going back to the hardcoded 400x400 size) would you prefer?

**Comment by RishabhS66** [comment] 2022-04-19 04:59
Hi Harald,

After further analysis, I realised that the code is working properly, and it was the initial hard-coded 400x400 size that imageio-batik v3.4 reverted to, when viewBox was not supported, that made us set wrong expectations. Thanks for all the patience that you displayed, learnt a lot from the discussion! :)

**Closed** 2022-04-19 05:00 UTC
Labels: Trouble-shooting

**Comment by haraldk** [comment] 2022-04-19 07:10
No problem! 😀

**Comment by haraldk** [comment] 2022-06-10 15:23
@RishabhS66 See #684 which might affect you.

**Comment by RishabhS66** [comment] 2022-06-12 08:36
Sure @haraldk, will look into it once.
