### ISSUE TITLE
java.awt.color.CMMException: Cannot get color transform

### ISSUE THREAD

**Issue by peerke** [haraldk/TwelveMonkeys#128] opened 2015-04-10 06:29 UTC
After reading the question at http://stackoverflow.com/questions/4470958/why-does-loading-this-jpg-using-javaio-give-cmmexception I integrated this library. But still I get the exception below. Is this a bug?

```
java.lang.RuntimeException: Problem with image: IMG_9299.jpg
	at com.peerke.photogallery.servlets.PictureThumbnailServlet.doGet(PictureThumbnailServlet.java:28)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:701)
Caused by: java.awt.color.CMMException: Cannot get color transform
	at sun.java2d.cmm.lcms.LCMS.createNativeTransform(Native Method)
	at sun.java2d.cmm.lcms.LCMSTransform.doTransform(LCMSTransform.java:149)
	at sun.java2d.cmm.lcms.LCMSTransform.colorConvert(LCMSTransform.java:526)
	at java.awt.image.ColorConvertOp.filter(ColorConvertOp.java:571)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readImageAsRasterAndReplaceColorProfile(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1438)
	at javax.imageio.ImageIO.read(ImageIO.java:1298)
	at com.peerke.photogallery.servlets.PictureThumbnailServlet.doGet(PictureThumbnailServlet.java:24)
	... 18 more
```

This pictures are just coming out of Adobe Lightroom.

**Comment by haraldk** [comment] 2015-04-10 07:41
Hi Peter,

Thanks for reporting!

This is an LCMS exception (Little CMS was introduced in OpenJDK 7 and Oracle Java 8), and isn't related to the StackOverflow question you linked, which is quite old. My reader will read the image in that question (I have a copy of the image locally, it seems to have vanished).

Can you please attach the image you have trouble with, and I'll have a look at it?

Most likely, you can work around the problem, using KCMS (if you are on an Oracle JRE). See #124 for details.


Regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-04-15 10:21
Closing for now, as the problem is not reproducable without the image in question. Feel free to re-open if you find an image you can share, that causes this issue.

-- 
Harald K

**Closed by haraldk** 2015-04-15 10:21 UTC
Labels: Trouble-shooting

**Comment by thesunshinerain** [comment] 2015-05-28 16:50
![badtest](https://cloud.githubusercontent.com/assets/12647056/7865574/601a6cd0-052f-11e5-841d-101960881db5.jpg)
I found the attached image in a link in the Java Bug Ticket #6829549.
The Java 8 Reader now works for this image, making it a very tricky situation where I prefer to use twelvemonkeys since it works for some images but now not for others.

**Comment by haraldk** [comment] 2015-05-28 17:01
@thesunshinerain Great find! Can you please open a new issue for this, as this is not the same issue as the OP posted. It's still a bug though.

Thanks,

-- 
Harald K
