### ISSUE TITLE
ArrayIndexOutOfBoundsException for special srcHeight - dstHeight combination

### ISSUE THREAD

**Issue by meonwax** [haraldk/TwelveMonkeys#195] opened 2015-11-26 12:12 UTC
When i have a BufferedImage of dimensions 100x354 and want to resample it to 100x18,
i get an ArrayIndexOutOfBoundsException.

Example code:
```
BufferedImage myImage = new BufferedImage(100, 354, BufferedImage.TYPE_INT_ARGB);
BufferedImageOp resampler = new ResampleOp(100, 18, ResampleOp.FILTER_LANCZOS);

try {
    BufferedImage resizedImage = resampler.filter(myImage, null);
} catch (Exception e) {
    e.printStackTrace();
}
```

StackTrace:
```
java.lang.ArrayIndexOutOfBoundsException: 118
	at com.twelvemonkeys.image.ResampleOp.resample(ResampleOp.java:1500)
	at com.twelvemonkeys.image.ResampleOp.filter(ResampleOp.java:566)
	at com.mycompany.app.App.main(App.java:17)
```

This issue seems to be related to the `srcHeight` - `dstHeight` combination.
Maybe there is something buggy calculating the `yscale` or rounding with `Math.ceil` and `Math.floor`.

**Comment by haraldk** [comment] 2015-11-26 14:05
Hi,

Thanks for reporting! I can reproduce the issue in a test case. Hopefully, I will be able to provide a fix soon. 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-11-26 15:11
It seems changing line 1468 in `ResampleOp` from:

    contribY[i].p = new Contributor[(int) (width * 2.0 + 1)];

to:

    contribY[i].p = new Contributor[(int) Math.round(width * 2.0 + 1)];

...fixes the issue for me. 

I need to do some more visual tests to see if this works okay, but it looks like that's the issue.


-- 
Harald K

**Comment by meonwax** [comment] 2015-11-27 08:58
Thank you for investigating this issue, Harald.
Take your time for thorough tests.
Looking forward for a bugfix release.

**Comment by haraldk** [comment] 2015-11-27 12:22
Fixed in 6db06414af93ec02ceaa955efd44bfe147556fcf.

I'll try to make a bugfix release one of the coming days.

-- 
Harald K

**Comment by meonwax** [comment] 2015-11-27 12:32
Many thanks!

**Comment by meonwax** [comment] 2015-12-14 12:06
Sorry, but i have to reopen this issue:

My test image has the dimensions 2832 x 2832 and i want to resize it to 144 x 144.
-> `java.lang.ArrayIndexOutOfBoundsException: 118`

This time the relevant value is the *width*-combination, i think.
Perhaps you could take a look in this issue.

Regards

**Comment by haraldk** [comment] 2015-12-16 09:22
Hi again,

Seems you are right. Reopening. 
I just pushed a fix (doing the same thing as with the height), and it seems to fix the issue. Can you please test if this does fix the problem for you?

Thanks for following up on the issue! 

-- 
Harald K

**Closed by haraldk** 2015-12-16 09:22 UTC
Labels: Bug

**Comment by meonwax** [comment] 2015-12-16 10:30
I can confirm that this fix works for me.
Thanks.

Will you create a bugfix release for this?

**Comment by haraldk** [comment] 2015-12-16 13:49
I'll try to create a bugfix release as soon as possible. But I don't have much time to work on this before christmas, so worst case is you'll have it early next year. Hope to do it before though.


Best regards,

-- 
Harald K
