### ISSUE TITLE
Writing TIFF files with custom resolution value

### ISSUE THREAD

**Issue by zourious** [haraldk/TwelveMonkeys#139] opened 2015-05-26 14:45 UTC
TIFFImageWriter writes TIFF files only with 72 dpi. I'd like to set that value for myself, maybe via IIOMetadata streamMetadata (argument of TIFFImageWriter#write)

public static final Rational STANDARD_DPI = new Rational(72);
...
entries.add(new TIFFEntry(TIFF.TAG_X_RESOLUTION, STANDARD_DPI));
entries.add(new TIFFEntry(TIFF.TAG_Y_RESOLUTION, STANDARD_DPI));
entries.add(new TIFFEntry(TIFF.TAG_RESOLUTION_UNIT, TIFFBaseline.RESOLUTION_UNIT_DPI));

Changing the resolution unit would also be favorable.

**Comment by haraldk** [comment] 2015-05-27 08:53
Hi Zourious,

I agree, setting the DPI and resolution unit (as well as other meta data) would be a useful feature. My plan is to support this via the meta data (the `imageMetadata` parameter), and use the same (or very similar) native metadata format as the JAI TIFF plugin. 

-- 
Harald K

**Comment by zourious** [comment] 2015-05-27 12:51
I'd like to contribute this, but I don't have the time understanding how JAI does this nor does my employer seems willing to invest time into the matter.

I've done it this way, maybe it helps you.

public class TIFFMetaData extends IIOMetadata {

	public static final String[] FORMATS = new String[] { "native" };

	public static final String NATIVE_NODE = "nativeRootNode";

	public static final String ATT_SOFTWARE = "software";
	public static final String ATT_RESOLUTION_X = "xResolution";
	public static final String ATT_RESOLUTION_Y = "yResolution";
	public static final String ATT_RESOLUTION_UNIT = "unitResolution";

	public static final String UNIT_NONE = "1";
	public static final String UNIT_PPI = "2";
	public static final String UNIT_PPC = "3";

	private final IIOMetadataNode nativeRoot;

	public TIFFMetaData() {
		this.nativeRoot = new IIOMetadataNode(NATIVE_NODE);

	}

	@Override
	public Node getAsTree(String formatName) {
		if (FORMATS[0].equals(formatName)) {
			return this.nativeRoot;
		}
		return null;
	}

	@Override
	public boolean isReadOnly() {
		return false;
	}

	@Override
	public void mergeTree(String formatName, Node root) throws IIOInvalidTreeException {}

	@Override
	public void reset() {}

	@Override
	public String[] getMetadataFormatNames() {
		return FORMATS;
	}
}

TIFFImageWriter (about line 210)

IIOMetadata imageMeta = image.getMetadata();
if (imageMeta != null && imageMeta instanceof DactyTIFFMetaData) {
	DactyTIFFMetaData tiffMeta = (DactyTIFFMetaData) imageMeta;
	IIOMetadataNode rootNode = (IIOMetadataNode) tiffMeta.getAsTree(DactyTIFFMetaData.FORMATS[0]);
	int unit = Integer.parseInt(rootNode.getAttribute(DactyTIFFMetaData.ATT_RESOLUTION_UNIT));
	int resolutionX = Integer.parseInt(rootNode.getAttribute(DactyTIFFMetaData.ATT_RESOLUTION_X));
	int resolutionY = Integer.parseInt(rootNode.getAttribute(DactyTIFFMetaData.ATT_RESOLUTION_Y));
	entries.add(new TIFFEntry(TIFF.TAG_SOFTWARE, rootNode.getAttribute(DactyTIFFMetaData.ATT_SOFTWARE)));
	entries.add(new TIFFEntry(TIFF.TAG_X_RESOLUTION, new Rational(resolutionX)));
	entries.add(new TIFFEntry(TIFF.TAG_Y_RESOLUTION, new Rational(resolutionY)));
	entries.add(new TIFFEntry(TIFF.TAG_RESOLUTION_UNIT, unit));
} else {
	entries.add(new TIFFEntry(TIFF.TAG_SOFTWARE, "TwelveMonkeys ImageIO TIFF writer")); 
	entries.add(new TIFFEntry(TIFF.TAG_X_RESOLUTION, STANDARD_DPI));
	entries.add(new TIFFEntry(TIFF.TAG_Y_RESOLUTION, STANDARD_DPI));
	entries.add(new TIFFEntry(TIFF.TAG_RESOLUTION_UNIT, TIFFBaseline.RESOLUTION_UNIT_DPI));
}

Usage: (example only)

IIOMetadata tiffMeta = new TIFFMetaData();
IIOMetadataNode node = (IIOMetadataNode) tiffMeta.getAsTree(DactyTIFFMetaData.FORMATS[0]);
node.setAttribute(TIFFMetaData.ATT_SOFTWARE, ProductUtil.getApplicationName());
node.setAttribute(TIFFMetaData.ATT_RESOLUTION_X, trace.getResolution().toString());
node.setAttribute(TIFFMetaData.ATT_RESOLUTION_Y, trace.getResolution().toString());
node.setAttribute(TIFFMetaData.ATT_RESOLUTION_UNIT, TIFFMetaData.UNIT_PPI);

**Comment by haraldk** [comment] 2015-05-27 13:31
Good stuff!

The DTD of the JAI TIFF image metadata is "accidentally" checked in [here](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-tiff/src/main/resources/tiff-image-metadata-sun.dtd).

I will use the layout and names of that DTD. 

But I might be able to use some of your code as a starting point. 


-- 
Harald K

**Comment by haraldk** [comment] 2015-08-12 09:20
Fixed in c913ef4 and 61b07cb.

Note that you need to modify your code slightly to use the new functionality, as the metadata formats are different. 

    IIOMetadata tiffMeta = new TIFFImageMetaData();
    IIOMetadataNode root = (IIOMetadataNode) tiffMeta.getAsTree("com_sun_media_imageio_plugins_tiff_image_1.0");  // Alternatively, use the standard format
    ...
    // I suggest you look at the TIFFImageWriterTest for further details, 
    // it shows setting the values using both native and standard formats.

Also, note that you need to use the `IIOMetadata.setFromTree` or `.mergeTree` methods, to "apply" your changes to the metadata object (this is per the `IIOMetadata` API. Your implementations mutates a "live" view of the metadata, this is however, a bug... :-)).

If you (like me) don't really like the ImageIO metadata API, you can also create a new `TIFFImageMetadata` object directly from a collection of `com.twelvemonkeys.imageio.metadata.Entry`s or a `com.twelvemonkeys.imageio.metadata.Directory`.  This might feel more familiar, and look more like your initial code:

    // Until I make EXIFEntry or TIFFEntry public
    final class MyEntry extends AbstractEntry {
        public MyEntry(final short identifier, final Object value) {
            super(identifier, value);
        }
    }

    List<Entry> ifd = new ArrayList();
    ifd.add(new MyEntry(TIFF.TAG_X_RESOLUTION, new Rational(300))); 
    ifd.add(new MyEntry(TIFF.TAG_Y_RESOLUTION, new Rational(300))); 
    ...

     IIOMetadata tiffMeta = new TIFFImageMetadata(ifd);


Best regards,

-- 
Harald K

**Closed by haraldk** 2015-08-12 09:20 UTC
Labels: New feature

**Comment by djarvis** [comment] 2017-07-19 18:55
Hi.  I have a need to do this as well.  Has there been any updates such that to make this whole process easier?  Thanks!

**Comment by haraldk** [comment] 2017-07-19 19:43
@djarvis The above is implemented as intended. The `javax.imageio.metadata` API is as it is, like it or not.

In addition, #204 allows you to use `TIFFEntry` directly, instead of the custom `AbstractEntry` subclass, if you want to go the non-standard route. 



-- 
Harald K
