### ISSUE TITLE
Multiple JPEG streams in single file causes javax.imageio.IIOException: Not a JPEG file: starts with 0xff 0xff

### ISSUE THREAD

**Issue by tmyroadctfig** [haraldk/TwelveMonkeys#202] opened 2016-01-07 03:14 UTC
Hi,

I'm hitting an error trying to convert the following image to PDF. While grabbing the image size to work out how to scale it on the page I'm seeing this error:

```
javax.imageio.IIOException: Not a JPEG file: starts with 0xff 0xff
at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:609)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:603)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.getWidth(JPEGImageReader.java:716)
at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getWidth(Unknown Source)
```

Any help would be appreciated. Also I'll try to track down another sample which is free to use.

Thanks,

Luke

![olympus fe3010 x895](https://cloud.githubusercontent.com/assets/855586/12161324/9b1df67a-b548-11e5-9c51-711c0d8b03ef.jpg)

**Comment by tmyroadctfig** [comment] 2016-01-07 04:01
I forgot to mention that the above image is from here: https://www.flickr.com/photos/26134380@N02/3755842820

**Comment by haraldk** [comment] 2016-01-07 08:05
Hi Luke,

Thanks for reporting!

Can you also provide the code you run when you get the exception? 

I'm able to reproduce the issue, but only when trying to read the second image (the `JPEGImageReader` thinks this file contains two images, for some reason). I think maybe fixing the `getNumImages` method will resolve the issue, unless you are doing something else?


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2016-01-07 08:31
Okay, 

After some more investigation, I've found that the image in question actually contains a low res JPEG after the full res image and the Exif thumbnail. So the `getNumImages(true)` method returning `2` is correct.

The problem instead seems to be that after reading the first image, the logic for locating the second image misinterprets the EOI marker for the Exif thumbnail, and tries to read from there (expecting a SOI), rather than locating the EOI marker for the full res image (where the next SOI marker really is).

I'll see if I can create a fix for this.


Thanks,

-- 
Harald K

**Comment by tmyroadctfig** [comment] 2016-01-08 00:18
Thanks Harald,

That makes sense because our PDFing code will enumerate all images in the image and attempt to add each to a page in the PDF.

Here are two more samples which are under a CC and CC-SA licence:
https://flic.kr/p/6Q1dNZ
https://flic.kr/p/cgren1

Cheers,
Luke



![leaves](https://cloud.githubusercontent.com/assets/855586/12186700/62ed59ec-b5f9-11e5-9113-2f27f7cc7154.jpg)
![people](https://cloud.githubusercontent.com/assets/855586/12186706/70d4eff2-b5f9-11e5-80a2-3d9cb28fbf24.jpg)

**Comment by haraldk** [comment] 2016-01-08 09:42
Thanks!

I've done some more work on this last night, but unfortunately, the bugs are in the `com.sun.imageio.plugins.jpeg.JPEGImageReader` that I delegate reading to, and they are harder to work around than I thought.

Unless you actually need both the full size and the scaled down version of the image, I suggest you create a workaround and only read the first image (index 0) from JPEGs for now.


Best regards,

-- 
Harald K

**Comment by j-p-sequeira** [comment] 2018-06-14 14:05
Oh, and in the skipImage(), before the return, it may be needed to go back 2 bytes: `iis.seek(iis.getStreamPosition() - 2);`

**Comment by haraldk** [comment] 2018-06-18 07:38
@j-p-sequeira I think your idea makes sense! 

I thought about something similar once, but never found the time to test it out. 

If possible, perhaps we could implement it in the `JPEGSegmentImageInputStream` that already contains logic for "fixing" minor JPEG stream issues?

Note that a lot of methods in the reader contains an image index, but we must search for the start of that image only once, to make sure we don't confuse the internal state of the delegate `JPEGImageReader`...


-- 
Harald K

**Comment by j-p-sequeira** [comment] 2018-06-18 16:31
I think it is very doable. Again, every time there is a call with `imageIndex!=0` within `JPEGImageReader`, we pass it as `imageIndex=0` to the delegate before calling a `JPEGSegmentImageInputStream` method, for ex: `positionAtImageIndex(int index)` to position the stream (as long as the Java reader does not try to reposition).

I think I could try to do that if I had a bit of time and if I knew how to use maven/github, I'm a newbie... xP I'd love to have version 3.4 released soon, but I can't make promises.

**Comment by j-p-sequeira** [comment] 2018-06-19 10:36
Ok, I wrote some code, but bare in mind that it is not tested. But I'd try something like this:

In `JPEGSegmentImageInputStream.java` add a field for a list of cached image positions and initialize it on your constructor, then add the new two methods:

```
    // List of cached image positions.
    private final List<Long> imagePositions = new ArrayList<>(1);

    JPEGSegmentImageInputStream(final ImageInputStream stream, final JPEGSegmentStreamWarningListener warningListener) {
        this.stream = notNull(stream, "stream");
        this.warningListener = notNull(warningListener, "warningListener");
        this.imagePositions.add(0L); // First image is at position 0.
    }

    public void positionAtImage(int imageIndex, boolean seekForwardOnly) throws IOException {
        if (imageIndex == 0 && this.getStreamPosition() == 0) {
            // Reading first image and we are at the beginning of the stream.
            return;
        }

        if (seekForwardOnly) {
            // To read a non-zero image index, seeking back is needed.
            throw new IOException("Multi-paged images are not supported on a stream that is set as seek forward only.");
        }

        if (this.imagePositions.size() < imageIndex) {
            // If the position of the image in the stream is not cached...
            this.searchForImagePosition(imageIndex);
        }

        this.seek(this.imagePositions.get(imageIndex));
    }

    private void searchForImagePosition(int imageIndex) throws IOException {
        // Position stream at the last found image.
        this.seek(this.imagePositions.get(this.imagePositions.size() - 1));

        int byteval;
        do {
            // Search for "FF D9 FF D8"...
            byteval = stream.read();
            if (byteval == 0xFF) {
                byteval = stream.read();
                if (byteval == 0xD9) {
                    byteval = stream.read();
                    if (byteval == 0xFF) {
                        byteval = stream.read();
                        if (byteval == 0xD8) {
                            // Found a new image position. Cache it.
                            this.imagePositions.add(this.stream.getStreamPosition() - 2);
                        }
                    }
                }
            }
            // ...while not at the right index and end of file is not reached.
        } while (byteval != -1 && this.imagePositions.size() < imageIndex);

        if (byteval < 0) {
            // Reached end of file before the requested index.
            throw new IndexOutOfBoundsException("Invalid index (" + imageIndex + "). Max index found: " + (this.imagePositions.size() - 1));
        }
    }
```

Then at your `JPEGImageReader.java`, add the method:

```
private void updateInputPositionFor(int imageIndex) throws IOException {
        if(this.getInput() != null && this.getInput() instanceof JPEGSegmentImageInputStream){
            ((JPEGSegmentImageInputStream)this.getInput()).positionAtImage(imageIndex, this.isSeekForwardOnly());
        }
    }
```

Then, it is where I got some doubts... the idea is to change all delegate calls to use index = 0 and call the updateInputPositionFor with the right index before it. For example: 

```
// return delegate.read(imageIndex, param);
// Is replaced with:
this.updateInputPositionFor(imageIndex);
return delegate.read(0, param);
```

and...

```
// ImageTypeSpecifier rawType = delegate.getRawImageType(imageIndex);
// Is replaced with:
this.updateInputPositionFor(imageIndex);
ImageTypeSpecifier rawType = delegate.getRawImageType(0);
```

etc...

However, I'm not too sure exactly where this is needed, as this will cause multiple repositions.

**Comment by haraldk** [comment] 2018-08-17 13:35
The bad news: Implementing this correctly and performant proved *a lot* harder than I thought. 

The good news: I have it working locally now. Just need to clean up, before pushing. :-)

-- 
Harald K

**Comment by haraldk** [comment] 2018-08-18 11:09
Fixed in latest master.

**Closed by haraldk** 2018-08-18 11:09 UTC
Labels: Bug
