### ISSUE TITLE
Can't make ImageIO read other extensions

### ISSUE THREAD

**Issue by pedro991** [haraldk/TwelveMonkeys#153] opened 2015-07-18 10:41 UTC
Hi,

I know the title is a bit airy, but I couldn't find a more useful one..
Anyway, I added the JARs but I still can't let my program read those format.
I think it just doesn't get the plugins, because I made some test with output messages, and I found out that it stop running where it finds this line

buffImgI= ImageIO.read(fileNameOriginal);

So it's probably just an installation error, but I still can't resolve it..

JARs I added:
twelvemonkeys-common-lang-3.1.1.jar
twelvemonkeys-common-io-3.1.1.jar
twelvemonkeys-common-image-3.1.1.jar
twelvemonkeys-imageio-core-3.1.1.jar
twelvemonkeys-imageio-metadata-3.1.1.jar
twelvemonkeys-imageio-pnm-3.1.1.jar
twelvemonkeys-imageio-tiff-3.1.1.jar

Here it is an image of the lines where it gives problems and the JARs I added to the calss path:
![immagine](https://cloud.githubusercontent.com/assets/13315669/8761300/56d71cf2-2d4a-11e5-862d-f147dbd4996f.png)

Thanks for you support;
Roberto

**Comment by haraldk** [comment] 2015-07-18 12:33
I'm not sure what fileNameOriginal is (or what kind of file it refers to), so it's still hard to say exactly. 

I'm also no Eclipse user... But I *think* the problem is that you are adding the JARs to the *build* classpath. Normally that's not needed. Instead, you need to add the JARs to the *runtime* classpath. 


-- 
Harald K

**Comment by pedro991** [comment] 2015-07-18 13:26
Yeah, my bad: fileNameOriginal is a varyable of File type which contains the file's url. That's how it loads the file. 
I'm going to try to inculde the JARs the right way as soon as I can! I knew the problem was due to my inexperience xD 
I'll let you know! 
Thanks again!!

**Comment by haraldk** [comment] 2015-07-18 20:57
Hi again,

I got that `fileNameOriginal` was a `File`... My point is, I don't know its value. I don't have that file, and I don't know it's contents. 

If the file is a Word document, what you describe is the expected behaviour (`buffImgI` will be `null`). If it's a valid TIFF file it should read into a `BufferedImage`, assuming everything is properly installed. :-)

I'm sure this is just a class path issue. Try printing the reader formats for debugging:

    for (String format : ImageIO.getReaderFormatNames()) {
        System.out.println(format);
    }


-- 
Harald K

**Comment by haraldk** [comment] 2015-07-26 15:53
Did you solve this problem? :-)

-- 
Harald K

**Comment by pedro991** [comment] 2015-07-27 11:44
99% of it :D 
As you said, the problem was in the way I added the jars to the classpath.
Now the pnm plugin works fine :) :+1: 
The "problem" is that I can't make the tiff jar work, but I don't really need it and since it's probably just an error of mine I can easily quit minding :D

**Comment by haraldk** [comment] 2015-07-27 11:49
Ok, good stuff!

There was a bug preventing the TIFF *writer* from being registered, but otherwise things should work. But if you don't really need it.... 

I'm closing for now!

-- 
Harald K

**Closed by haraldk** 2015-07-27 11:49 UTC
Labels: Trouble-shooting
