### ISSUE TITLE
"javax.imageio.IIOException: No SOF segment in stream" when using JPEG compression in a TIFF v2

### ISSUE THREAD

**Issue by fkluthe** [haraldk/TwelveMonkeys#584] opened 2021-01-15 12:20 UTC
I still got somewhat the same error as in https://github.com/haraldk/TwelveMonkeys/issues/433 and the provided test image (https://github.com/haraldk/TwelveMonkeys/files/2259496/test.zip).

```
Caused by: javax.imageio.IIOException: No SOF segment in stream
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:888)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:338)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFOldJPEGDecompressor.decodeRaw(TIFFOldJPEGDecompressor.java:651)
	at com.github.jaiimageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2583)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:1144)
	at com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1414)
	at javax.imageio.ImageIO.read(ImageIO.java:1462)
	at javax.imageio.ImageIO.read(ImageIO.java:1357)
```

Environment:
com.twelvemonkeys.imageio:imageio-jpeg:3.6.1
openjdk-8-jre-headless 8u272-b10-0ubuntu1~18.04
18.04.5 LTS

**Comment by haraldk** [comment] 2021-01-15 13:01
Hi,

I see from the stack trace that you are using a different JAI bulid/version than the original #433 issue (the package names are different)... The original bug was caused by a seek in the JPEG plugin that is no longer there, so I'm not sure why the problem still happens. I don't have the resources to test all combinations of third-party (or is that "fourth-party? 😛) plugins and my own, but I did some manual tests at the time if I remember correctly. And most importantly, the file still reads fine using the TwelveMonkeys TIFF plugin. 

If you like me to look further into this, please provide the exact code you use (preferably as a JUnit test case) and the Maven coordinates for your com.github JAI dependency.


Best regards,

-- 
Harald K

**Comment by fkluthe** [comment] 2021-01-18 08:22
I  hacked together a small example on my windows machine: 
[complete.zip](https://github.com/haraldk/TwelveMonkeys/files/5828662/complete.zip)

You can run it with `./gradlew run -Dorg.gradle.java.home="C:\path\to\openJdk\java-11-openjdk-11.0.7.10-1.windows.ojdkbuild.x86_64"`

Funnily enough, with this example the error is reproducible with openjdk 11 but not with openjdk 8. However, i followed my instincts and added the imageio-tiff dependency (see build.gradle). This fixed the issue in the example and in the complex project where the error first occurred. Also the example is working when no com.twelvemonkeys.imageio dependency is defined..

Hope this helps :)

**Comment by haraldk** [comment] 2021-01-18 19:55
Excellent, 

I'll look into it!

-- 
Harald K

**Comment by rashaHm** [comment] 2021-03-07 08:44
hello
please can we help me who can I include jai in my project to read and write tiff image, I use netbeans

**Comment by haraldk** [comment] 2021-03-30 09:03
Hi,

Finally found some time to look into this las night! 

The "problem" here turns out to be that the TIFF file in your sample is little endian, while JPEG is always big endian, and some assumptions the various readers does about the input...

TwelveMonkeys `TIFFImageReader` wraps the input before delegating to a JPEG reader, effectively setting the byte order to big endian. This is the safe option as it prevents other readers to "mess" with its stream. TwelveMonkeys `JPEGImageReader` assumes the input is big endian.

Oracle `TIFFImageReader` apparently does not wrap the input, passing the input directly to the JPEG reader, but assumes the byte order is not changed by the delegate. Oracle `JPEGImageReader` does not make assumptions about byte order. 

This means that the TM TIFF + TM JPEG and TM TIFF + Oracle JPEG will work with no problems. Oracle TIFF + Oracle JPEG obviously works fine. But Oracle TIFF + TM JPEG works only for big endian TIFFs at the moment... 😕

One quick fix could be to just set the endianness in the TM JPEG reader, however, this will cause problems in the Oracle TIFF reader later on, as it will continue reading assuming the byte order of the stream is unchanged. The only other option is to wrap the stream in the TM JPEG reader, causing degraded performance. But well...

Hope to have a fix soon. 😀 


-- 
Harald K

**Comment by haraldk** [comment] 2021-03-30 10:41
Hmm.. Just realized your stack trace actually contains the JAI TIFF plugin, not the Oracle JDK one. 😛 

I think however, the problem is the same, as their source originates from the same source. 

-- 
Harald K

**Comment by haraldk** [comment] 2021-03-30 14:34
Fixed in latest master.

**Closed by haraldk** 2021-03-30 14:34 UTC
Labels: Trouble-shooting

**Comment by fkluthe** [comment] 2021-04-12 13:48
Ah cool, thx for your effort. Will check it out in the next release 👍
