### ISSUE TITLE
WMF files are rendered incorrectly

### ISSUE THREAD

**Issue by lfcnassif** [haraldk/TwelveMonkeys#338] opened 2017-04-10 22:31 UTC
imageio-batik-3.3.2.jar and batik-1.8 dependencies are on classpath. Most wmf files are decoded fine. But others are rendered incorrectly. No exception is thrown. Some are partially rendered, like them was cut off. Some are rendered black, some are rendered white. Triggering files are attached.
[problematic-wmf.zip](https://github.com/haraldk/TwelveMonkeys/files/911644/problematic-wmf.zip)

**Comment by haraldk** [comment] 2017-04-11 09:02
Hi lfcnassif,

Thanks for reporting!

The WMF rendering is handled through the Batik transcoder/rasterizer. If you can write a small code snippet that demonstrates that these files are rendered correctly using only Batik, but incorrect using the WMFImageReader, I'll look into it. 

Otherwise, I'll have to assume that the issue is with the Batik WMF transcoder code, and that the problem should be reported to the Batik team.


Best regards,

-- 
Harald K

**Comment by lfcnassif** [comment] 2017-04-11 19:28
Hi again Harald,

You are right, the issue could be with batik library. As I did not know batik api, I will have no time in near future to write a test code. I guess the problem is with batik. When I have time I will test and report the issue to them if appropriate. Feel free to close this issue if you want.

Thanks
Luis

**Comment by haraldk** [comment] 2017-04-12 08:56
Closing for now. Feel free to reopen or file a new bug, if you find differences between TwelveMonkeys and Batik output.

-- 
Harald K

**Closed by haraldk** 2017-04-12 08:56 UTC
Labels: Trouble-shooting
