### ISSUE TITLE
javax.imageio.metadata.IIOInvalidTreeException: Xdensity attribute out of range

### ISSUE THREAD

**Issue by saibotma** [haraldk/TwelveMonkeys#558] opened 2020-09-04 10:32 UTC
```
javax.imageio.metadata.IIOInvalidTreeException: Xdensity attribute out of range
	at com.sun.imageio.plugins.jpeg.MarkerSegment.getAttributeValue(MarkerSegment.java:164) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JFIFMarkerSegment.updateFromNativeNode(JFIFMarkerSegment.java:266) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JFIFMarkerSegment.<init>(JFIFMarkerSegment.java:151) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromNativeTree(JPEGMetadata.java:2203) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromTree(JPEGMetadata.java:2168) ~[?:1.8.0_212]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:168) 
```

Is this a bug in the plugin or is the Xdensity attribute really out of range?
Unfortunately I was not able to reproduce this issue as I got this from a customer. Will update this thread in case I get some new information.

**Comment by haraldk** [comment] 2020-09-04 14:26
Hmmm.. 

First of all: What version of the TwelveMonkeys ImageIO library are you using? I'm assuming you are using Oracle Java 8 u212, based on the stack trace, if not that's also of interest. 

The X (and Y) density range is [1, 65535], but not knowing what the *actual* value is, it's hard to say what's causing this. I would suspect an uninitialized value of 0 (which is the only unsigned 16 bit value outside the range). 

In any case, it's an invalid value, so unless *the origin* of that value is the TwelveMonkeys library, it's not a bug the plugin. But likely a bug in the encoder that wrote the file you are trying to convert, or your code if you created/modified the metadata. 

If the value really is 0, we could probably use a default here, and write 72 DPI or so.

Best regards, 

-- 
Harald K

**Comment by saibotma** [comment] 2020-09-07 11:41
Thanks for the quick reply.

I am using https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-jpeg/3.6 and you are right about the Java version.

**Comment by haraldk** [comment] 2020-09-17 19:47
@saibotma,

Have you been able to reproduce this issue in a test case or small standalone program? I'm not able to do anything about the issue without further information.

-- 
Harald K

**Comment by haraldk** [comment] 2020-10-12 13:54
Closing as I can't reproduce this. Feel free to reopen, if you find a way to reproduce. 

-- 
Harald K

**Closed by haraldk** 2020-10-12 13:54 UTC
Labels: Trouble-shooting
