### ISSUE TITLE
EOFException reading pcx image and ImageInputStream closed

### ISSUE THREAD

**Issue by TomWolk** [haraldk/TwelveMonkeys#192] opened 2015-11-18 15:27 UTC
I get an java.io.EOFException reading a pcx image. Which is unusual because up till now I got only IIOExceptions but this one is an IOException. What's even worse is that the ImageInputStream is closed after this Exception but I want to reuse the ImageInputStream to use for another reading try of a different implementation.

     at: java.io.DataInputStream.readFully(DataInputStream.java:197)
     at: com.twelvemonkeys.imageio.plugins.pcx.PCXImageReader.readRowByte(PCXImageReader.java:318)
     at: com.twelvemonkeys.imageio.plugins.pcx.PCXImageReader.read(PCXImageReader.java:274)

I used the file from http://www.fileformat.info/format/pcx/sample/00f1243fa2bb44309329f4afaab736fc/index.htm

which is readable by Jimi.

In my code I try to read multiple files and I stop when and Exception is thrown:

          reader.setInput(stream, true, false);
          int maxNumImages;
          if ("JPEG".equals(reader.getFormatName())) {
            maxNumImages = 1; // huge performance gain for jpeg images.
          } else {
            maxNumImages = Integer.MAX_VALUE;
          }
          for (int imageIndex = 0; imageIndex < maxNumImages; ++imageIndex) {
            BufferedImage bi;
            IIOMetadata imageMetadata;
            try {
              imageMetadata = reader.getImageMetadata(imageIndex);
              bi = reader.read(imageIndex, null);
            } catch (IndexOutOfBoundsException e) {
              break;
            } catch (IIOException e) { // happens when a jpg has a photoshop header
              Debug.printError("Image with index " + imageIndex + " can not be read from " + fileName, e);
              break;
            }

**Comment by haraldk** [comment] 2015-11-18 19:36
Hi Thomas,

Thanks for reporting!

I'm unable to download the image from that page, but I believe it is [the same that I already have](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-pcx/src/test/resources/pcx/GMARBLES.PCX) and is part of the test cases for the plugin. The image is really broken (truncated) as far as I can understand, although the missing part is just the two last lines of the image (which are all black because of the border in the image, so you might never know they were missing).

I remember debugging this particular image while originally developing the plugin, scratching my head and pulling my hair, before I eventually came to the conclusion that the image is truncated. There might of course be a bug in the RLE implementation, but it's so simple I can't understand how I could possibly have got it wrong... ;-)

You can read everything up until the missing parts by passing an explicit destination image in the `ImageReadParam` and ignoring the exception if you like. This isn't a completely general solution unfortunately, but probably the best you can get for now.

Also, I don't close the stream anywhere in any of my plugins, as far as I know. However, some of the stream is flushed for efficiency, meaning you can't read it again. The only solution is to either wrap the stream, and override `flushBefore` (just be ware that `getFlushedPosition()` must still work as before), *or*  create a new `ImageInputStream` for each try. Anyway, if you create a test case that exposes a bug where the stream is really closed (I'm not able to reproduce with your code above, but it's incomplete, so it's hard to say), I'll fix ASAP.

PS: If you have JPEG files with Photoshop headers that can't be read with my JPEG plugin, I'd like to see them ASAP to fix the issue. ;-)


Best regards,

-- 
Harald K

**Comment by TomWolk** [comment] 2015-11-19 08:32
Hi Harald,

I made the comment about the Photoshop headers before I added TwelveMonkeys to the the project. With TwelveMonkeys all JPEGS are readable without any problems.

You were right about the ImageInputStream not beeing closed and the IOException is fine considering the file is broken.

I made an ImageInputStreamWrapper and that works for me.

Thanks for the response, kind regards, Thomas

**Comment by haraldk** [comment] 2015-11-19 09:26
Good stuff!

An `ImageInputStream` might be reusable, but unfortunately, it depends. Normally, if an exception happens during header parsing, it's reusable. If it happens during image data decoding it isn't... And of course, it is plugin-specific. So yes, the safest is to create a stream wrapper or create a new new stream each time (or check if `getFlushedPosition() <= 0`, if it is, the stream can be reused).

Anyway, I'm closing this issue as resolved. Don't hesitate to report any other issue you should find! :-)


Regards,

-- 
Harald K

**Closed by haraldk** 2015-11-19 09:26 UTC
Labels: Trouble-shooting
