### ISSUE TITLE
ClassCastExceptions even on isolated application classloaders on Weblogic 12c

### ISSUE THREAD

**Issue by etandes** [haraldk/TwelveMonkeys#467] opened 2019-01-02 03:20 UTC
We have two web applications; AppA (as EAR) uses TwelveMonkeys and AppB (as WAR) uses JAI. These web applications are deployed on Weblogic 12c, wherein each application is isolated from each other. They both have application-level classloaders (to ensure that libraries on one app does not conflict with another), and container-level and system-level classloaders. We've configured the system to ensure that TwelveMonkeys is only loaded through the AppA app-level classloader. However, AppB *somehow* still sees TwelveMonkeys classes and encounters ClassCastExceptions.

**Is there a way to properly enforce TwelveMonkeys to be within the scope of one application only, and not all applications (which this situation seems to point at)?**
		
Is this behavior typically attributed to TwelveMonkeys, or would this be a Weblogic issue? Does TwelveMonkeys play well with multiple applications in other containers?

**Comment by haraldk** [comment] 2019-01-02 17:23
Hi,

Unfortunately, this is likely a general `ImageIO` issue, not directly related to TwelveMonkeys, JAI or even WebLogic. Please read [Deploying the plugins in a web app](https://github.com/haraldk/TwelveMonkeys#deploying-the-plugins-in-a-web-app) for some background.

The problem is that `ImageIO` have a shared, static registry of *all the registered plugins*. The `IIORegistry` will leak references, regardless of the class loaders. It does internally have a concept of an "application context", but it is not the same as a JavaEE application context (it's more like an applet, where each "application" is assumed to have its own thread group). So, because each application will see the other's plugins, you may experience these kinds of exceptions. If possible (I don't know if this is possible in WebLogic), you could force each application to use a separate thread group. Then they would also be in different app contexts, and you should in theory be good.

Another option could be to create a JavaEE replacement for the static methods in `ImageIO` (just the class, not the entire API), with app local plugin registries. But as some plugins depends on other plugins in some cases (ie. TIFF plugin uses JPEG plugin to read JPEG-compressed TIFFs), it may not fully solve the problem...

Perhaps the best bet is to just deploy both JAI and TwelveMonkeys on the system-level, and then have a mechanism to chose the right plugins at runtime from each app. 

-- 
Harald K

**Comment by haraldk** [comment] 2019-01-03 08:21
https://stackoverflow.com/q/54001105/1428606

**Comment by haraldk** [comment] 2019-04-15 12:12
Closing for now, as this is a general ImageIO issue. 
Might reopen if someone comes up with a workaround that can be implemented.

**Closed by haraldk** 2019-04-15 12:12 UTC
Labels: Trouble-shooting
