### ISSUE TITLE
read jpegs with two SOF markers

### ISSUE THREAD

**Issue by millmanorama** [haraldk/TwelveMonkeys#197] opened 2015-12-02 19:34 UTC
When using twelvemonkeys to read the attached file I get the following exception:

> javax.imageio.IIOException: Invalid JPEG file structure: two SOF markers
>	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImage(Native Method)
>	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1236)
>	at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1039)
>	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:362)
>	at javax.imageio.ImageIO.read(ImageIO.java:1448)
>	at javax.imageio.ImageIO.read(ImageIO.java:1352)

![ogaaabu9xqrhiug712ghcd5nwnffoqetns5nuchwmjsb3adonfqo7pwcan8rsszcssgwo-zoioxmzfuldvakcy-ruxyam1t1ubdtqgqr3w31plpqsqbyrvfwwrjj 1](https://cloud.githubusercontent.com/assets/1168227/11541639/40438886-9901-11e5-8cd1-7c8b28b9d418.jpg)

Admittedly, I am pretty sure this file is corrupt, but lots of other software can still open and display this file(even github).   Is there anything you can do to help?

**Comment by haraldk** [comment] 2015-12-03 07:51
Hi Jonathan,

This is an issue with Java exception handling, rather than not being able to read the image. You can't have a value returned and an exception thrown at the same time.

Using code similar to the below, I can read your image:

            File file = new File(arg);

            ImageInputStream input = ImageIO.createImageInputStream(file); // TODO: null check
            Iterator<ImageReader> readers = ImageIO.getImageReaders(input); // TODO: hasNext check
            ImageReader reader = readers.next();
            reader.setInput(input);

            // This is the important part, get or create a ReadParam, 
            // create a destination image to hold the decoded result,
            // then pass that image with the param.
            ImageReadParam param = reader.getDefaultReadParam();
            BufferedImage image = reader.getImageTypes(0).next().createBufferedImage(reader.getWidth(0), reader.getHeight(0));
            param.setDestination(image);

            try {
                image = reader.read(0, param);
            }
            catch (IOException e) {
                // Ignore this exception or display a warning or similar, for exceptions happening during decoding
                e.printStackTrace();
            }

Your image now contains the partly decoded image (and it looks exactly like it does above in my browser).


PS: You'll find the full code in the `JPEGImageReader`'s `main` method.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-12-03 14:10
Closing this as not a bug. 

But feel free to comment or re-open if you have further input on this issue,  or post a new issue should you have any other questions! :-)

-- 
Harald K

**Closed by haraldk** 2015-12-03 14:10 UTC
Labels: Trouble-shooting

**Comment by millmanorama** [comment] 2015-12-03 17:17
Thanks Harald,

I was relying in ImageIO.read, but your explanation make sense and the sample code you provided worked.

**Comment by kasparianr** [comment] 2019-07-02 22:33
So helpful. Thank you. I'm glad I finally found this solution. Many pictures that my phone takes cause ImageIO.read to fail and I had no idea that there was this work-around.
