### ISSUE TITLE
SVGImageReader: Can't overwrite cause with java.awt.image.ImagingOpException: Unable to transform src image

### ISSUE THREAD

**Issue by j-p-sequeira** [haraldk/TwelveMonkeys#453] opened 2018-10-23 14:05 UTC
Some SVG files cause an exception in TwelveMonkeys:

```
java.lang.IllegalStateException: Can't overwrite cause with java.awt.image.ImagingOpException: Unable to transform src image
	at java.lang.Throwable.initCause(Throwable.java:457)
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.readImage(SVGImageReader.java:538)
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.getImage(SVGImageReader.java:562)
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.access$200(SVGImageReader.java:262)
	at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.read(SVGImageReader.java:141)
	...
```

This is because the TranscoderException already initializes the throwable cause with null and thus initCause cannot be called:

```
            catch (Exception ex) {
                TranscoderException exception = new TranscoderException(ex.getMessage());
                exception.initCause(ex);
                throw exception;
            }
```

So it should be changed into something like this:

```
            catch (Exception ex) {
                TranscoderException exception = new TranscoderException(ex.getMessage(), ex);
                throw exception;
            }
```

Alright, but this is not such a big issue. What worries me is the original exception to begin with:
`java.awt.image.ImagingOpException: Unable to transform src image`

Now, since you are using an ARGB image already, this seems to be a Batik bug that it in turn seems to be caused by a Java bug ([see this](https://stackoverflow.com/questions/17343518/batik-fails-on-transformations-since-jre-1-7-0-25))...

The images that cause these exceptions are in the Batik sample folder as follows:
batikYin.svg
logoShadowOffset.svg
textRotateShadows.svg

The problem (at least in the examples above, there may be other triggers) goes way if you edit the feGaussianBlur's stdDeviation parameter in the XML to use only one argument.

For example, this causes the exception:
`<feGaussianBlur stdDeviation="2 3" />`

but this does not:
`<feGaussianBlur stdDeviation="2" />`

I don't think there is much that can be done to fix the `ImagingOpException` but it is just to let you know
: )

**Comment by j-p-sequeira** [comment] 2018-10-23 14:11
Oh, this also has some nice details about the issue:
https://issues.apache.org/jira/browse/BATIK-1106

**Comment by haraldk** [comment] 2018-10-23 14:43
If you look at the commits, I changed the code from what you propose to what it is now, in 2013...  What version of Batik are you using? I don't get the same exception (`IllegalStateException`) here, using the supported Batik 1.9.1.

I do, however, get the `java.awt.image.ImagingOpException: Unable to transform src image` exception (same root cause). This is known issue, unfortunately. It used to work, until JRE 7u45 (see `com.twelvemonkeys.imageio.plugins.svg.SVGImageReaderTest`). You need to talk to the Batik team, or perhaps even the OpenJDK guys... You may want to try with a more recent JRE, to see if it actually fixed again. 

-- 
Harald K

**Comment by j-p-sequeira** [comment] 2018-10-23 15:03
IllegalStateException: Yes, I'm using Batik 1.10, ahaha, didn't know that TranscoderException was broken in earlier versions. Hard to know what to do if that's the case  ( ^ _ ^ ) Well, better not worry about such a trivial thing.

ImagingOpException: Oh, well... I'm running the latest JRE 8 (u191) so it is still broken in Java 8 for sure.

**Comment by haraldk** [comment] 2018-10-23 18:56
Excellent. Closing this (I will probably fix the exception issue at some point though).

-- 
Harald K

**Closed by haraldk** 2018-10-23 18:56 UTC
