### ISSUE TITLE
IOException while reading a particular PSD file

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#390] opened 2017-11-03 04:07 UTC
Following error is observed while reading the attached "1105_T_M_baby.psd"

Google Drive Link of 1105_T_M_baby.psd -
https://drive.google.com/open?id=0B1SBo6BEhvipVFdFdnBhLVRyem8

````
javax.imageio.IIOException: An invalid XML character (Unicode: 0x{2}) was found in the value of attribute "{1}" and element is "1b".
	at com.twelvemonkeys.imageio.metadata.xmp.XMPReader.read(XMPReader.java:87)
	at com.twelvemonkeys.imageio.plugins.psd.PSDXMPData.readData(PSDXMPData.java:71)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageResource.<init>(PSDImageResource.java:68)
	at com.twelvemonkeys.imageio.plugins.psd.PSDXMPData.<init>(PSDXMPData.java:55)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageResource.read(PSDImageResource.java:198)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.readImageResources(PSDImageReader.java:920)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getEmbeddedColorSpace(PSDImageReader.java:328)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeForCompositeLayer(PSDImageReader.java:222)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getRawImageTypeInternal(PSDImageReader.java:143)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.getImageTypes(PSDImageReader.java:263)
	at com.twelvemonkeys.imageio.plugins.psd.PSDImageReader.read(PSDImageReader.java:357)

````

**Comment by haraldk** [comment] 2017-11-03 12:25
Hi Vishal,

There seems to be parts of the stack trace missing, this exception is caused by a SAX parser exception, due to incorrect XML in the XMP (or a bug in SAX). Furter information on what the problem is, can be found there. Unfortunately, I can't fix this problem directly.  

But it should be possible to defer parsing of the XMP data, until it is needed (ie. until someone asks for the metadata). And even then, we could just issue a warning, and ignore the XMP data, as it's not crucial for the display of the image in any way. 

Have you tried the Adobe XMP toolkit for Java, and tested if it can handle the seemingly bad XML? If so, you could try to fix the XMP in these probably rare cases. 

PS: Do you know if the file in question is written by Photoshop? If not, what software did?

-- 
Harald K

**Comment by haraldk** [comment] 2017-11-05 09:34
Should be fixed now, in the latest master.

-- 
Harald K

**Closed** 2017-11-06 12:04 UTC
Labels: Trouble-shooting
