### ISSUE TITLE
Thumbnail creation failing for few SVG images

### ISSUE THREAD

**Issue by anuraggupta228** [haraldk/TwelveMonkeys#299] opened 2016-11-25 10:31 UTC
On uploading of SVG file - [Lynparza_PARPinhibition.svg](https://drive.google.com/file/d/0B_ghLHNxn-FvVWlheTM1eWJRVnM/view?usp=sharing), it is failing to create its thumbnail. Its throwing "java.lang.IllegalArgumentException" at [here](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-batik/src/main/java/com/twelvemonkeys/imageio/plugins/svg/SVGImageReader.java#L132).

**Comment by haraldk** [comment] 2016-11-25 11:35
Hi Anurag,

Thanks for reporting! 

Can you please add the full stacktrace you get.  Also, please state what version of the library and Batik are you using.

I'm currently unable to reproduce the `IllegalArgumentException`. I get a `NullPoninterException` from Batik when I try to read the linked SVG, using the Batik version from the TwelveMonkeys ImageIO 3.3 POM files. 


-- 
Harald K

**Comment by haraldk** [comment] 2016-11-25 12:04
Hi,

Tried you SVG, and the problem seems related to it's CSS. Batik does not support `opacity` on this form:

    opacity:9.090909e-002

Internally, Batik will throw a `DOMException` with the message `"The "opacity" property does not support dimension values."`, but this exception never bubbles up, somehow shadowing the root cause.

If I rewrite it as:

    opacity: 0.09.090909

...the file is read and displayed.

Not sure if this is an issue with Batik or the file, but as the file displays nicely in both IE and Chrome on my computer, I assume it's Batik. ;-)

I suggest you report the issue to the Batik team, and refer to this issue for further details.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2016-12-12 20:37
Closing this issue for now. 

Please refer to the Batik issue for updates or to provide further information. 

-- 
Harald K

**Closed by haraldk** 2016-12-12 20:37 UTC
Labels: Trouble-shooting
