### ISSUE TITLE
Random Missing TIFF tag Exception

### ISSUE THREAD

**Issue by jond02** [haraldk/TwelveMonkeys#308] opened 2017-01-06 20:57 UTC
Hello Harald,

I'm using TwelveMonkeys in a Spring Boot web app (deployed as Jar) where the user can upload any number of images through the interface, and they are then processed on the backend. I'm running into the exception below at random times, while using the same set of test images:

    javax.imageio.IIOException: Missing TIFF tag: ImageWidth
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getValueAsNumberWithDefault(TIFFImageReader.java:277)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getValueAsIntWithDefault(TIFFImageReader.java:292)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getValueAsInt(TIFFImageReader.java:300)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.getWidth(TIFFImageReader.java:307)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:756)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)

The line the exception is thrown at is:

    BufferedImage image = ImageIO.read(new File(filename));

Maven:

    <dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
           <dependency>
                     <groupId>com.twelvemonkeys.imageio</groupId>
                     <artifactId>imageio-tiff</artifactId>
                     <version>3.3.1</version>
            </dependency>
		<dependency>
			<groupId>com.jcraft</groupId>
			<artifactId>jsch</artifactId>
			<version>0.1.53</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>Chilkat</groupId>
			<artifactId>xmp</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>com.drewnoakes</groupId>
			<artifactId>metadata-extractor</artifactId>
			<version>2.9.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<version>4.5.1</version>
		</dependency>
	</dependencies>

Java version 1.8.0_101

I've noticed that the likelihood of the exception happening increases with the number of images being uploaded at once. What would cause this exception to happen at random times with the same images? Let me know if you need any additional info.

Thank you,

Jonathan

**Comment by haraldk** [comment] 2017-01-07 14:28
Hi Jonathan,

I've got no experience with Spring Boot, so I can't really be of much help there. 

The exact exception you are seeing here, is probably a symptom of a failed parsing of a TIFF IFD. The IFD parsing has been made more lenient over time, to allow partial reading of the TIFF structure, which enables us to read some broken TIFFs, where only less relevant data is missing. Of course, it could also be that these are broken TIFFs with no ImageWidth tag, but as you say this happens at random, this is less likely.

However, the cause of the IFD parsing failure is still a mystery. As each invocation of `ImageIO.read(...)` creates a new instance of both `ImageInputStream` and `TIFFImageReader` multiple threads should be no problem. I also done an analysis of the parsing code, and there's really no shared mutable state that could cause this to fail randomly under load/many threads, as far as I can see. In addition, I'm often running massive parallell tests to test the reader on large file sets, and I never experience random errors like you report.

As you use `ImageIO.read(new File(filename))`, my best guess would be to look at the file uploading code (and logs), and make sure you don't (accidentally) reuse filenames, partially overwriting files or similar. How do you currently ensure filename uniqueness? How is the file writing done, both on client and server? Or perhaps some files are not fully uploaded? Do you have errors in your client or server logs related to the file upload? Can you dump the contents of the files, each time a read fails?

I strongly believe the problem is elsewhere in your solution. But if you don't find the problem there, try to isolate the issue and see if you can create a standalone program that causes this issue at random with a fixed set of good TIFF files. Send it to me, and I will look further into it. Until then, I don't think there's much I can help you with. 


Best regards,

-- 
Harald K

**Comment by jond02** [comment] 2017-01-07 22:37
Hi Harald,

Thanks for the quick and detailed response. The files are uploaded from the same directory, so the filenames are unique per upload, when the exception is happening.

I created a standalone version of the app with just the upload and create preview functionality, to try and isolate the issue, and the exception is still happening. Could you take a look when you have a chance?

https://github.com/jond02/ImagePreviewDemo

Test images: https://drive.google.com/open?id=0B8FrShLAYpOEMTdZRnI3UXU1bEU

After the app launches you can load it in a browser at http://localhost:8080. Drag all of the files at once into the Images section of the interface. Sometimes the previews are created, and other times the exception happens.

Thanks for the help.

**Comment by jond02** [comment] 2017-01-08 05:32
After some more testing it appears that the http post might be causing an issue before the Tiff tag exception.

**Comment by haraldk** [comment] 2017-01-09 09:33
Good news!

Thanks for reporting back!

I'll close this issue for now. Feel free to reopen if you have new information/further questions about this issue, or file a new issue if you find other problems with the plugin!


Best regards,

-- 
Harald K

**Closed by haraldk** 2017-01-09 09:33 UTC
Labels: Trouble-shooting

**Comment by jond02** [comment] 2017-01-09 21:34
Sounds good, thanks again Harald!
