### ISSUE TITLE
Error when reading ICO files (version 3.1.2)

### ISSUE THREAD

**Issue by rmuller** [haraldk/TwelveMonkeys#165] opened 2015-08-21 10:48 UTC
When reading [this](http://www.jpg.fr/Images/StaplesFR/shared/favicon.ico) ICO file, i get this error:

descriptor: BitmapRGB[ICOEntry: width: 20, height: 20, colors: 0, planes: 1, bit count: 32, size: 1720, offset: 22, BitmapInfoHeader: size: 40 bytes, width: 20, height: 40, planes: 1, bit count: 32, compression: 0, image size: 1600, X pixels per m: 3779, Y pixels per m: 3779, colors used: 1 (unknown), colors important: 1 (all)]
javax.imageio.IIOException: Illegal count -1959962730 for tag 25956 type 19576 @0000dc76
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readEntry(Unknown Source)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(Unknown Source)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readSubdirectories(Unknown Source)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.readDirectory(Unknown Source)
	at com.twelvemonkeys.imageio.metadata.exif.EXIFReader.read(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readMetadata(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readIFD(Unknown Source)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)

When using metadata-extractor or imagemagick no errors appear.

Ronald

**Comment by haraldk** [comment] 2015-08-21 10:57
Hi Ronald,

I downloaded your favicon file, and yes, it does print:

    descriptor: BitmapRGB[ICOEntry: width: 20, height: 20, colors: 0, planes: 1, bit count: 32, size: 1720,  offset: 22, BitmapInfoHeader: size: 40 bytes, width: 20, height: 40, planes: 1, bit count: 32, compression: 0, image size: 1600, X pixels per m: 3779, Y pixels per m: 3779, colors used: 1 (unknown), colors important: 1 (all)]

This is however just an annoying debug statement I forgot to remove, not an exception. The file otherwise reads fine for me.

The stack trace below it, comes from the `TIFFImageReader`, and is likely caused by another file. Unless something very strange happens, the TIFF plugin should not attempt at reading an ICO file. Do you have enough logging information to figure out what file caused the exception in the TIFF plugin, I would very much like to have it. :-)


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-08-21 10:58
Fixed in 4b70b0cf1cf6b1dc0fe8373c1a52971755110b4b.

-- 
Harald K

**Closed by haraldk** 2015-08-21 10:58 UTC
Labels: Bug, Trouble-shooting

**Comment by rmuller** [comment] 2015-08-21 11:18
That was fast! :)

Thanks. Bad from my side, did not notice i were actually two things, debug statement and an exception.

You can download the tif image from here: https://s3-eu-west-1.amazonaws.com/rmuller/L152-combi.tif

Ronald

**Comment by haraldk** [comment] 2015-08-21 11:54
Hi again Roland,

Thanks!

Actually, for the linked image, `exiftool` reports:

    ...
    Warning                         : Bad ExifIFD directory
    ...

So, there is a problem with this file. However, as the problem is only in the Exif sub-IFD, most readers only ignores that, and reads on. I probably shouldn't print stacktraces just like that. At the same time, I have no other way to give warnings fro this part of the code yet... The file still reads fine though.

If this is important to you/your project/your client, please file a separate issue for this (ie. "Remove printStackTrace() from EXIFReader") and attach the image in the issue, by renaming it to `basename + "_tif.png"` (the GitHub issue tracker file support is a little weird).


Best regards,

-- 
Harald K

**Comment by rmuller** [comment] 2015-08-21 12:10
Thanks again. Not a big deal for me, but it looks a little bit ugly. I checked the source code, and maybe it is better to log a warning here. However, i noticed you are not using "standard" (JUL) logging. That would be an improvement.

Anyway, thanks for the support and I am watching your awesome library from now on :)

**Comment by haraldk** [comment] 2015-08-21 13:26
All right, all right... It's friday after all. ;-)

See #166 

-- 
Harald K
