### ISSUE TITLE
Cannot open some JPEGs

### ISSUE THREAD

**Issue by abhijeetmulugu** [haraldk/TwelveMonkeys#294] opened 2016-11-17 10:49 UTC
Hello, I get the following exception while opening some JPEG images

Exception in thread "main" java.lang.IllegalArgumentException: identifier may not be blank
	at com.twelvemonkeys.lang.Validate.notEmpty(Validate.java:47)
	at com.twelvemonkeys.imageio.plugins.jpeg.Application.<init>(Application.java:54)
	at com.twelvemonkeys.imageio.plugins.jpeg.Application.read(Application.java:96)
	at com.twelvemonkeys.imageio.plugins.jpeg.Segment.read(Segment.java:94)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:721)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:784)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:364)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at gridfs.images.App.main(App.java:84)

Can you fix this ? Thanks

**Comment by theigl** [comment] 2016-11-17 11:14
I'm seeing the exact same issue on our production system after upgrading from 3.2.1 to 3.3.

**Comment by abhijeetmulugu27** [comment] 2016-11-17 11:26
So should the version 3.2.1 work fine ?

**Comment by haraldk** [comment] 2016-11-17 11:29
Hi guys,

Thanks for reporting! There has been some changes to the internals of the JPEG plugin related to the JPEG Lossless support, which may have caused this regression. If so, 3.2.1 should work.

"Unfortunately" I don't see this happening with any of my test images. But if you can provide a JPEG sample file that causes this exception, I'll look at it right away! 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2016-11-17 12:46
I dug up some sample files from my huge sample collection, and this is clearly a regression. I'll fix and provide a bugfix release soon.

-- 
Harald K

**Comment by haraldk** [comment] 2016-11-20 19:14
Fixed in latest master.

**Closed by haraldk** 2016-11-20 19:14 UTC
Labels: Bug

**Comment by slorber** [comment] 2016-11-29 15:48
Hi,

Thanks, also having this issue :)

@haraldk do you plan on releasing soon?

**Comment by haraldk** [comment] 2016-11-29 20:05
@slorber Seems this is your lucky day. 😉

[New release is out](https://github.com/haraldk/TwelveMonkeys/releases/latest)

**Comment by slorber** [comment] 2016-11-30 18:23
thanks :)

**Comment by haraldk** [comment] 2017-06-01 06:30
@Macs75 The bug is fixed in the latest master, and will be in the next (3.4) release. But there's no bug release done yet, sorry.

-- 
Harald K

**Comment by Macs75** [comment] 2017-06-01 06:54
No access to nightly build?

**Comment by haraldk** [comment] 2017-06-01 13:18
@Macs75 Sorry, I was wrong (in a hurry...). The issue in question is fixed, and was released in 3.3.1. 

If you still get this exception (or a similar one) using 3.3.2, please create a new issue, include the exact stack trace, Java version and platform, along with a sample file (and possibly code, if a simple `ImageIO.read(...)` doesn't reproduce the problem).

You may also try [building a snapshot from the latest master](https://github.com/haraldk/TwelveMonkeys#building) (I don't have nightly builds). 


Best regards,

-- 
Harald K

**Comment by Macs75** [comment] 2017-06-02 11:11
I got this error 2 days ago after updating to the latest version, but yesterday it has worked fine with the same image. I don't understand, but in case it appear again I will open a new bug as you suggest.

java.lang.IllegalArgumentException: identifier may not be blank
	at com.twelvemonkeys.lang.Validate.notEmpty(Validate.java:47) [common-lang-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.Application.<init>(Application.java:54) [imageio-jpeg-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.Application.read(Application.java:96) [imageio-jpeg-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.Segment.read(Segment.java:94) [imageio-jpeg-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.initHeader(JPEGImageReader.java:721) [imageio-jpeg-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getSOF(JPEGImageReader.java:784) [imageio-jpeg-3.3.2.jar:3.3.2]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:364) [imageio-jpeg-3.3.2.jar:3.3.2]
	at javax.imageio.ImageIO.read(ImageIO.java:1448) [rt.jar:1.7.0_131]
	at javax.imageio.ImageIO.read(ImageIO.java:1352) [rt.jar:1.7.0_131]
	at com.codedreams.school.controller.GalleryController.addphoto(GalleryController.java:252)

**Comment by haraldk** [comment] 2017-06-06 08:14
@Macs75 Seems to me like you have (had) an incorrectly named JAR or an old version of the plugin loaded at the time of the stack trace, as there's no longer a `Validate.notEmpty` invocation in the `Application` constructor (since 3.3.1). Maybe you have multiple versions of the JAR?

-- 
Harald K
