### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by j-p-sequeira** [haraldk/TwelveMonkeys#519] opened 2020-01-28 16:12 UTC
Any chance for the WebP image format to ever be supported? It seems it's becoming a thing (some websites are already using it).

**Comment by haraldk** [comment] 2020-01-29 07:59
Duplicate of #395 

And yes, I like to add support for it. I have a working prototype, but my time budget is up. It's absolutely doable, but until someone wants to support this feature or the project financially, it will not happen any time soon. Keep in mind that just maintaining the current code base is quite a bit of work. Sorry.

Best regards,

-- 
Harald K

**Closed by haraldk** 2020-01-29 07:59 UTC
