### ISSUE TITLE
Colors are inverted

### ISSUE THREAD

**Issue by DANONE-SAP** [haraldk/TwelveMonkeys#185] opened 2015-10-12 12:45 UTC
Hello,
I'm using version 3.1.2 and I'm still having trouble with JPEG (inverted colors).
Wasn't the issue supposed to be sorted?
Thanks

**Comment by haraldk** [comment] 2015-10-12 13:26
Hi,

That depends on what issue you are talking about. Unfortunately, JPEG colors have to be determined by convention, rather than by a standard, as multiple standards exists, and even then a lot of images does not follow the standard (even if they claim to). Especially the problem with inverted colors for CMYK JPEGs extracted from PDFs cannot be solved by the `JPEGImageReader` alone... You will need special code to handle it.

Is your issue inverted CMYK colors? Or RGB mistaken for YCbCr (or vice versa)? Or ARGB mistaken for CMYK (or vv)? 

Please attach a sample JPEG you have problems with.


Best regards,

-- 
Harald K

**Comment by DANONE-SAP** [comment] 2015-10-12 14:00
![_paciucma01](https://cloud.githubusercontent.com/assets/3499760/10429634/507a7c16-70fa-11e5-8593-06a9e94fc713.jpg)

There you go! I don't know how it's generated and I don't have much control on it.

**Comment by haraldk** [comment] 2015-10-12 15:34
Hi,

I can't reproduce the inverted colors issue using the attached image.

Furthermore, despite its extension, the image is not a JPEG. It is a PNG in RGBA (32 bit) mode. It is written by Microsoft Office, according to its meta data, and seems to read and display fine, using the standard `com.sun.imageio.plugins.png.PNGImageReader` (TwelveMonkeys does not currently include a PNG plugin). 

Maybe you attached the wrong image? Otherwise I'm closing this issue as not reproducible.


Best regards,

-- 
Harald K

**Closed by haraldk** 2015-10-12 15:34 UTC
Labels: Trouble-shooting

**Comment by DANONE-SAP** [comment] 2015-10-13 09:51
You are right, there's no issue at all, I was mistaken.
Regards
