### ISSUE TITLE
Unable to modify a JPEGImage10Metadata comment value

### ISSUE THREAD

**Issue by steinarb** [haraldk/TwelveMonkeys#845] opened 2023-10-21 07:26 UTC
I am trying to modify the JFIF comment (note: not an EXIF tag, but the comment in the JFIF metadata) of an image and am running into the issue that the JPEGImage10Metadata object is readonly.

I am trying the approach of getting the metadata as a tree, walking the tree, replacing an attribute and setting the metadata as a tree, as outlined here: https://stackoverflow.com/a/9508479

Is there another way? 

I have looked for ways to copy-and-mutate the JPEGImage10Metadata object, but not found any?

(I can see the existing value in the debugger so that it feels kind of annoying not to be able to change it... I've even considered using reflection... :smile: )

Here is the code that I'm trying to run:
```
    File downloadImageUrlToTempFile(AlbumEntry albumEntry, Path tempDir) {
        var imageUrl = albumEntry.getImageUrl();
        if (imageUrl == null || imageUrl.isEmpty()) {
            throw new OldAlbumException(String.format("Unable to download album entry matching id=%d, imageUrl is missing", albumEntry.getId()));
        }

        var fileName = findFileNamePartOfUrl(imageUrl);
        var tempfile = tempDir.resolve(fileName).toFile();
        IIOImage image = null;
        ImageWriter writer = null;
        try {
            HttpURLConnection connection = getConnectionFactory().connect(imageUrl);
            connection.setRequestMethod("GET");
            try(var inputStream = ImageIO.createImageInputStream(connection.getInputStream())) {
                var readers = ImageIO.getImageReaders(inputStream);
                if (readers.hasNext()) {
                    var reader = readers.next();
                    writer = ImageIO.getImageWriter(reader);
                    reader.setInput(inputStream);
                    image = reader.readAll(0, null);
                }
            }
        } catch (IOException e) {
            throw new OldAlbumException(String.format("Unable to download album entry matching id=%d from url=\"%s\"", albumEntry.getId(), albumEntry.getImageUrl()), e);
        }

        var metadata = image.getMetadata();
        var metadataAsTree = metadata.getAsTree("javax_imageio_1.0");
        findJfifCommentNode(metadataAsTree)
            .ifPresent(node -> node.setAttribute("value", albumEntry.getDescription()));
        try {
            metadata.setFromTree("javax_imageio_1.0", metadataAsTree);
        } catch (IIOInvalidTreeException e) {
            throw new OldAlbumException(String.format("Failed to replace comment in local copy of album entry matching id=%d from url=\"%s\"", albumEntry.getId(), albumEntry.getImageUrl()), e);
        }

        try (var outputStream = ImageIO.createImageOutputStream(new FileOutputStream(tempfile))){
            writer.setOutput(outputStream);
            writer.write(image);
            Files.setLastModifiedTime(tempfile.toPath(), FileTime.from(albumEntry.getLastModified().toInstant()));
            return tempfile;
        } catch (IOException e) {
            throw new OldAlbumException(String.format("Unable to save local copy of album entry matching id=%d from url=\"%s\"", albumEntry.getId(), albumEntry.getImageUrl()), e);
        }
    }

    Optional<IIOMetadataNode> findJfifCommentNode(Node metadataAsTree) {
        return StreamSupport.stream(iterable(metadataAsTree.getChildNodes()).spliterator(), false)
            .filter(n -> "Text".equals(n.getNodeName()))
            .findFirst()
            .flatMap(n -> StreamSupport.stream(iterable(n.getChildNodes()).spliterator(), false).findFirst());
    }

    public static Iterable<IIOMetadataNode> iterable(final NodeList nodeList) {
        return () -> new Iterator<IIOMetadataNode>() {

                private int index = 0;

                @Override
                public boolean hasNext() {
                    return index < nodeList.getLength();
                }

                @Override
                public IIOMetadataNode next() {
                    if (!hasNext())
                        throw new NoSuchElementException();
                    return (IIOMetadataNode) nodeList.item(index++);
                }
            };
    }
```

**Comment by haraldk** [comment] 2023-10-21 09:31
Hi Steinar,

Short answer: `JPEGImage10Metadata` is (currently) read-only, see the `isReadOnly` method. Invoking `mergeTree`/`setFromTree` on an instance, will fail. 

Long answer: You should still be able to achieve what you want, see #668. 😀
Especially [this comment](https://github.com/haraldk/TwelveMonkeys/issues/668#issuecomment-1275090715) where I try to outline a workaround. I think it worked for jAlbum. 

Try that first, but if you can't make it work, let me know, and we'll see if I can help.

**Comment by steinarb** [comment] 2023-10-22 06:50
Thanks, Harald! The workaround of using the default metadata of the writer and replacing the content with the modified metadata tree of the writer worked. Working code example below.

Next up for me is to find the exif segment of the metadata, if present, or create one of there isn't one, and then insert 3 values:

1. last modified date
2. the image description
3. the user comment

Can I do this in a simple way from the existing metadata object (where I can see the exif data in the debugger)?
Or do I have to read the exif segment from the input stream?
And when/if I have the exif segent can I easily add it to the default metadata object? 
I assume I will have to insert it into the tree?

```
    File downloadImageUrlToTempFile(AlbumEntry albumEntry, Path tempDir) {
        var imageUrl = albumEntry.getImageUrl();
        if (imageUrl == null || imageUrl.isEmpty()) {
            throw new OldAlbumException(String.format("Unable to download album entry matching id=%d, imageUrl is missing", albumEntry.getId()));
        }

        var fileName = findFileNamePartOfUrl(imageUrl);
        var tempfile = tempDir.resolve(fileName).toFile();
        IIOImage image = null;
        ImageWriter writer = null;
        try {
            HttpURLConnection connection = getConnectionFactory().connect(imageUrl);
            connection.setRequestMethod("GET");
            try(var inputStream = ImageIO.createImageInputStream(connection.getInputStream())) {
                var readers = ImageIO.getImageReaders(inputStream);
                if (readers.hasNext()) {
                    var reader = readers.next();
                    writer = ImageIO.getImageWriter(reader);
                    reader.setInput(inputStream);
                    image = reader.readAll(0, null);
                }
            }
        } catch (IOException e) {
            throw new OldAlbumException(String.format("Unable to download album entry matching id=%d from url=\"%s\"", albumEntry.getId(), albumEntry.getImageUrl()), e);
        }

        var metadata = image.getMetadata();
        var metadataAsTree = metadata.getAsTree("javax_imageio_1.0");
        findJfifCommentNode(metadataAsTree)
            .ifPresent(node -> node.setAttribute("value", albumEntry.getDescription()));

        try (var outputStream = ImageIO.createImageOutputStream(new FileOutputStream(tempfile))){
            writer.setOutput(outputStream);
            var param = writer.getDefaultWriteParam();
            var modifiedMetadata = writer.getDefaultImageMetadata(ImageTypeSpecifiers.createFromRenderedImage(image.getRenderedImage()), param);
            modifiedMetadata.setFromTree("javax_imageio_1.0", metadataAsTree);
            image.setMetadata(modifiedMetadata);
            writer.write(image);
            Files.setLastModifiedTime(tempfile.toPath(), FileTime.from(albumEntry.getLastModified().toInstant()));
            return tempfile;
        } catch (IOException e) {
            throw new OldAlbumException(String.format("Unable to save local copy of album entry matching id=%d from url=\"%s\"", albumEntry.getId(), albumEntry.getImageUrl()), e);
        }
    }

    Optional<IIOMetadataNode> findJfifCommentNode(Node metadataAsTree) {
        return StreamSupport.stream(iterable(metadataAsTree.getChildNodes()).spliterator(), false)
            .filter(n -> "Text".equals(n.getNodeName()))
            .findFirst()
            .flatMap(n -> StreamSupport.stream(iterable(n.getChildNodes()).spliterator(), false).findFirst());
    }

    public static Iterable<IIOMetadataNode> iterable(final NodeList nodeList) {
        return () -> new Iterator<IIOMetadataNode>() {

                private int index = 0;

                @Override
                public boolean hasNext() {
                    return index < nodeList.getLength();
                }

                @Override
                public IIOMetadataNode next() {
                    if (!hasNext())
                        throw new NoSuchElementException();
                    return (IIOMetadataNode) nodeList.item(index++);
                }
            };
    }
```

**Comment by steinarb** [comment] 2023-10-22 06:57
Adding exif to the tree is possibly covered here? https://github.com/haraldk/TwelveMonkeys/issues/586#issuecomment-770718149

(Seems a little cumbersome...?)  Is it easier if the exif segment already exists I wonder?

**Comment by steinarb** [comment] 2023-10-22 19:08
Tried the approach outlined in https://github.com/haraldk/TwelveMonkeys/issues/586#issuecomment-770718149 and https://stackoverflow.com/q/36029295 but I got the following error message when setting the metadata:
```
Caused by: javax.imageio.metadata.IIOInvalidTreeException: Invalid node: markerSequence
```

Here is what I've tried to do: https://gist.github.com/steinarb/0ab59ad7c17b7ac15b757dd67368dad9

Here is the complete stack trace: https://gist.github.com/steinarb/a2ae1019aa90a4ade2ca49387f6135b9

**Comment by haraldk** [comment] 2023-10-22 19:56
Sorry, no time right now,  but: `javax_imageio_1.0` is the format neutral metadata format. You need the “JPEG native” format to access/write Exif, ie `javax_imageio_jpeg_image_1.0`.

**Comment by haraldk** [comment] 2023-10-24 09:23
Did changing to the `javax_imageio_jpeg_image_1.0` metadata format help? 😀 

Your code does *a lot*, so it would probably help to organize things a little different to make things easier to understand... But I'm fairly sure this was the reason for the exception (as there is no `markerSequece` in the "plug-in neutral" format). 

The "plug-in neutral" format is good for getting a few essential values in a standard way, but it's not so good if you need to mess with format specific things like Exif in JPEG. 

[javax_imageio_1.0 DTD](https://docs.oracle.com/javase/8/docs/api///javax/imageio/metadata/doc-files/standard_metadata.html)
[javax_imageio_jpeg_image_1.0 DTD](https://docs.oracle.com/en/java/javase/17/docs/api/java.desktop/javax/imageio/metadata/doc-files/jpeg_metadata.html#image)

**Comment by steinarb** [comment] 2023-10-25 17:47
Ok, now I'm back to getting java.io.EOFException.

The exception comes when I'm trying to read the metadata of the transformed image in the test and it comes when trying to read a stream containing just "Exif" followed by to 0-byte values.

I.e. it looks like the line doesn't do anything:
```
            new TIFFWriter().write(entries, new MemoryCacheImageOutputStream(bytes));
```

The size of the bytes ByteArrayOutputStream doesn't change in the above line.

This is the current version of the complete code: https://gist.github.com/steinarb/251e02cda3de13c9cc2845a2c9020f4a#file-oldalbumserviceprovider-java-L35

**Comment by steinarb** [comment] 2023-10-25 18:43
I did this instead, and then I got further:
```
            try(var imageOutputStream = new MemoryCacheImageOutputStream(bytes)) {
                new TIFFWriter().write(entries, imageOutputStream);
            }
```

Now the EXIF metadata parses without throwing an EOFException.

Current problem: my replacement of the JFIF comment didn't survive the addition of modifying EXIF comments: https://gist.github.com/steinarb/da81e5d71a6d9e44058ef02598972f3a#file-oldalbumserviceprovider-java-L30

**Comment by haraldk** [comment] 2023-10-25 19:12
The latest version (with try-with-resources) closes (and implicitly flushes) the stream, to commit from the memory cache to the underlying `ByteArrayOuputStream`. The previous code would probably also have worked if you explicitly invoked `flush()` on the `MemoryCacheImageOutputStream`. 

Not sure about why the comment didn't survive. As mentioned, there's too much "going on" for me to fully understand what's happening. Are you sure the `findJfifCommentNode` works? Are you sure there was an existing comment in the file to replace? Are you sure the `ifPresent` block is even executed? 

PS: This code won't work as intended:

```java
        var markerSequence = (IIOMetadataNode) metadataAsTree.getElementsByTagName("markerSequence").item(0);
        if (markerSequence == null) {
            markerSequence = new IIOMetadataNode("markerSequence");
            metadataAsTree.appendChild(markerSequence);
        }
```

If there is no `markerSequence` node, the node list will be empty, and there won't be an item 0...

**Comment by steinarb** [comment] 2023-10-26 04:54
>>>>> Harald Kuhr ***@***.***>:

> The latest version (with try-with-resources) closes (and implicitly flushes) the stream, to commit from the memory cache to the underlying `ByteArrayOuputStream`. The previous code would probably also have worked if you explicitly invoked `flush()` on the `MemoryCacheImageOutputStream`. 

Yes, I followed MemoryCacheImageOutputStream up the inheritance
hierarchy until I found Closable and then went for try-with-resource. :-)

> Not sure about why the comment didn't survive. As mentioned, there's too much "going on" for me to fully understand what's happening. Are you sure the `findJfifCommentNode` works? Are you sure there was an existing comment in the file to replace? Are you sure the `ifPresent` block is even executed? 

The tree looks different when I use the native tree, and the ifPresent
block is never executed.

I'm trying to find the right node in the new tree.  As said I can't see
the tree nodes well in the debugger and the debugger goes a bit crazy
when I try to navigate them.

I found that the comment was put into a node named "com" by stepping
through the build of the native tree in the debugger.

But I found a node named "com" directly under markerSequence and tried
replacing it, but that probably wasn't the right one.

> PS: This code won't work as intended:

> ```java
>         var markerSequence = (IIOMetadataNode) metadataAsTree.getElementsByTagName("markerSequence").item(0);
>         if (markerSequence == null) {
>             markerSequence = new IIOMetadataNode("markerSequence");
>             metadataAsTree.appendChild(markerSequence);
>         }
> ```

> If there is no `markerSequence` node, the node list will be empty, and there won't be an item 0...

Thanks! :-) Yes I know. :-)

(I'll make a test case without the node and fix the handling)

**Comment by haraldk** [comment] 2023-10-26 07:07
> I'm trying to find the right node in the new tree.  As said I can't see
> the tree nodes well in the debugger and the debugger goes a bit crazy
> when I try to navigate them.

One thing this odd XML-ish node structure *is* good for, is that it's.. well.. XML. 😀 

You can dump the whole tree like this:

```java
 new XMLSerializer(System.out, "UTF-8").serialize(tree, false);
```

(using `com.twelvemonkeys.xml. XMLSerializer`, other serializers will probably do fine too..)

The only thing you won't see there it the `userObject`s, because the `javax.imageio` API invented `userObject` instead of reusing `userData`, not really sure why...

> I found that the comment was put into a node named "com" by stepping
> through the build of the native tree in the debugger.
> 
> But I found a node named "com" directly under markerSequence and tried
> replacing it, but that probably wasn't the right one.

According to the DTD I referenced above, the `com` (JFIF comment) marker is a child of `markerSequence`. It can't appear anywhere else.

**Comment by steinarb** [comment] 2023-10-26 19:24
>>>>> Harald Kuhr ***@***.***>:

> One thing this odd XML-ish node structure *is* good for, is that it's.. well.. XML. 😀 

> You can dump the whole tree like this:

> ```java
>  new XMLSerializer(System.out, "UTF-8").serialize(tree, false);
> ```

> (using `com.twelvemonkeys.xml. XMLSerializer`, other serializers will probably do fine too..)


Oooh! Nice!  Thanks! Found it: copy-paste-error!

> The only thing you won't see there it the `userObject`s, because the `javax.imageio` API invented `userObject` instead of reusing `userData`, not really sure why...

>> I found that the comment was put into a node named "com" by stepping
>> through the build of the native tree in the debugger.
>> 
>> But I found a node named "com" directly under markerSequence and tried
>> replacing it, but that probably wasn't the right one.

> According to the DTD I referenced above, the `com` (JFIF comment) marker is a child of `markerSequence`. It can't appear anywhere else. 

I ended up putting the comment as an attribute on markerSequence,
because I had forgotten to change the name of the element I was
searching for.

(I dumped out the tree before and after).

Now it is time to tidy up the code.

Current iteration (before tidying) looks like this: https://gist.github.com/steinarb/497c28d27f59e85614b0f221115199f4

**Comment by steinarb** [comment] 2023-10-28 16:35
Here's the tidied up code: https://gist.github.com/steinarb/ec1c22513a64870a880f21e134ea33fb

Now it will reside in a git branch waiting for the OSGi-fied version of Twelvemonkey to be released. :smiley: 

Note that I'm currently just storing the description in the JFIF comment (i.e. the way I did things back in 1996), instead of in the EXIF usercomment.

It's trivial to store it there as well. I take suggestions as what to do (store it in the exif user comment? continue to use the JFIF comment? Use both?).

Do other programs use any of these fields?

I know google photo uses the lastmodifieddate EXIF field.

Does any applications out there use the EXIF ImageDescription?

Does any applications out there use either the JFIF comment (it has been around for a while...)?
Does any applications out there use the EXIF UserComment?

**Comment by haraldk** [comment] 2023-10-30 08:26
> Now it will reside in a git branch waiting for the OSGi-fied version of Twelvemonkey to be released. 😃

I thought I mentioned it, but [3.10.0 with your OSGi support](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.10.0) was released last week. 


> I take suggestions as what to do (store it in the exif user comment? continue to use the JFIF comment? Use both?).
> Do other programs use any of these fields?

[Wikipedia lists a few programs](https://en.wikipedia.org/wiki/Exif#Program_support), but that's just a small subset. I don't have a list of applications, but mostly use only Preview on MacOS, which displays a lot of TIFF and Exif/GPS metadata. You should probably just test with the software you use, or the software you want to support. 

For Exif vs JFIF comment, it's a bit of apples and oranges discussion. The COM marker is just a generic "comment", while the TIFF/Exif tags have a specific semantic meaning, allowing for much richer metadata. I don't see a problem using both. There's also IPTC metadata and XMP metadata worth considering, if you want to jump into the meta data rabbit hole... 😀

**Comment by steinarb** [comment] 2023-10-30 16:39
>>>>> Harald Kuhr ***@***.***>:

>> Now it will reside in a git branch waiting for the OSGi-fied version of Twelvemonkey to be released. 😃
> I thought I mentioned it, but [3.10.0 with your OSGi support](https://github.com/haraldk/TwelveMonkeys/releases/tag/twelvemonkeys-3.10.0) was released last week. 

Oh, nice! That release had slipped past me.  I was busy with other stuff
last week. :-)

I've merged the feature branch to main in the oldalbum application:
 https://github.com/steinarb/oldalbum

I will make a new release one of these days.

I've also updated my minimal demo application for using twelvemonkeys in OSGi:
 https://github.com/steinarb/twelvemonkeys-karaf-demo

>> I take suggestions as what to do (store it in the exif user comment? continue to use the JFIF comment? Use both?).
>> Do other programs use any of these fields?

> [Wikipedia lists a few programs](https://en.wikipedia.org/wiki/Exif#Program_support), but that's just a small subset. I don't have a list of applications, but mostly use only Preview on MacOS, which displays a lot of TIFF and Exif/GPS metadata. You should probably just test with the software you use, or the software you want to support. 

Yep! It doesn't really matter if they are used or not as long as I can
embed the metadata for future usage.

> For Exif vs JFIF comment, it's a bit of apples and oranges discussion. The COM marker is just a generic "comment", while the TIFF/Exif tags have a specific semantic meaning, allowing for much richer metadata. I don't see a problem using both.

Thanks! I'll add both (but with the current push of master only JFIF).

> There's also IPTC metadata and XMP metadata worth considering, if you want to jump into the meta data rabbit hole... 😀 

Hm... I'll study IPTC and XMP metadata, and see how much work it would
be to add them. Thanks!

**Comment by haraldk** [comment] 2023-10-31 12:08
Sounds good! 

I'll close this issue as resolved, unless you have more questions about JPEG metadata? If so just reopen, or create a new, more specific issue.

**Closed by haraldk** 2023-10-31 12:08 UTC
Labels: Trouble-shooting

**Comment by steinarb** [comment] 2026-01-01 16:41
Good morning and happy new year!

I thought I had it working but I discovered during Christmas that if the image has an existing EXIF structure I write my values (datetime with identifier 306, description with identifier 0x010e, and user comment with identifier 37510 to the wrong place): I am writing all of these values to the top of the markerSequence found here:
https://github.com/steinarb/oldalbum/blob/eee2923e117579dd3815adc4491f8d7764988408/oldalbum.backend/src/main/java/no/priv/bang/oldalbum/backend/OldAlbumServiceProvider.java#L794

But what happens is that [I get an extra EXIF structure](https://gist.github.com/steinarb/354752dee9c37b390e78962f0c3735e7#file-gistfile1-txt-L82) in addition to [the one that was there from before](https://gist.github.com/steinarb/354752dee9c37b390e78962f0c3735e7#file-gistfile1-txt-L20).

In addition [I write everything on the top level](https://gist.github.com/steinarb/354752dee9c37b390e78962f0c3735e7#file-gistfile1-txt-L87) when [the user comment should have been nested](https://gist.github.com/steinarb/354752dee9c37b390e78962f0c3735e7#file-gistfile1-txt-L51) inside[ a node with identifier 34665](https://gist.github.com/steinarb/354752dee9c37b390e78962f0c3735e7#file-gistfile1-txt-L20) (the encoding for my UserComment looks broken (should have been 20 bytes long) but this may be an artifact of exiftool...?)

What brought me here:

1. I scanned some negatives on a [Rollei slide scanner](https://www.rollei.de/products/foto-und-diascanner-pdf-s-240-se-20681?_pos=1&_psq=PDF-S+240+SE&_ss=e&_v=1.0)
2. I then edited the scans in [Shotwell](https://shotwell-project.org/) (adjusting the orange level to make the scans less green, flipped mirror image scans and did some cropping) and exported the results from Shotwell
3. Then I tried importing the files exported from shotwell into [oldalbum](https://github.com/steinarb/oldalbum/tree/eee2923e117579dd3815adc4491f8d7764988408) but that failed because [the UserComment lacked an encoding](https://gist.github.com/steinarb/eb0f19e3f5ee8ed9aa06a6a7080cbf1e#file-shotwell-exif-metadata-L51)
4. I made oldalbum more tolerant by [allowing import of UserComment without encoding (assuming UTF8)](https://github.com/steinarb/oldalbum/commit/d001669c9856d556b49d33886651c251a838baca) 
5. I exported files from oldalbum and tried importing them, but the import only had the old metadata
6. I fixed this in oldalbum by [reading all EXIF directories and let the last one win and also to look for UserComment on the top level](https://github.com/steinarb/oldalbum/commit/420a84e64c5cb3d8262b47505861ca535e6b17fb)

But the fix is not really a fix and maybe should be reverted...?

What I want to do, is:

1. Put the DateTime field in the existing EXIF diretctory overwriting any existing values
2. Put the Description in the existing EXIF directory overwriting any existing values
3. If there is no nested EXIF directory in the existing EXIF directory, add one
4. Put the UserComment into the nested EXIF directory overwriting any existing value for UserComment
5. Revert my workaround for [reading more than one EXIF directory and allowing UserComment on top](https://github.com/steinarb/oldalbum/commit/420a84e64c5cb3d8262b47505861ca535e6b17fb)

Currently I have no idea how to do steps 1-4, but we will see what I find out. Wrote this comment mainly to collect my thoughts.

**Comment by steinarb** [comment] 2026-01-02 09:53
I have used XMLSerializer to:

- Serialize [the metadata extracted from the JPEG images](https://gist.github.com/steinarb/5156a09e6f319725131601e3813e85ad) (done [here in the code](https://github.com/steinarb/oldalbum/blob/eee2923e117579dd3815adc4491f8d7764988408/oldalbum.backend/src/main/java/no/priv/bang/oldalbum/backend/OldAlbumServiceProvider.java#L732))
- Serialize [the markerSequence after adding a new EXIF directory](https://gist.github.com/steinarb/42a563a9db338750b925ef9994490d3c) (done [here in the code](https://github.com/steinarb/oldalbum/blob/eee2923e117579dd3815adc4491f8d7764988408/oldalbum.backend/src/main/java/no/priv/bang/oldalbum/backend/OldAlbumServiceProvider.java#L776))

The serialized XML isn't superhelpful, but from what I'm putting in when creating a new EXIF directory, I am guessing that the first two `<unknown markerTag="225" />` are the [EXIF directory](https://gist.github.com/steinarb/eb0f19e3f5ee8ed9aa06a6a7080cbf1e#file-shotwell-exif-metadata-L20) and something called [XMP Directory](https://gist.github.com/steinarb/eb0f19e3f5ee8ed9aa06a6a7080cbf1e#file-shotwell-exif-metadata-L70) in the original image.

What's backing up the quess is that [I find a third  `<unknown markerTag="225" />` after adding my own](https://gist.github.com/steinarb/42a563a9db338750b925ef9994490d3c#file-markersequence-L33).

I guess I will have to try unpacking what I find at  `<unknown markerTag="225" />` to see what I find and what I can do with it?

**Comment by steinarb** [comment] 2026-01-02 09:56
Pinging @haraldk here because there may be interesting information about new devices and their quirks here (Rollei slide scanner which writes UserComment with broken encoding and is writing XMP directory as well as EXIF directory).

**Comment by steinarb** [comment] 2026-01-02 11:00
Tried using TIFFReader to read the byte array pulled from the user object of `<unknown markerTag="225" /`:
```
    Directory findOriginalExifDirectory(IIOMetadataNode markerSequence) {
        var unknown = (IIOMetadataNode) markerSequence.getElementsByTagName("unknown").item(0);
        var rawUserObject = unknown.getUserObject();
        try(var input = new ByteArrayImageInputStream((byte[]) rawUserObject)) {
            return new TIFFReader().read(input);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
```

But this failed because the byte array wasn't leading with a byte order mark:
```
javax.imageio.IIOException: Invalid TIFF byte order mark 'Ex', expected: 'II' or 'MM'
	at com.twelvemonkeys.imageio.metadata.tiff.TIFFReader.read(TIFFReader.java:101)
	at no.priv.bang.oldalbum.backend.OldAlbumServiceProvider.findOriginalExifDirectory(OldAlbumServiceProvider.java:755)
	at no.priv.bang.oldalbum.backend.OldAlbumServiceProvider.writeImageWithModifiedMetadataToOutputStream(OldAlbumServiceProvider.java:738)
	at no.priv.bang.oldalbum.backend.OldAlbumServiceProvider$3.write(OldAlbumServiceProvider.java:729)
	at no.priv.bang.oldalbum.backend.OldAlbumServiceProviderTest.testDownloadAlbumEntryOnExistingImageFromShotwellExport(OldAlbumServiceProviderTest.java:1305)
	...
```

**Comment by steinarb** [comment] 2026-01-06 15:34
@haraldk A possible bug in the TIFF writer so I am putting the information here instead of on stackoverflow. If you confirm that it is an actual bug I can create a separate bug issue with a more appropriate title (if that is desired).

The possible bug is: if the IFD entry isn't the last entry the offset in the byte array written to will be wrong when the writing of the IFD is completed, and the next entry on the top level is completed.

I have a unit test that can be debugged that writes 4 TIFF entries to an EXIF directory in a JPEG:

1. A DateTime entry
2. A DateTimeOriginal entry
3. AnImageDescription entry
4. An IDF entry containing a UserComment entry

When writing the entries are sorted so that the order they are written in, is:
1. A DateTime entry
2. An ImageDescription entry
3. An IDF entry containing a UserComment entry
4. A DateTimeOriginal entry (one of the datetimes end up here, not sure which one)

When the UserComment is written, the current new pos is 91 and when the final datetime starts writing, it starts at position 77, which makes it overwrite part of the UserComment.

To get to the unit test:

1. Clone the project
   ```
   cd /tmp
   git clone https://github.com/steinarb/oldalbum.git
   ```
2. Add the scratch git repository and get the branch I am working on
   ```
   cd /tmp/oldalbum/
   git remote add scratch
   git fetch scratch
   git checkout oldalbum/write-metadata-to-existing-structure
   ```
3. Building that branch will fail with 4 test failures 
   ```
   cd /tmp/oldalbum/
   mvn install
   ```
4. Removing the head commit (which just adds some log traces, ie "heisenbug") will result in just a single test failure in `OldAlbumServiceProviderTest.testDownloadAlbumEntryOnExistingImageFromShotwellExport()`, which is the case described above
   ```
   cd /tmp/oldalbum/
   git checkout -b temp1 HEAD^
   mvn clean install
   ```

**Comment by haraldk** [comment] 2026-01-12 14:36
I would appreciate if you could open a new issue for the above suspected bug, and add your code there as a test case for reproduction. It looks likely to be a bug in this library, related to writing nested IFDs... 

The reason for the sorting is that the TIFF spec mandates that tags are written in numerical ascending order. However, for the nested (Exif) IFD, this only requires that the IFD offset is written in place, the actual IFD will be written later in the file. 

I might be able to look at your code at some point, but creating a separate issue/test case will help me spend more time at fixing the actual problem, less time fighting with project setup. 😀
