### ISSUE TITLE
jpeg metadata YCbCr and 1 channel

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#104] opened 2015-03-02 17:24 UTC
In issue 102 you asked me to "report a bug on one of the other image in the series, if they still have issues (ie. if the metadata still says YCbCr and 1 channel, which obviously can't happen)". So there it is attached :-)

    <?xml version="1.0" encoding="UTF-8"?><javax_imageio_1.0>
      <Chroma>
        <ColorSpaceType name="YCbCr"/>
        <NumChannels value="1"/>
      </Chroma>
      <Compression>
        <CompressionTypeName value="JPEG"/>
        <Lossless value="FALSE"/>
        <NumProgressiveScans value="1"/>
      </Compression>
      <Dimension>
        <ImageOrientation value="normal"/>
      </Dimension>
    </javax_imageio_1.0> 

![176936-p154-1](https://cloud.githubusercontent.com/assets/6665575/6446096/e4a5ecba-c108-11e4-8d6e-a0865e9a60a7.jpg)

**Comment by haraldk** [comment] 2015-03-02 20:23
Thanks! 

I'll look into it! 

-- 
Harald K

**Comment by haraldk** [comment] 2015-03-03 10:26
And now I regret it... ;-)

Unfortunately, there's no quick fix for this issue, as fixing it only for this case will break other cases. 

It also depends somewhat on what is the use case for metadata. Do you want to see the meta data actually stored in the file (it's sometimes useful to get to the ICC profile or other data, even if they don't match the image data), or do you only want to see what the reader interpreted as the intended metadata (probably cleaned up, so that writing it back would adhere to the spec)? 

I think both of these are valid use cases, unfortunately, one can't have both in the current API (at least in no way can you have it for the current `JPEGMetada` implementation).

Open for input. :-)


-- 
Harald K

**Comment by haraldk** [comment] 2015-03-03 13:53
...and I changed my mind again. :-)
I don't think there's much a use case for getting this obviously incorrect value.

Fixed in 37d4c035483b43bf513592afd363df24cbd51f83.

Still open for input about the two different use cases of image meta data in general though. 


Regards,

-- 
Harald K

**Closed by haraldk** 2015-03-03 13:53 UTC
Labels: Bug

**Comment by THausherr** [comment] 2015-03-03 18:54
We only need the NumChannels value, this tells us to read the raster and not to bother with a BufferedImage. You can see our code here:
https://svn.apache.org/viewvc/pdfbox/trunk/pdfbox/src/main/java/org/apache/pdfbox/filter/DCTFilter.java?view=markup&sortby=date

In other words, we don't need any fix related to the image I attached, I only opened this issue because you asked me to :-) Our software works fine with that image with the code from last night. I'm retesting the current code.

**Comment by haraldk** [comment] 2015-03-04 12:49
Sure, I was just wondering if you had some input on the issue of metadata consistency in general. But no problem. :-)

Re: DCTFilter.java, it seems that the code has been through a lot of iterations, and most of this should not be needed using the TwelveMonkeys `JPEGImageReader` (I use many similar techniques in my code already, to correctly determine color space, number of channels etc., you shouldn't need to second-guess this).

My `JPEGImageReader` will generally try to convert the image to the RGB (gray data is left as is) when using the `BufferedImage read(...)` methods. Internally, the image returned is created by consulting the `getImageTypes(..)` method (unless an explicit destination or destination type is passed as in the `ImageReadParam`), and using the first element from this iterator.  

From [ImageReader.getImageTypes(int)](http://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageReader.html#getImageTypes(int)) API doc:

> The first element of the iterator should be the most "natural" type for decoding the image with as little loss as possible. For example, for a JPEG image the first entry should be an RGB image, even though the image data is stored internally in a YCbCr color space.

It might be that conversion to RGB is a little stretch of the meaning "natural", but as Java has no "native" CMYK color space, I do this conversion. RGB is much faster to render and avoids a lot of bug reports of the type "the reader is very slow...". 

If you need the data in its original form, it's still possible to instruct the reader to read the original YCCK/CMYK data as a CMYK `BufferedImage`, by passing the appropriate `ImageTypeSpecifier` as destination type in the `ImageReadParam`.

The other option you have, is to use the `readRaster(...)` method. From the API doc:

 > This method allows formats that normally apply a color conversion, such as JPEG, and formats that do not normally have an associated colorspace, such as remote sensing or medical imaging data, to provide access to raw pixel data.

This means that you will have to do any color space conversion yourself, and will need to consult the meta data, to determine source color space (because the `getRawImageType(...)` method that would otherwise be ideal for this, returns `null` for YCbCr and YCCK, because Java has no such color space...).

If you allow me, here's an updated version of DCTFilter.java decode method, as I think it should be: :-)

    @Override
    public DecodeResult decode(InputStream encoded, OutputStream decoded,
                               COSDictionary parameters, int index) throws IOException
    {
        ImageReader reader = findImageReader("JPEG", "a suitable ImageIO plugin is not installed");
        ImageInputStream iis = null;
        try
        {
            // Either instantiate MemoryCacheImageInputStream directly
            iis = new MemoryCacheImageInputStream(encoded);

            // ...or let client code decide wheter this should be disk cached
            // iis = ImageIO.createImageInputStream(encoded);
            
            // In general, library code should *not* use ImageIO.setUseCache(false), 
            // as the setting is application global, and may interfer with user settings
            // and create unneccessary OutOfMemoryErrors. 
            // In any case, the origingal code invoked setUseCache(false) *after* invoking createImageInputStream(...),
            // this is probably not as intended, as the first invocation would still use disk cache... 

            // Skip one LF if there
            if (iis.read() != 0x0A)
            {
                iis.seek(0);
            }

            reader.setInput(iis);

            // Get the raster 
            BufferedImage image;
            Raster raster;
            
            // Strategy 1:
            // Simple but will not give you CMYK data. Will handle any YCbCr/YCCK color space conversions.
            // Note: Relies on implementation details, in theory, the raster *could* be a non-byte type.
            image = reader.read(0);
            raster = image.getRaster();

            if (raster.getNumBands() == 3)
            {
                // TODO: Consult ColorModel band settings before doing the byte swap, 
                // as the data might already be in RGB layout.
                // BGR to RGB
                raster = fromBGRtoRGB(raster);
            }

            // Strategy 2:
            // Slightly more verbose, will give you CMYK data, and still handle YCbCr/YCCK conversion.
            // Note: Relies on implementation details, in theory, the raster *could* be a non-byte type.
            ImageTypeSpecifier type = null;
            Iterator<ImageTypeSpecifier> types = reader.getImageTypes(0);
            while (types.hasNext()) 
            {
                ImageTypeSpecifier spec = types.next();
                
                if (type == null) 
                {
                    // Default to first ImageTypeSpecifier 
                    type = spec;
                }
                
                if (spec.getColorModel().getColorSpace().getType() == ColorSpace.TYPE_CMYK) 
                {
                    // Only YCCK/CMYK images will contain a TYPE_CMYK ImageTypeSpecifier, so prefer this
                    type = spec;
                    break;
                }
            }

            ImageReadParam param = reader.getDefaultReadParam();
            param.setDestinationType(type);
            image = reader.read(0, param)
            raster = image.getRaster();

            if (raster.getNumBands() == 3)
            {
                // TODO: Consult ColorModel band settings before doing the byte swap, 
                // as the data might already be in RGB layout.
                // BGR to RGB
                raster = fromBGRtoRGB(raster);
            }

            // Strategy 3:
            // Read raster directly, faster. No color conversion done by the reader.
            // Will give you the data exactly as in the stream.
            // YCbCr or YCCK conversion/inversion must be done by DCTFilter class.
            // Not sure if PDF embedded JPEGs are allowed to contain ICC profiles; if they do, 
            // you might need to perform additional ColorConvertOp on the raster. 
            raster = reader.readRaster(0, null);
            
            String colorSpace = getColorSpace(reader); // Get color space from Standard metadata,
            
            if ("YCbCr".equals(colorSpace)) 
            {
                raster = fromYCCtoRGB(raster); // Similar to fromYCCKtoCMYK, feel free to see my code
            } 
            else if ("YCCK".equals(colorSpace)) 
            {
                raster = fromYCCKtoCMYK(raster);
            }
            // ...else, CMYK, GRAY and RGB left as-is.
            
            
            // Common code below...
            
            DataBufferByte dataBuffer = (DataBufferByte)raster.getDataBuffer();
            decoded.write(dataBuffer.getData());
        }
        finally
        {
            if (iis != null)
            {
                iis.close();
            }
            reader.dispose();
        }
        return new DecodeResult(parameters);
    }

    // returns the color space as a string, or an empty string if there is an error getting the meta data
    private String getColorSpace(ImageReader reader) throws IOException
    {
        try
        {
            IIOMetadata imageMetadata = reader.getImageMetadata(0);
            if (imageMetadata == null)
            {
                return "";
            }
            
            IIOMetadataNode metaTree = (IIOMetadataNode) imageMetadata.getAsTree("javax_imageio_1.0");
            Element colorSpaceType = (Element) metaTree.getElementsByTagName("ColorSpaceType").item(0);
            if (colorSpaceType == null)
            {
                return "";
            }
            
            return colorSpaceType.getAttribute("name");
        }
        catch (IOException e)
        {
            return "";
        }
    }

-- 
Harald K

**Comment by THausherr** [comment] 2015-03-04 19:20
Thanks I have mentioned it in the PDFBox issue, and will do a test later this week. However at this time the focus is on supporting both readers, i.e. the default one and yours. 

Re "it seems that the code has been through a lot of iterations" - yes. John did most work on it, and you can feel the pain he had trying to find a way to squeeze as much valid data as possible from the sun reader.

**Comment by biblific** [comment] 2015-03-05 19:37
Thanks - Strategy 3 looks like what we're after, as PDF can contain extra color space information which is external to the JPEG.

**Comment by jahewson** [comment] 2015-03-05 19:38
Thanks - Strategy 3 looks like what we're after, as PDF can contain extra color space information which is external to the JPEG.

**Comment by haraldk** [comment] 2015-03-06 10:04
Makes sense! I don't know the PDF format in depth like you do, but I figured it would make sense to keep common document/page resources like color space external. 

And yes, I can feel your pain. I tried in so many different ways to do some of the same things myself... :-)

-- 
Harald K

**Comment by THausherr** [comment] 2015-03-08 11:21
I just tried the code and it works fine, but only when using twelvemonkeys. Two PDFs are rendered very slightly different, but maybe even better than before. However the code doesn't work with the sun reader, but I assume this is excepted. I'll attach it to the PDFBox issue.

**Comment by haraldk** [comment] 2015-03-09 11:37
Hi,

Good to hear that it works! And yes, it's expected that it won't work with the Sun reader (for anything the Sun reader considers non-spec).

Of interest is also Issue #108, I've reported it using the Oracle bug tracker but I'm not holding my breath... 

-- 
Harald K
