### ISSUE TITLE
Cannot read a specific JPEG

### ISSUE THREAD

**Issue by swisscryptodev** [haraldk/TwelveMonkeys#732] opened 2023-02-10 14:23 UTC
**Describe the bug**
can not read these JPEG image:
ImageIO.read(new URL("https://meebits.app/meebitimages/characterimage?index=7&type=full&imageType=jpg")) returns NULL

**Version information**
3.9.4

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
For example: 
JVM version - 15.0.2

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

**To Reproduce**

1. Compile the below sample code
2. Download the sample image file
3. Run the code with the sample file

**Expected behavior**

**Example code**
ImageIO.read(new URL("https://meebits.app/meebitimages/characterimage?index=7&type=full&imageType=jpg")) returns NULL

**Sample file(s)**
https://meebits.app/meebitimages/characterimage?index=7&type=full&imageType=jpg

**Stak trace**

**Screenshots**

**Additional context**

**Comment by haraldk** [comment] 2023-02-10 14:29
No problem reading the linked image here. 

Are you sure the problem is the image, not the download? What happens if you download the image first, then attempt to read it?

**Comment by haraldk** [comment] 2023-02-14 08:43
Closing this as not reproducible.

**Closed by haraldk** 2023-02-14 08:43 UTC
Labels: Reported bug
