### ISSUE TITLE
Support for 32bpc PSDs 

### ISSUE THREAD

**Issue by ashokpanghal** [haraldk/TwelveMonkeys#325] opened 2017-02-20 11:51 UTC
Question :-
We have couple of 32 bpc PSDs and trying to generate jpeg thumbnails out of those but its always resulting into a blank white jpeg image. does TM support 32 bpc PSD files ? if not, can this be considered for future releases.

**Comment by haraldk** [comment] 2017-02-20 12:05
Yes,

Reading 32 bit per sample PSDs in either Greyscale, RGB or CMYK (with or without alpha) is supported and should work (you should get an exception if your image isn't supported). 

However, I doubt that the `JPEGImageWriter` will know how to handle such images... There's also been issues with full unsigned 32 bit color models in Java2D, which may cause trouble. How do you convert the images to 8 bps? 

To help you further I need a sample file and the minimal sample code that reproduces the problem.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2017-03-01 10:32
Closing for now. Feel free to reopen, when you can provide a sample file that exposes the problem (and the problem wasn't related to JPEG writing).

If you have problems attaching PSDs, create a ZIP archive and attach, or upload to Dropbox/Google drive or similar and share a link.

-- 
Harald K

**Closed by haraldk** 2017-03-01 10:32 UTC
Labels: Trouble-shooting
