### ISSUE TITLE
IndexOutOfBoundsException in reader.readRaster(0, null)

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#107] opened 2015-03-05 19:58 UTC
I get this with the attached (broken) file:

    java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	  at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	  at java.util.ArrayList.get(ArrayList.java:411)
	  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.fetchSegment(Unknown Source)
	  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.repositionAsNecessary(Unknown Source)
	  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.read(Unknown Source)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInputData(JPEGImageReader.java:307)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:604)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:342)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:476)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:597)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1054)
	  at com.sun.imageio.plugins.jpeg.JPEGImageReader.readRaster(JPEGImageReader.java:1453)
	  at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.readRaster(Unknown Source)

my wish (as usual): an IIOException instead :-)

![dct-1425584807450](https://cloud.githubusercontent.com/assets/6665575/6513311/59842196-c37a-11e4-965a-d92af587a8dd.jpg)

**Comment by haraldk** [comment] 2015-03-06 07:35
I agree! :-)

However, when trying to read this image, using the latest 3.1-SNAPSHOT, I don't get the same exception (I get an EOFException):

java.io.EOFException
	at javax.imageio.stream.ImageInputStreamImpl.readUnsignedByte(ImageInputStreamImpl.java:222)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.fetchSegment(JPEGSegmentImageInputStream.java:94)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.repositionAsNecessary(JPEGSegmentImageInputStream.java:230)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.read(JPEGSegmentImageInputStream.java:258)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInputData(JPEGImageReader.java:307)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readImageHeader(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readNativeHeader(JPEGImageReader.java:604)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.checkTablesOnly(JPEGImageReader.java:342)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.gotoImage(JPEGImageReader.java:476)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.readHeader(JPEGImageReader.java:597)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageTypesOnThread(JPEGImageReader.java:778)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageTypes(JPEGImageReader.java:768)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageTypes(JPEGImageReader.java:215)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.main(JPEGImageReader.java:1418)

-- 
Harald K

**Comment by haraldk** [comment] 2015-03-06 08:09
BTW: Are you generating these broken samples, or are they actually produced by "real" software? I'm asking mostly out of curiosity. ;-)

**Comment by THausherr** [comment] 2015-03-06 17:08
No, I am not generating these broken samples myself, that would be nasty, heh heh :-) These come embedded in PDF files from the digitalcorpora website (http://digitalcorpora.org/corp/nps/files/govdocs1/zipfiles/) and from JPEG files from http://digitalcorpora.org/corp/nps/files/govdocs1/by_type/jpg.zip. The files were grabbed from publicly available government websites. A few of the files are malformed, some are really broken, e.g. because they were uploaded in ascii mode to the original government website.

We got this strategy from the Apache TIKA project, which uses PDFBox. It is mentioned on https://issues.apache.org/jira/browse/TIKA-1302 but I believe the idea is older.

I'll do more tests and submit the file as a ZIP.

**Comment by THausherr** [comment] 2015-03-06 18:24
I can't attach .zip files in this issue, I have uploaded it here:
http://home.snafu.de/tilman/tmp/DCT-1425665944560.zip

**Comment by haraldk** [comment] 2015-03-06 19:03
Okay, makes sense. I was wondering because I noticed most nulls (`0x00`) had been replaced by `0x20` (or ASCII space). Probably the FTP ASCII mode transfer then. I did a binary search/replace and got back a readable image of a brain (or brain activity).. ;-)

Anyway, I still can't reproduce the `IndexOutOfBoundsException` above, unless it's in one of the files in the ZIP. I'll try during the weekend if I find the time, otherwise on Monday.


PS: The GitHub issue-tracker is kind of lame in that way, you can't attach anything but images. However you can fool it by renaming the file to `xxx.rename-me-back-to.zip.png`... ;-)

-- 
Harald K

**Comment by THausherr** [comment] 2015-03-07 11:31
Hmm, I do indeed get an EOF exception when I test it outside of the preflight mass test application.

**Comment by THausherr** [comment] 2015-03-07 11:46
Now I can reproduce it. It happens if I try to get the meta data first. I will now try to find the "minimal" code that produces the problem.

**Comment by haraldk** [comment] 2015-03-07 11:48
Okay. Makes sense. I think maybe it's fixed as part of the 109 issue, would you please do a pull & rebuild and test on that? :-)

-- 
Harald K

**Comment by THausherr** [comment] 2015-03-07 11:53
No, I was already using the latest version. Here's the code:

        ImageReader reader = ImageIO.getImageReadersByFormatName("jpeg").next();
        ImageInputStream iis = ImageIO.createImageInputStream(new File(....));
        
        reader.setInput(iis);
        try
        {
            reader.getImageMetadata(0);
        }
        catch (IOException e)
        {
            e.printStackTrace();
            System.out.println("error getting metadata");
        }
        reader.readRaster(0, null);

What happens is that there is an EOF getting metadata. I suspect you're not recovering from that, and the out of bounds exception is a follow up because something is "poinsoned" by that eof.

**Comment by haraldk** [comment] 2015-03-07 12:22
Thanks for looking into this! 

I'll put this into a test case, and hopefully push a fix soon.

-- 
Harald K

**Comment by haraldk** [comment] 2015-03-07 20:43
You were spot on, the EOFException left the JPEGSegmentImageInputStream in a bad state. :-)

Fixed in 2b2dd2fb40bf6422e30f8a855882d3a359e6fbb7.

-- 
Harald K

**Closed by haraldk** 2015-03-07 20:43 UTC
Labels: Trouble-shooting

**Comment by haraldk** [comment] 2015-03-09 11:59
Wasn't really happy about the fix for this, as I couldn't reproduce the bug at stream level (and the problem had to be at the stream level). After some debugging last night, I was finally able to recreate a test case, which resulted in a slightly more robust fix. It should not affect behaviour much if you used to do `catch (IOException)`. The main difference is that you will now get an `IIOException` thrown from the `JPEGMetadata` class, rather than an `EOFException` from the `JPEGSegmentImageInputStream`, if an image contains bad segment lengths.

Pushed in 032b2d9601f4b77de644364c4f73e43e07cb643d.


-- 
Harald K

**Comment by haraldk** [comment] 2015-03-10 11:54
PS: Created a tool to test all the files in the digitalcorpora.org ZIP file.

With a couple more fixes, I now have: 

    Processed: 109233 files (109006 ok/227 bad)

Of the bad, there's only one exception that is not an IOException. :-)
Expect a few more fixes coming soon...

Many thanks for the link!

-- 
Harald K
