### ISSUE TITLE
java.awt.color.CMMException: Invalid image format in createColorSpace

### ISSUE THREAD

**Issue by kulpreetsaluja** [haraldk/TwelveMonkeys#356] opened 2017-06-21 09:17 UTC
Env. - Jdk1.7_80, Windows 7 Enterprise
Library version - 3.3.2

I am reading a profile from a file and creating a color space but it fails with below exception

```
Exception in thread "main" java.awt.color.CMMException: Invalid image format
	at sun.java2d.cmm.kcms.CMM.checkStatus(Unknown Source)
	at sun.java2d.cmm.kcms.CMM.createTransform(Unknown Source)
	at java.awt.color.ICC_ColorSpace.fromRGB(Unknown Source)
	at com.twelvemonkeys.imageio.color.ColorSpaces.getCachedOrCreateCS(ColorSpaces.java:168)
	at com.twelvemonkeys.imageio.color.ColorSpaces.createColorSpace(ColorSpaces.java:134)

```
Code : 

```java
File profileFile = new File( "D:\\FilePath\\ICCProfile.icc" );
    byte[] array = Files.readAllBytes( profileFile.toPath() );
      ICC_Profile profile = ICC_Profile.getInstance( array );
      ICC_ColorSpace cs = ColorSpaces.createColorSpace( profile );
```

It creates color space in java 8 but fails in java 7.
ICC profile does have a rendering intent as "Relative Colorimetric", i tried to change to perceptual as well but that did not resolve the issue.

```java
private static void intToBigEndian( int value, byte[] array, int index ) {
    array[index] = (byte)( value >> 24 );
    array[index + 1] = (byte)( value >> 16 );
    array[index + 2] = (byte)( value >> 8 );
    array[index + 3] = (byte)( value );
  }
```

Values passed - intToBigEndian( 0, array, ICC_Profile.icHdrRenderingIntent );

I am not able to upload the ICC profile here.

**Comment by haraldk** [comment] 2017-06-21 09:59
Hi,

Thanks for reporting! However, without the ICC profile in question, I won't be able to help much. The exception message is very generic and basically says there's something wrong with the profile.

I do have a class that does some ICC profile "first-aid" for known issues, that might be extended for this case.  But I will need the profile for further investigation.

Are you unable to share the file due to legal constraints, or just not able to upload it to the issue tracker? If the latter is the problem, I think you can upload it as a ZIP file, or even just rename it to *.png. Alternatively, link it from your dropbox or other file sharing service.


Best regards,

-- 
Harald K

**Comment by kulpreetsaluja** [comment] 2017-06-21 10:13
I am not able to upload the zip as well. Uploaded it in google drive
https://drive.google.com/file/d/0BzftvJ6Q9wqnZkk0VXBxenhnQlE/view?usp=sharing

**Comment by haraldk** [comment] 2017-06-21 10:58
Excellent! 

I'll look into this, just need a system with multiple JRE's set up.

-- 
Harald K

**Comment by haraldk** [comment] 2017-06-23 08:20
Hi,

Did some digging into this, and so far this seems to be a limitation of the Java 7 default CMS implementation (KCMS). I can reproduce the same error on Java 8 too, by specifying ` -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider` on the command line.

Java 8 uses LittleCMS (LCMS) by default, which seems to be more lenient/compatible. 

I'll see if there's anything I can do to "fix" the profile on the fly, but I'm not sure how much energy we should spend on making this work, now that Java 7 is already in end-of-life, and Java 9 is due to be released in about a month...

-- 
Harald K

**Comment by kulpreetsaluja** [comment] 2017-06-23 09:41
Hi Harald,

Thanks for looking into it. It would be very helpful if we can find a fix for this or if we know which tag or header from the profile is causing the problem that would also help. I can't change my project version to java 8.
Can we not use LCMs with java 7?

**Comment by haraldk** [comment] 2017-06-23 10:01
I don't have Java 7 on my work machine, but try:

    -Dsun.java2d.cmm=sun.java2d.cmm.lcms.LcmsServiceProvider

Or perhaps:

    -Dsun.java2d.cmm=sun.java2d.cmm.lcms.LCMS

(the setting has changed for each version of Java...)

-- 
Harald K

**Comment by kulpreetsaluja** [comment] 2017-06-23 11:07
It's not working with either. Getting same error.

**Comment by haraldk** [comment] 2017-06-23 12:52
Well, then you are either not using the right command line, or LCMS isn't supported in your JRE. 

-- 
Harald K

**Comment by kulpreetsaluja** [comment] 2017-06-23 13:49
SystemUtil.isClassAvailable("sun.java2d.cmm.lcms.LCMS") this returns false so I guess it's jre which is not supporting :(

**Comment by haraldk** [comment] 2017-11-06 15:48
Hi,

I finally had some time to get to the bottom of this, and unfortunately, the profile in question is a ICC V4.3 profile, and these are not supported in KCMS. You need to use LCMS and Java 8 or later, if you want to use this profile. There isn't something I can reasonably do to make it work (other than perhaps use a completely different profile altogether).

-- 
Harald K

**Closed by haraldk** 2017-11-06 15:48 UTC
Labels: Trouble-shooting
