### ISSUE TITLE
Unexpected End of PackBits Stream for some TIFF files

### ISSUE THREAD

**Issue by annacc-everlaw** [haraldk/TwelveMonkeys#489] opened 2019-07-10 19:46 UTC
Hiya. For some TIFF files that I've attempted to read using your library, I run into the following exception:

```
java.io.EOFException: Unexpected end of PackBits stream
	at com.twelvemonkeys.io.enc.PackBitsDecoder.readFully(PackBitsDecoder.java:202)
	at com.twelvemonkeys.io.enc.PackBitsDecoder.decode(PackBitsDecoder.java:158)
	at com.twelvemonkeys.io.enc.DecoderStream.fill(DecoderStream.java:180)
	at com.twelvemonkeys.io.enc.DecoderStream.read(DecoderStream.java:124)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:425)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:398)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1863)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1102)
	at javax.imageio.ImageReader.read(ImageReader.java:939)
```
I've attached one of the files that caused this error in the following ZIP, because for whatever reason GitHub won't allow me to attach the TIFF directly:

[TIFF Error.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/3379081/TIFF.Error.tif.zip)

If you need any extra information from me, I am happy to provide it.

Thanks!

**Comment by haraldk** [comment] 2019-07-10 20:16
Thanks for reporting!

I’ll look into it as soon as I’m back in the office. 😀 


Best regards,

-- 
Harald K

**Comment by annacc-everlaw** [comment] 2019-08-05 17:42
@haraldk Hey! Sorry to bother, just wondering what the status of this is?

Thanks!

**Comment by haraldk** [comment] 2019-08-06 07:44
Hi, 

No worries. I just came back to work yesterday, and will look at the issue some time this week. Hopefully today. 

-- 
Harald K

**Comment by haraldk** [comment] 2019-08-06 08:24
Okay,

Had a quick look and it seems the problem is a combination of the software ("IMAGE MAKER: Spittin' Image Software Inc.  V1.0") writing the TIFF not ending the PackBits stream correctly or not writing the correct `StripByteCounts` value, and my PackBits decoder trying to be a little too smart by reading ahead to decode faster.

I can probably fix this in my PackBits decoder, so that it no longer does this read-ahead.

-- 
Harald K

**Comment by annacc-everlaw** [comment] 2019-08-06 17:43
Yeah, I'm not super well versed in the TIFF format, but I guessed that it had something to do with the ancient software that made it.

Thank you for looking into it! Very helpful.

**Comment by haraldk** [comment] 2019-08-07 14:57
I pushed a fix for this issue now.

-- 
Harald K

**Closed** 2019-08-07 14:56 UTC
Labels: Bug

**Comment by annacc-everlaw** [comment] 2019-08-07 17:24
Amazing! Thank you so much!
