### ISSUE TITLE
Unable to dispose JPEG image reader

### ISSUE THREAD

**Issue by jprante** [haraldk/TwelveMonkeys#527] opened 2020-02-19 14:26 UTC
Calling `dispose()` on JPEGImageReader does not seem to work.

```
java.lang.IllegalStateException: Attempting to use reader after dispose()
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.resetReader(Native Method)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.resetInternalState(JPEGImageReader.java:1647)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.setInput(JPEGImageReader.java:291)
	at java.desktop/javax.imageio.ImageReader.reset(ImageReader.java:2494)
	at java.desktop/com.sun.imageio.plugins.jpeg.JPEGImageReader.reset(JPEGImageReader.java:1672)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.resetMembers(JPEGImageReader.java:152)
	at com.twelvemonkeys.imageio.ImageReaderBase.dispose(ImageReaderBase.java:122)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.dispose(JPEGImageReader.java:171)
```

**Comment by jprante** [comment] 2020-02-19 14:26
Twelvemonkeys Version 3.5

**Comment by haraldk** [comment] 2020-02-24 11:06
From the stack trace, it seems like you are invoking `dispose` on a reader for the second time (it's already disposed). At least I cannot reproduce your stack trace in any other way, and my test cases already invoke `dispose()` in most if not all tests.

Note that the API docs for `dispose()` states: 

> The result of calling any other method (other than `finalize`) subsequent to a call to this method is undefined.

If you think this is a real problem, please create a failing test case for the issue, and state what JDK/JRE (`java --version`) you use. Otherwise I'll close this as not a bug/not reproducible.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2020-04-15 13:43
Closing this for now. Feel free to re-open if you can provide a failing test case. 

-- 
Harald K

**Closed by haraldk** 2020-04-15 13:43 UTC
Labels: Trouble-shooting
