### ISSUE TITLE
Reading a multipage TIFF with JPEG compression can yield a ArrayNegativeSizeException

### ISSUE THREAD

**Issue by odrusso** [haraldk/TwelveMonkeys#525] opened 2020-02-12 06:15 UTC
When running the following code on a multi-page TIFF (attached) (in Kotlin)
```
import java.awt.image.BufferedImage
import javax.imageio.ImageIO

val inputBytes = File(*path to image*).readBytes()

val imageStream = ImageIO.createImageInputStream(inputBytes.inputStream())
reader.input = imageStream
val numPages = reader.getNumImages(true)
val listOfImages = (0 until numPages).map { reader.read(it) }.toList()
```

Throws the following error:

```
java.lang.NegativeArraySizeException: -19548

	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1303)
	at java.desktop/javax.imageio.ImageReader.read(ImageReader.java:938)
        ...
```
With the following Gradle dependencies,
```
compile group: 'com.twelvemonkeys.imageio', name: 'imageio-pnm', version: '3.5'
compile group: 'com.twelvemonkeys.imageio', name: 'imageio-tiff', version: '3.5'
```

Notably - the ImageIO builtin TIFFImageReader does not exhibit the same behavior.

[662260-color.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/4190408/662260-color.tif.zip)

**Comment by odrusso** [comment] 2020-02-12 08:49
I've had a bit of a play-around in the relevant class to try and diagnose or fix the bug, but my knowledge of the tiff/jpeg data structure (and Java) is far too limited and I'm afraid I won't be much help.

**Comment by haraldk** [comment] 2020-02-12 09:38
Hi Oscar,

Thanks for reporting! 

I'll look into your issue as soon as possible, but anything you can do to isolate the problem or reproduce in a test case will help a lot in resolving it. I will take a loot at your test cases and possibly add them to the test suite.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2020-04-14 20:22
Hi again,

Sorry for taking so long looking into this. But yes, this seems to be a bug, reading a JPEG segment length as a signed, rather than an unsigned number... Causing a possible negative array size.

I'll have a fix soon.

-- 
Harald K

**Comment by haraldk** [comment] 2020-04-15 11:30
Pushed a fix just now, will be part of the next release.

-- 
Harald K

**Closed by haraldk** 2020-04-15 11:30 UTC
Labels: Bug, Trouble-shooting

**Comment by philals** [comment] 2020-04-15 18:14
Thanks @haraldk Great stuff!
