### ISSUE TITLE
Caching in ColorSpaces may cause wrong ICC profile to be used in color conversion

### ISSUE THREAD

**Issue by igorrogov** [haraldk/TwelveMonkeys#386] opened 2017-10-27 09:18 UTC
Hi,

I noticed the following weird behavior. If I load the image 002.jpg (attached), it works fine. But if I first load another image 001.jpg (also attached) and then 002.jpg right after that, the color of the 002 image is slightly different and I can see the bytes are different now.

```
Test 1
getImageMd5( "002.jpg" ) = 32629496911f9addbc476ec8db564446

```

```
Test 2
getImageMd5( "001.jpg" ) = 6400d19bda78a9464651c07a2235aa9d
getImageMd5( "002.jpg" ) = 83ba95b3d6c5b8c4c063a824666735bd // same image, different MD5

```

Sample source code and images are attached.

Version: twelvemonkeys.imageio-jpeg 3.3.2 (also tried 3.3.1).

[JpegReaderTest.java.zip](https://github.com/haraldk/TwelveMonkeys/files/1421483/JpegReaderTest.java.zip)
[images.zip](https://github.com/haraldk/TwelveMonkeys/files/1421489/images.zip)

Thanks!

**Comment by haraldk** [comment] 2017-10-27 12:16
Curious...

When I run your program (on my local 3.4-SNAPSHOT branch), I get:

    File: 002.jpg = 32629496911f9addbc476ec8db564446
    File: 001.jpg = fa927f13c3da6d5d16e3acd210b9d511
    File: 002.jpg = 32629496911f9addbc476ec8db564446

...so I'm afraid I'm not able to reproduce it so far. I'll try some more later.

What platform, OS, Java version etc are you using?


-- 
Harald K

**Comment by haraldk** [comment] 2017-10-28 11:09
The above test was Windows/Java 8 using the latest master. 

I have now tried again on macOS, using Java  7, Java 8 and Java 9, combined with the 3.3.2 branch, the 3.3.1 branch and the current master, all producing the exact same result:

    File: 002.jpg = 32629496911f9addbc476ec8db564446
    File: 001.jpg = fa927f13c3da6d5d16e3acd210b9d511
    File: 002.jpg = 32629496911f9addbc476ec8db564446

Closing this as not reproducible, until I get further details.

-- 
Harald K

**Comment by haraldk** [comment] 2017-10-28 11:14
PS: Just out of curiosity I removed the KCMS system property and ran all the tests again. This time, the MD5s were different (except for Java 7, which uses KCMS by default) as expected, but were still consistent across all runs:

File: 002.jpg = 26df2e87201d0f8bf3b7cf3bdfbe1250
File: 001.jpg = d1dc3ffb0d89f188487820fb8a42abea
File: 002.jpg = 26df2e87201d0f8bf3b7cf3bdfbe1250

-- 
Harald K

**Comment by igorrogov** [comment] 2017-10-30 01:24
Hi Harald,

Thanks for looking into that!
I'm using Windows 10 and Java 1.8.0_151 (64 bit).

If I run 002, 001, 002 I get the same MD5s as you. But did you try to run 001 then 002 exactly in this order? Please see my output below.

Test 1
```
File: 002.jpg = 32629496911f9addbc476ec8db564446
File: 001.jpg = fa927f13c3da6d5d16e3acd210b9d511
File: 002.jpg = 32629496911f9addbc476ec8db564446
```

Test 2
```
File: 001.jpg = 6400d19bda78a9464651c07a2235aa9d
File: 002.jpg = 83ba95b3d6c5b8c4c063a824666735bd (md5 has changed now)
```

Thanks!

**Comment by igorrogov** [comment] 2017-10-30 01:37
Additionally if I disable the twelvemonkeys plugin, it starts to work fine:

```
ImageReaderSpi jpegSpi = IIORegistry.getDefaultInstance().getServiceProviderByClass(com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReaderSpi.class);
IIORegistry.getDefaultInstance().deregisterServiceProvider(jpegSpi);
````

Test 1
```
Using JPEG reader: class com.sun.imageio.plugins.jpeg.JPEGImageReader

File: 002.jpg = 32629496911f9addbc476ec8db564446
File: 001.jpg = 6400d19bda78a9464651c07a2235aa9d
File: 002.jpg = 32629496911f9addbc476ec8db564446
```

Test 2
```
Using JPEG reader: class com.sun.imageio.plugins.jpeg.JPEGImageReader

File: 001.jpg = 6400d19bda78a9464651c07a2235aa9d
File: 002.jpg = 32629496911f9addbc476ec8db564446 (same MD5)
```

So it seems to be related to the twelvemonkeys plugin.

I hope this helps, thanks!

**Comment by haraldk** [comment] 2017-10-30 09:12
Thanks for being persistent and clearing that up! :-)

Yes, I see that there's a problem. It's actually in the `ColorSpaces` class, that caches ICC color profiles/ColorSpaces. Your JPEGs contains different ICC profiles (one "Adobe RGB 1998", and one"ColorMacth RGB"), that somehow have equal profile signatures... Because of this, the first profile is cached and use for both images, even if they are not the same.

I need to read up on the ICC color profile spec to figure out if this is supposed to be allowed, but in any case we need to handle it somehow, to avoid this unpredictable behavior. 

I'll look into it!

-- 
Harald K

**Comment by haraldk** [comment] 2017-11-05 10:46
Fixed now, in latest master.

-- 
Harald K

**Closed by haraldk** 2017-11-05 10:46 UTC
Labels: Bug, Trouble-shooting
