### ISSUE TITLE
Problem with T.4 group 3 fax TIFFs

### ISSUE THREAD

**Issue by JaxCoder** [haraldk/TwelveMonkeys#535] opened 2020-03-23 14:57 UTC
I have a bunch of mulitpage TIFF files taken from a healthcare system and when I try to display them, they are pure white. I've attempted to research TIFF compression and debug and tried making some changes, but alas, I have been unsuccessful thus far. 

the tiffinfo -d command shows a premature EOL,  and I believe this might be the issue in reading it, however - I know these TIFF files are not corrupt (at least not in the sense they are unreadable) because Snowbound java library reads them and .net framework's tiff decoder reads them as well.

Unfortunately I can't upload a TIFF here because it contains personal health information. I'll include as much info as I can, and i'll continue looking for a TIFF that is safe to upload, but im hoping someone will know why these TIFFs aren't working and maybe have an idea how to fix.

@Schmidor  it looks like you created the original G3/4 decoder, not sure if you have time to look into this.

I've included just the IFD0 info for brevity.

**TIFFINFO -D**
TIFFReadDirectory: Warning, Unknown field with tag 293 (0x125) encountered.
TIFF Directory at offset 0x8 (8)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 1700 Image Length: 2200
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 1
  Compression Scheme: CCITT Group 3
  Photometric Interpretation: min-is-white
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 32
  Planar Configuration: single image plane
  Page Number: 0-0
  Group 3 Options: EOL padding (4 = 0x4)
Fax3Decode1D: Warning, Premature EOL at line 0 of strip 0 (got 0, expected 1700).

**TIFFDUMP**
Magic: 0x4949 <little-endian> Version: 0x2a <ClassicTIFF>
Directory 0: offset 8 (0x8) next 67710 (0x1087e)
SubFileType (254) LONG (4) 1<2>
ImageWidth (256) LONG (4) 1<1700>
ImageLength (257) LONG (4) 1<2200>
BitsPerSample (258) SHORT (3) 1<1>
Compression (259) SHORT (3) 1<3>
Photometric (262) SHORT (3) 1<0>
FillOrder (266) SHORT (3) 1<1>
StripOffsets (273) LONG (4) 69<810 1368 1774 2228 4184 5188 7376 9462 11048 12136 12900 13580 15070 16464 17798 18670 19600 20422 20912 21414 21960 22552 23154 23700 ...>
Orientation (274) SHORT (3) 1<1>
SamplesPerPixel (277) SHORT (3) 1<1>
RowsPerStrip (278) LONG (4) 1<32>
StripByteCounts (279) LONG (4) 69<558 406 454 1956 1004 2188 2086 1586 1088 764 680 1490 1394 1334 872 930 822 490 502 546 592 602 546 626 ...>
XResolution (282) RATIONAL (5) 1<200>
YResolution (283) RATIONAL (5) 1<200>
PlanarConfig (284) SHORT (3) 1<1>
Group3Options (292) LONG (4) 1<4>
Group4Options (293) LONG (4) 1<0>
ResolutionUnit (296) SHORT (3) 1<2>
PageNumber (297) SHORT (3) 2<0 0>

**Comment by Schmidor** [comment] 2020-03-23 15:22
You could try creating a test case with an single bytestrip, which is causing this issue.
1-3 lines of pixels should probably be enough to look into this issue :)
https://github.com/haraldk/TwelveMonkeys/blob/a1047edddb3db0c116075e63b89c842d79b41a19/imageio/imageio-tiff/src/test/java/com/twelvemonkeys/imageio/plugins/tiff/CCITTFaxDecoderStreamTest.java#L163

**Comment by JaxCoder** [comment] 2020-03-23 17:33
i could fill in the first strip, which is 558 bytes, but making it a legit test with a bitmap to assert against may be difficult.

**Comment by haraldk** [comment] 2020-03-24 13:06
@JaxCoder As you say Snowbound and .net TIFF decoder can decode the TIFFs, just writing a single line image from those packages should be fairly easy? 

While we'd love to look into and hopefully fix this issue, it's crucial that we get test data and matching correct data to reproduce the problem and verify a potential fix .

-- 
Harald K

**Comment by JaxCoder** [comment] 2020-03-24 14:59
@haraldk @Schmidor 
Thanks for your input! I definitely understand your need for good test data. I have a feeling that outputting a TIFF from either of the other libraries will output a TIFF that ImageIO can read with no issue, as ImageIO from my understanding already supports T.4 group3 fax/bilevel TIFFs. But I will definitely give it a shot. 

Meanwhile, if its of any use - I have stripped a strip from one of my "bad" TIFFs and put it in the the test class. For right now, I simply have it asserting that the entire array is NOT filled with 0's. It fails appropriately, but obviously that assertion isn't "proper", but a starting point.

if you care to take a look: [check my branch ISSUE-535 on my fork](https://github.com/JaxCoder/TwelveMonkeys/blob/issue-535/imageio/imageio-tiff/src/test/java/com/twelvemonkeys/imageio/plugins/tiff/CCITTFaxDecoderStreamTest.java)

otherwise, I'll let you know if there's any luck reproducing a similar TIFF with one of the libraries. (not sure the limitations of writing TIFFs with the eval license of snowbound)

**Comment by Schmidor** [comment] 2020-03-30 22:34
I've looked into the data stream. This doesn't look like Group3 1D data, but more like raw 1D data which correspondents to TIFFBaseline.COMPRESSION_CCITT_MODIFIED_HUFFMAN_RLE. You could try if chaning the compression from "3" to "2" works.

The first five bytes equal to this bit sequence, i've put pipes where the Huffman-Codes end:
0011 0101 | 0000 0010 1011 | 0110 0111 | 0010 1001 | 0100
Those are "0 white, 59 black, 640 non terminating white, 40 white" and four bits of the next code.

Group 3 1D starts each line with an EOL code (000000000001, might be more leading zeros if byte aligned). This stream seems to contain no EOL codes, at least not at the start.

**Comment by Schmidor** [comment] 2020-04-01 12:37
As we're currently switching from ICEpdf to ApachePDF Box im looking back into how I've integrated our decoder there.

There were some PDFs which had the same problem, where I did a workaround to switch to from T4 to RLE, if no EOL is found within the first 20 bytes. It might be worthwhile to integrate that directly into the decoder:
```
if (streamData[0] != 0 || (streamData[1] >> 4 != 1 && streamData[1] != 1)) {
  // leading EOL (0b000000000001) not found, search further and try RLE if not
  // found
  type = TIFFExtension.COMPRESSION_CCITT_MODIFIED_HUFFMAN_RLE;
  short b = (short) (((streamData[0] << 8) + streamData[1]) >> 4);
  for (int i = 12; i < 160; i++) {
     b = (short) ((b << 1) + ((streamData[(i / 8)] >> (7 - (i % 8))) & 0x01));
     if ((b & 0xFFF) == 1) {
       type = TIFFExtension.COMPRESSION_CCITT_T4;
       break;
     }
   }
}
```

**Comment by JaxCoder** [comment] 2020-04-07 13:01
> You could try if chaning the compression from "3" to "2" works.

I tried this, I simply get "Unknown code in Huffman RLE stream" exception when trying to decode the full image. When I try to decode just the byte sequence I added to my fork, I get an image, but not the correct one.

MS Paint JPG Conversion
![MS Paint JPG conversion](https://user-images.githubusercontent.com/53888386/78672095-2c3c1880-78ae-11ea-987e-c35112463bc8.jpg)

Decoder Output
![Decoder output](https://user-images.githubusercontent.com/53888386/78671710-a61fd200-78ad-11ea-9653-1b08ff7b77c9.jpg)

**Comment by JaxCoder** [comment] 2020-04-07 13:11
@Schmidor  
> The first five bytes equal to this bit sequence, i've put pipes where the Huffman-Codes end:
> 0011 0101 | 0000 0010 1011 | 0110 0111 | 0010 1001 | 0100
> Those are "0 white, 59 black, 640 non terminating white, 40 white" and four bits of the next code.

if i count the pixels in the original image, the first row of pixels has 59 black, followed by 680 white (640 + 40). so it looks like you're correct here, but the decoder is not outputting that, as you can see in my included images.

**Comment by Schmidor** [comment] 2020-04-07 14:31
@JaxCoder Can you try building from this branch? I've included the automatic switch from my comment. 
https://github.com/Schmidor/TwelveMonkeys/tree/issue-535
FillOrder 1 should be correct according to your sample.

**Comment by JaxCoder** [comment] 2020-04-07 19:28
@Schmidor 
I didn't debug through yet to understand why your change works, but testing it with one of my TIFFs, it definitely worked! 

Definitely want to look into what its doing since changing the compression type via the debugger did not work for me, so i'd like to understand the difference. 

Thanks so much for this! I hope it will get added into the next version of ImageIO.

**Comment by haraldk** [comment] 2020-04-16 10:10
@Schmidor I looked into our proposed fix in [issue-535](https://github.com/Schmidor/TwelveMonkeys/tree/issue-535), and reworked it slightly to invoke the compression type test from the `TIFFImageReader` (the actual code to test is still in the `CCITTDecoderStream` as a static method), in order to issue a warning if we change compression type. 

Before I do this, I just like to ask if there is any specific reason to include this in the stream constructor, that I'm forgetting? The only difference now is that detecting the incorrect compression will be left to client code, but I don't think anyone uses the class outside the `TIFFImageReader`...

PS: Moving the type change outside, also changes the byte align flag, as I then invoke the constructor with the RLE compression instead of T4. Is that a good or bad thing? 😀

-- 
Harald K

**Comment by Schmidor** [comment] 2020-04-16 11:15
@haraldk To be honest, without an full test file I'm not sure. But if it worked in @JaxCoder's test there are probably no fillbits, as without an EOL to catch those it probably makes a difference.

From my experiences with ICEpdf and Apache PDFbox im suspecting some PDF writers to write the compression wrong, and later on maybe some simple PDF to TIFF CCITT extractors in this case.
I've done the fix  I proposed here from inside the stream on ICEpdf from the caller and proposed the same to PDFbox. I'm pretty sure that was why Tilman Hausherr modified our code when he integrated it. But PDF Readers set the byte align flag explicitly.

**Comment by haraldk** [comment] 2020-04-17 10:53
Okay... 

I have now re-created a full TIFF sample from @JaxCoder's data. Not sure if it is *exactly* as it should, but at least the reader can read it, and it looks like in the sample above... 😉

Yes, the byte align flag makes a difference. It must be kept to false, unfortunately. So I needed some more changes. I guess there's really no good way to detect if this flag from the data... 

I do see that the original sample data actually contains *both* G3/T.4 and G4/T.6 options, and the T.4 options do have fill bits set to 1... However, it's hard to tell which part of the information you can trust/use for anything, when there are inconsistencies in the tags.

[incorrect-compression.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/4492386/incorrect-compression.tif.zip)


-- 
Harald K

**Comment by Schmidor** [comment] 2020-04-17 11:47
https://github.com/apache/pdfbox/blob/trunk/pdfbox/src/main/java/org/apache/pdfbox/filter/CCITTFaxDecoderStream.java
I believe he changed G3 1D to run on the RLE codes and just ignore EOLs.

**Comment by haraldk** [comment] 2020-06-16 20:03
Just pushed a fix for this (the reworked version of @Schmidor's fix, as mentioned above). 

Sorry about the delay! 

-- 
Harald K

**Closed** 2020-06-16 20:04 UTC
Labels: Trouble-shooting
