### ISSUE TITLE
Tif image read result in wrong colors

### ISSUE THREAD

**Issue by bosofelipe** [haraldk/TwelveMonkeys#434] opened 2018-08-09 11:23 UTC
I´m read tif images to transform in jpg files, but some tif files results in wrong colors, I don´t know what happens. What the problem or problem in my image cause this.

A print of the main image (tif format) : 

![error](https://user-images.githubusercontent.com/4993515/43895845-00d90264-9bad-11e8-9c38-9205bbe1e11e.png)

Converted File

![error_converted](https://user-images.githubusercontent.com/4993515/43895851-068d1dd0-9bad-11e8-940a-fd13769a234d.png)

My code to read the file :

```
package com.hadoocken;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Iterator;

import javax.imageio.ImageIO;
import javax.imageio.ImageReadParam;
import javax.imageio.ImageReader;
import javax.imageio.stream.ImageInputStream;

import org.apache.commons.codec.binary.Base64;

import net.coobird.thumbnailator.Thumbnails;

public class TifTest {
	
	public static void main(String[] args) throws IOException {
		convertTiffToPng("cleaned_ERROR.tif");
	}
	
	public static void convertTiffToPng(String filename) throws IOException {
		File file = new File(filename);
		byte[] bytes = loadFile(file);
		byte[] encoded = Base64.encodeBase64(bytes);
		String encodedString = new String(encoded, StandardCharsets.US_ASCII);

		byte[] decoded = java.util.Base64.getDecoder().decode(encodedString);

		ImageInputStream input = ImageIO.createImageInputStream(new ByteArrayInputStream(decoded));

		try {
			Iterator<ImageReader> readers = ImageIO.getImageReaders(input);

			if (!readers.hasNext()) {
				throw new IllegalArgumentException("No reader for: " + file);
			}

			ImageReader reader = readers.next();

			try {
				reader.setInput(input);

				ImageReadParam param = reader.getDefaultReadParam();

				BufferedImage image = reader.read(0, param);

				image = setImageBackgroundToWhite(image);
				Thumbnails.of(image).size(1200, 1200).outputQuality(0.9D).keepAspectRatio(true)
						.imageType(BufferedImage.TYPE_INT_ARGB).outputFormat("jpg").toFile(new File("Convertidos/test" + System.currentTimeMillis()));
			} finally {
				reader.dispose();
			}
		} finally {
			input.close();
		}
	}

	private static BufferedImage setImageBackgroundToWhite(BufferedImage imBuff) {
		int width = imBuff.getWidth();
		int height = imBuff.getHeight();

		BufferedImage newImage = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

		Graphics2D g = newImage.createGraphics();
		g.setColor(Color.WHITE);
		g.fillRect(0, 0, width, height);
		g.drawRenderedImage(imBuff, null);
		g.dispose();

		return newImage;
	}

	private static byte[] loadFile(File file) throws IOException {
		InputStream is = new FileInputStream(file);

		long length = file.length();
		byte[] bytes = new byte[(int) length];

		int offset = 0;
		int numRead = 0;
		while (offset < bytes.length && (numRead = is.read(bytes, offset, bytes.length - offset)) >= 0) {
			offset += numRead;
		}

		if (offset < bytes.length) {
			throw new IOException("Could not completely read file " + file.getName());
		}

		is.close();
		return bytes;
	}
}

```

Anybody can help me?

**Comment by haraldk** [comment] 2018-08-09 13:00
Hi Felipe,

**What version of the library are you using? And also, I need the original TIFF, to verify the issue.**

From looking at the code, there are some minor issues I like to point out:

* You convert the file contents to Base64 and back again (for no apparent reason)
* You read the entire file into a byte array, instead you could create an `ImageInputStream` directly from the `File`
* After decoding the image, you convert it to RGB with white background, but then use `BufferedImage.TYPE_INT_ARGB` which isn't generally good for JPEG (most software will misinterpret it as  CMYK instead of RGBA). Did you try to write out the image directly, without creating thumbnails?

Other than that, it should work. My guess is that you are using an old version of the library, and that the TIFF contains multiple extra samples, which isn't correctly implemented in that version. :-)


Best regards,

-- 
Harald K

**Comment by bosofelipe** [comment] 2018-08-09 13:28
@haraldk thanks for your response
I change the version 3.2.1 for the newest 3.3.2, and remove conversion for base64 and use file directly, but did not work yet :/
Setting background color or just read the image. Do you see my project? Running TifReader.java and looking for some error?

my project ziped...

[tiff-reader.zip](https://github.com/haraldk/TwelveMonkeys/files/2274330/tiff-reader.zip)

Waiting anxiously for your new response!

thanks!

**Comment by bosofelipe** [comment] 2018-08-09 13:58
@haraldk The image has an alpha channel layer...

**Comment by haraldk** [comment] 2018-08-09 14:08
Actually, your TIFF has 6 channels, the normal RGB + 1 alpha and 2 extra channels... 

This is not correctly supported in any of the currently available releases, unfortunately (I believe this is a duplicate of #317).  

To be able to read your TIFF, you need to build the current master (3.4) or wait for the 3.4 release. Any day now, but I've said that for a while, so don't hold your breath... ;-)

-- 
Harald K

**Closed by haraldk** 2018-08-09 14:08 UTC
Labels: Trouble-shooting

**Comment by bosofelipe** [comment] 2018-08-09 14:24
@haraldk thanks!

**Comment by bosofelipe** [comment] 2018-08-09 16:08
@haraldk  When the version 3.4 is stable and released?

**Comment by bosofelipe** [comment] 2018-08-09 21:18
@haraldk Is possible publish the version 3.4-SNAPSHOT in a maven central? This version works fine for me, but i need the jars in a repo for grails 2.5.5

Thanks again!!

**Comment by haraldk** [comment] 2018-08-10 11:37
It's possible to publish it to a local repository, but generally SNAPSHOT releases should not be on Maven Central. I don't know Grails, but I would expect it to work just by first running 

    $ mvn install

from the TwelveMonkeys project, to get a local install. If not, you could set up a local repository on the file system, or (preferably, if in a larger project) a centralized Nexus or similar repository manager. 

I'll try to release the 3.4 as soon as possible though!

-- 
Harald K

**Comment by bosofelipe** [comment] 2018-08-10 16:31
@haraldk very nice!

I use 

`mvn package`

get the tiff jars and put in lib folder in grails application.

Works fine!

Thank´s again!
