### ISSUE TITLE
javax.imageio.metadata.IIOInvalidTreeException: Invalid DHT node

### ISSUE THREAD

**Issue by saibotma** [haraldk/TwelveMonkeys#559] opened 2020-09-07 11:35 UTC
```
javax.imageio.metadata.IIOInvalidTreeException: Invalid DHT node
	at com.sun.imageio.plugins.jpeg.DHTMarkerSegment.<init>(DHTMarkerSegment.java:87) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromMarkerSequenceNode(JPEGMetadata.java:2223) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromNativeTree(JPEGMetadata.java:2208) ~[?:1.8.0_212]
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.setFromTree(JPEGMetadata.java:2168) ~[?:1.8.0_212]
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:168)
```

Unfortunately I was not able to reproduce this issue as I got this from a customer. Will update this thread in case I get some new information.
I am using https://mvnrepository.com/artifact/com.twelvemonkeys.imageio/imageio-jpeg/3.6 and Java 1.8.0_212.

**Comment by haraldk** [comment] 2020-09-17 19:43
Hi Tobias,

Have you been able to reproduce this problem? I'm not able to do much about this, unless you can create a test case or small standalone program that shows this behaviour...

Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2020-10-12 13:55
Closing, as I can't reproduce. Feel free to reopen if you find a way to reproduce the problem.

-- 
Harald K

**Comment by aprantl** [comment] 2022-01-10 15:35
Hi @haraldk - I recently saw the same exceptions after having upgraded from 3.4.x to 3.8. The exception appears since 3.6.

Please checkout my reproducer with two test images:
https://github.com/aprantl/TwelveMonkeys/commit/5fdd20a4b1275bc340d87b14bc189fd2aaab354e
Please use other images if you plan to something similar to your test suite.

Can you please re-open this issue? We'd love to upgrade to the latest version once the issue is fixed.

**Comment by haraldk** [comment] 2022-01-10 19:22
I can reopen, but... 

Do you have any test images that I *can* use? Fixing this without a test case is just asking for regressions later.

I'm able to reproduce using your images, the problem seems to be the same in both of them. The first image has 6 DHT (Huffman) tables, the second 5. While the reader allows more DHT tables in a single node, the native metadata only allows 4 when creating from another node for some reason...

It's possible to fix the issue by splitting the DHT in multiple nodes it seems.

**Comment by aprantl** [comment] 2022-01-10 22:39
Thank you for the quick reply and analysis. Sure, there should be a test case. I am however afraid that I have no other image nor did I succeed in creating another one with more than four tables yet. I am not sure, but I assume you can take the second one with the beach club if there is no other way.

**Comment by haraldk** [comment] 2022-01-12 18:33
> Maybe another junit test for the corresponding metadata class would be good enough.

Absolutely! Turned out I had already fixed this problem, in a class that was no longer in use, and then re-introduced the bug when I created my own metadata class... 😛 

Good thing, I could reuse the test case!

**Comment by haraldk** [comment] 2022-01-12 18:34
Fixed in latest master.

**Closed by haraldk** 2022-01-12 18:34 UTC
Labels: Trouble-shooting

**Comment by aprantl** [comment] 2022-01-13 06:45
😎  Thank you @haraldk . Looking forward to testing the release.

**Comment by aprantl** [comment] 2022-02-14 08:47
Hi @haraldk. Sorry for bothering you with this. I just want to check so that I can plan accordingly. This issue is currently preventing me from upgrading in my application. Do you plan to build a release anytime soon? 

Thanks, Andreas

**Comment by haraldk** [comment] 2022-02-15 17:59
Hi Andreas,

With the current funding (ie. more or less nothing), I'm trying my best to make quarterly releases. Sometimes more, sometimes less. I would love to be able to provide timely, monthly bug fix releases, but I can't afford it at the moment. 

So, yes, soon. But can't promise any date.  

-- 
Harald K
