### ISSUE TITLE
A Microsoft Office DOC file is identified as a thumbs DB and fails:

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [haraldk/TwelveMonkeys#218] opened 2016-02-02 14:07 UTC
I have an older (Office 2003) Word document that, when I ask for a reader, I get the ThumbsDB reader and asking that for a width throws an exception:

`````
java.lang.ArrayIndexOutOfBoundsException: 87931
	at com.twelvemonkeys.io.ole2.CompoundDocument.getSIdChain(CompoundDocument.java:388)
	at com.twelvemonkeys.io.ole2.CompoundDocument.seekToSId(CompoundDocument.java:412)
	at com.twelvemonkeys.io.ole2.CompoundDocument.access$000(CompoundDocument.java:53)
	at com.twelvemonkeys.io.ole2.CompoundDocument$Stream.fillBuffer(CompoundDocument.java:679)
	at com.twelvemonkeys.io.ole2.CompoundDocument$Stream.read(CompoundDocument.java:664)
	at com.twelvemonkeys.io.AbstractCachedSeekableStream.read(AbstractCachedSeekableStream.java:50)
	at com.twelvemonkeys.io.MemoryCacheSeekableStream.read(MemoryCacheSeekableStream.java:45)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readShort(LittleEndianDataInputStream.java:153)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.Catalog$CatalogHeader.read(Catalog.java:181)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.Catalog.read(Catalog.java:85)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.Catalog.read(Catalog.java:71)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.initCatalog(ThumbsDBImageReader.java:296)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.init(ThumbsDBImageReader.java:272)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.init(ThumbsDBImageReader.java:219)
	at com.twelvemonkeys.imageio.plugins.thumbsdb.ThumbsDBImageReader.getWidth(ThumbsDBImageReader.java:309)
`````

The code that causes it is below. The last line of the blurb is the start of the exception:

`````java
    public BufferedImage getImage (final ImageInputStream iis, final Iterator<ImageReader> i)
        throws IOException
    {
        BufferedImage result = null;
        final ImageReader reader = i.next ();

        try
        {
            final ImageReadParam params = reader.getDefaultReadParam ();
            reader.setInput (iis, true, false);

            // Get the configuration
            final ConfigurationType configuration = (m_configuration == null ? null : m_configuration.getData ());
            final GeneralSettingsType general = (configuration == null ? null : configuration.getGeneral ());
            final int nSize = (general == null ? 1080 : general.getContentWidth ());

            // Get the scaled width and height we want to load
            final int nIndex = reader.getMinIndex ();
            final int nWidth = reader.getWidth (nIndex);
`````

But unfortunately, the document contains private content so I can't just send it along. The image reader iterator was formed using the file extension (doc):

`i = ImageIO.getImageReadersBySuffix (sExtension);`

**Comment by haraldk** [comment] 2016-02-03 09:01
Hi,

Are you saying that by using `ImageIO.getImageReadersBySuffiix("doc")`, you are getting an iterator containing the `ThumbsDBImageReader`?

I'm not able to reproduce this, using the code below (also the code makes sure it is only created for the suffix `"db"`).

`````java
public class DocTest {
    public static void main(String[] args) {
        Iterator<ImageReader> docReaders = ImageIO.getImageReadersBySuffix("doc");

        if (!docReaders.hasNext()) {
            System.err.println("No readers!");
        }
        else while (docReaders.hasNext()) {
            ImageReader reader = docReaders.next();
            System.out.println("reader: " + reader);
        }
    }
}
`````

On the other hand, if you get the `ThumbsDBImageReader` by using `ImageIO.getImageReaders(stream)`, this is possible. It's a known issue, because a `Thumbs.db` file is just an [OLE2 Compound Document](https://en.wikipedia.org/wiki/Compound_File_Binary_Format), which is a Microsoft container format, that just contains other files/streams. It is quite hard to distinguish a Thumbs.DB file from other such files (like DOC, XLS, etc), without parsing unreasonably large amounts of the file. So, instead, we'll just see if the file is parseable as an OLE Compound Doc, and end up reporting a few false positives.

Now, the reader *should not* throw an `ArrayIndexOutOfBoundsException` though. This is unfortunately not something that I can fix without having a sample file. I understand you can't share the file. But I would be thankful if you could produce a sample file with dummy content, reproducing the same issue.

To work around your problem, there are some options:

- If you don't need to read Thumbs.db, just remove the JAR altogether
- If you need to read Thumbs.db you can match on file name and create the reader yourself
  - If the service provider causes trouble you can unregister it, using the  `IIORegistry.deregisterServiceProvider(...)` method, comment out the lines or remove the file in `/META-INF/services/javax.imageio.spi.ImageReaderSpi`.


Regards,

-- 
Harald K

**Comment by haraldk** [comment] 2016-02-23 13:30
Closing for now.

Feel free to reopen if you have a sample file that exposes the issue to share.

-- 
Harald K

**Closed by haraldk** 2016-02-23 13:30 UTC
Labels: Trouble-shooting

**Comment by AlskiOnTheWeb** [comment] 2016-02-23 15:46
I'm using your work around to avoid it. I don't ever want to render the thumbs.db as it is.

Thanks!
