### ISSUE TITLE
Decode failed when convert a TIFF files  to pdf which is bit depth 8 and Compression as LZW

### ISSUE THREAD

**Issue by Yuhan668** [haraldk/TwelveMonkeys#618] opened 2021-08-13 08:35 UTC
**Describe the bug**
get java.io.IOException: java.util.concurrent.ExecutionException: com.twelvemonkeys.io.enc.DecodeException: Corrupted TIFF LZW: code 256 (table size: 258)" when convert a tiff to pdf.

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use.
3.4.2

2. The *exact* output of `java --version` (or `java -version` for older Java releases). 
java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

3. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.
When convert tiff to pdf, we get "java.io.IOException: java.util.concurrent.ExecutionException: com.twelvemonkeys.io.enc.DecodeException: Corrupted TIFF LZW: code 256 (table size: 258)" error.

**Comment by haraldk** [comment] 2021-08-13 12:51
Hi @Yuhan668,

Thanks for reporting! 

To look further into this issue, I do need the following information (from the template):

> **Example code**
> Preferably as a failing JUnit test, or a standalone program with a `main` method that showcases the problem. 
> 
> Less is more. Don't add your entire project, only the code required to reproduce the problem. 😀 
> 
> **Sample file(s)**
> Attach any sample files needed to reproduce the problem. Use a ZIP-file if the format is not directly supported by GitHub.
> 
> **Stak trace**
> Always include the stack trace you experience.
> 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2021-08-24 08:36
Haven't received any feedback on this, closing as not reproducible. 

-- 
Harald K

**Closed by haraldk** 2021-08-24 08:36 UTC
Labels: Reported bug

**Comment by Yuhan668** [comment] 2021-09-29 05:54
Hi
 
The sample code and sample file are ready now. Can we reopen this case?

**Comment by haraldk** [comment] 2021-09-29 08:38
Sure, just attach the necessary information mentioned above, and reopen when ready! 👍🏻 

-- 
Harald K

**Comment by Yuhan668** [comment] 2021-11-04 01:25
Hi Harald,

Because of GDPR, I can't upload sample file by myself. Customer met below issue when attach sample file. they zip the tiff file and upload the zip, then get below error. They also tried adding the tiff to Word document, also get same error. Can you let me know how to resolve this?
<img width="591" alt="uploadIssue" src="https://user-images.githubusercontent.com/88013371/140241537-fb973cd2-a15c-4481-b3df-7c63f080d9f8.png">

**Comment by haraldk** [comment] 2021-11-04 16:16
Note that if the image can't be shared due to GDPR regulations, *you should not* upload it here... This is issue tracker is open for all. Only attach images that may be shared publicly, as we might need to use them in unit or regression tests in the future. 

Uploading a zipped TIFF file have worked for other users before, I would try again. For issues with the GitHub infrastructure, please contact GitHub.

**Comment by Yuhan668** [comment] 2021-11-05 02:03
Do you have any other way to accept sample file? For example, by email? That maybe safer and easier for customer. This issue only can be reproduced with customer's file.

**Comment by haraldk** [comment] 2021-11-05 07:40
If you can't make GitHub accept your file upload, you can upload it to any file sharing service (eg. DropBox), make the file publicly available and create a link to the file from this issue. This way I can download the file and attach it to the issue.

But I repeat, please *do not send or upload files that you cannot legally share*.
