### ISSUE TITLE
Dull colors when rendering PSD files saved with Adobe RGB color profile

### ISSUE THREAD

**Issue by octavian-nita** [haraldk/TwelveMonkeys#92] opened 2015-01-31 15:31 UTC
Hello,

First off -- Wow! What an amazing job you're doing with the TwelveMonkeys imaging library! Thank you!

Having said that, I noticed that when I am trying to render `BufferedImage`s loaded from **PSD** (Adobe Photoshop) documents saved with the **Adobe RGB** *color profile*, I get quite dull colors. This doesn't happen when I open the same documents in programs that support the PSD format, other than Photoshop, e.g. GIMP on any platform or Mac's Preview app.

Below there are two screenshots that illustrate the difference in rendering colors.

Rendered using TwelveMonkeys:
![image](https://cloud.githubusercontent.com/assets/4410478/5988566/31b59808-a966-11e4-9545-744739fe2595.png)

Rendered in GIMP:
![image](https://cloud.githubusercontent.com/assets/4410478/5988573/5e5733c6-a966-11e4-91b3-9f45ed284ba7.png)

The test file can be found here: http://github.com/octavian-nita/thepholio-desktop/blob/master/src/main/resources/samples/home-away-from-home.psd .

**Comment by haraldk** [comment] 2015-02-02 09:16
Thanks for reporting and providing a sample file! 

The expected color conversion step between the embedded ICC profile and sRGB was missing. This is now added. Fixed in ecfcea98dfa5985bbb76ec14e164a3f86a06d8a7. 

Please note that the colors will look different between Java 6/7 and Java 8, due to a difference in color managment systems (CMS). Older versions of Java have always used Kodak's original KCMS for Java, while Java 8 uses LittleCMS. LittleCMS seems to do a better job and reproduces the colors I see in Preview, but is also quite a bit slower.

I'm planning to release 3.1 very soon, but in the mean time, feel free to pull and build your own version to verify that this fixes the problem. 


PS: Do you have a smaller sample file that I could use for a test case/regression test? :-)


Best regards,

-- 
Harald K

**Closed by haraldk** 2015-02-02 09:16 UTC
Labels: Bug

**Comment by octavian-nita** [comment] 2015-02-02 23:00
Thank you so so much -- I will do a test tomorrow.

In the meanwhile, here's another (smaller) sample PSD file. Is this OK in
size?

Regards,
Octavian

**Comment by haraldk** [comment] 2015-02-03 09:03
Ok!

Can you please resend the attachment directly to my email? Attachments doesn't work so well with GitHub..

-- 
Harald K

**Comment by octavian-nita** [comment] 2015-02-06 10:37
I've tested (jdk8, Windows only for the moment) a 3.1-SNAPSHOT build done just now (so latest master) and the colors look much improved, indeed.

Thank you so much,
Octavian (Tavi)

**Comment by haraldk** [comment] 2015-02-06 11:35
Good stuff!

Thanks for confirming. 

-- 
Harald K
