### ISSUE TITLE
No EXIF orientation handling (rotate/mirror)

### ISSUE THREAD

**Issue by barsk** [haraldk/TwelveMonkeys#1075] opened 2024-12-20 11:11 UTC
**Describe the bug**
ImageIO of both the JRE and TwelveMonkey kinds does not properly handle rotation or mirror orientation from the EXIF metadata. Other comparable software like ImageMagick, web browsers and viewers in Windows to name a few does honour the rotate/mirror orientation in metadata and presents the image as indended. ImageIO does not. 

I speculate that this is intentional, in trying to keep the TweleveMonkey plugin compatible with the JRE version, even though this may be considered a bug? I would suggest that TweleveMonkey ImageIO actually would step ahead of the JRE compatibility in this regard and correct this issue, perhaps via a configurable property to toggle this behavious on/off if needed.

In any case I do feel that it would be _very helpful indeed_ if any info of this behaviour and how to work around it can be found in the FAQ section. I did find the cure for this in the contrib section, which I actually stumbled over by luck, but I fear that many may not be that lucky to find the EXIFUtilities class in the contrib parts which indeed have the orientation enabled methods that IMHO should be served by ImageIO itself by default.

**Version information**
Tested 3.4.0 - 3.12.0, all exhibit same behaviour.

**To Reproduce**
Load any image with EXIF metadata Orientation: rotated or mirrored. A sample is provided.

**Expected behavior**
Returned image rotated or mirrored as per metadata orientation.

**Example code**
```
  // Note! ImageIO will NOT handle Orientation (rotate, mirror) from Exif metadata by itself. 
  // We need to use a specific handling to make the rotation/mirroring happen.
  // This is supported by TweleveMonkeys contrib code as below.
  public  BufferedImage loadBufferedImage(File file) throws IOException {
	 return (BufferedImage) EXIFUtilities.readWithOrientation(file).getRenderedImage();
  }
```
**Sample file(s)**
Attached image is mirrored (horisontal) and will be properly viewed in a viewer or web browser, but improperly mirrored when loaded by ImageIO. Zoom in and look at the registration number.

![0146](https://github.com/user-attachments/assets/3d187a52-d0a7-4b26-8c99-09aebbe575f0)

**Comment by haraldk** [comment] 2024-12-20 13:52
Hi @barsk,

I kind of agree with you, but... It's complicated. See #288 for details. 

I'll close this issue as a duplicate of #288 for now.

**Closed by haraldk** 2024-12-20 13:52 UTC
Labels: New feature, Reported bug
