### ISSUE TITLE
Incorrect rendition gererated for a psd file

### ISSUE THREAD

**Issue by indra2gurjar** [haraldk/TwelveMonkeys#447] opened 2018-10-04 11:48 UTC
File  - https://www.dropbox.com/sh/n8x4z1nqph23tla/AAAGDCrHaRmDPrsuhlNwnv_Ca?dl=0

**Comment by haraldk** [comment] 2018-10-04 14:31
Hi Indra,

How do you expect the linked image to be rendered? It appears to render fine here, using the latest (3.4.1) version.

Also, what version of the library are you using, and what Java version (full output of `java --version`) and platform are you running on. 

Finally, if more advanced code than `ImageIO.read` is required to show the problem, please attach the  minimal source code to reproduce. 

PS: Keep in mind that the TwelveMonkeys ImageIO PSD plugin does not "render" PSD files, it simply reads the "composite layer" (and additional layers containing image data) into `BufferedImage`s.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2018-10-05 11:57
Hi again,

I believe this issue is fixed in the 3.4 (3.4.1) release. Please upgrade your dependencies and try again. 

If upgrading the library version does *not* help, please reopen this issue, and include the full output of `java --version`, as mentioned above. 


Best regards,

-- 
Harald K

**Closed by haraldk** 2018-10-05 11:57 UTC
Labels: Trouble-shooting

**Comment by haraldk** [comment] 2018-10-05 12:01
Duplicate of #384
