### ISSUE TITLE
Tiff reader/writer corrupts image data.

### ISSUE THREAD

**Issue by barryspearce** [haraldk/TwelveMonkeys#233] opened 2016-04-01 11:16 UTC
The Tiff reader (possibly writer) damages images. I am using standard options to the writer for an uncompressed image.

The steps to reproduce are:
Load a source image (jpg/tiff/png) into BufferedImage
Redraw the loaded image onto a new buffered image forced to INT_RGB and white BG instead of transparency. New image is same width/height.
SHA256 pixels.
Same image to disk.
Repeat using saved image as the new image to load.

Using a JPG initial then writing TIFF and doing 2 further iterations with TIFF images the TIFF images degrade rapidly. There is clearly an alignment problem. The SHA256 changes every time.

Using the same JPG image but writing PNG and doing 2 further iterations with PNG images the images remain constant and the SHA256 remains stable.

Ill knock up a noddy to isolate for testing but essentially the code (note this is extracted and edited - not running code but is used to provide the salient information) is:

       BufferedImage loadedImage = ImageIO.read(source.toFile());
        width = loadedImage.getWidth();
        height = loadedImage.getHeight();

        //
        // Turn whatever we have coming in into a straight RGB image without
        // transparency, converting from original colourspace to RGB. 
        //
        image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
        image.createGraphics().drawImage(loadedImage, 0, 0, Color.WHITE, null);
        sha256Image(image);

        File imgOutFile = new File(filename);
        ImageIO.write(image, "tiff", imgOutFile);`

and sha256 (Using BouncyCastle as provider) is obtain by:

        ByteBuffer byteBuffer = ByteBuffer.allocate(4 * width * height);
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {
                byteBuffer.putInt(img.getRGB(x, y));
            }
        }

        // hash.reset();
        hash = MessageDigest.getInstance("SHA-256", "BC");
        hash.update(byteBuffer.array());
        return Hex.toHexString(hash.digest());`

As I said Ill get a full class together to show the issue in full but this should be enough to understand the problem.

**Comment by haraldk** [comment] 2016-04-01 13:36
Hi Barry,

Thanks for reporting! 

If you can make this into a failing JUnit test case, that would be preferable, but anything that can reproduce the issue is good.

I'll look into it.


Regards,

-- 
Harald K

**Comment by barryspearce** [comment] 2016-04-01 17:41
OK Here is a simple file which shows the degradation. 
I am fairly certain the fault lies in the tiff reader - could be the writer but as the first write looks correct I suspect that the reader is at fault.

The output from the code is
Loaded Image SHA-256: db8013f63c2d67aa4d3f20bbeced0198a9286f812daf9246c5982fd4e4320206
SHA-256: db8013f63c2d67aa4d3f20bbeced0198a9286f812daf9246c5982fd4e4320206
Loaded Image SHA-256: 01f51e0ef5ba08e8649d429c50abdcef488d59ff8d9009f78e5e05ebde69e4fe
SHA-256: 01f51e0ef5ba08e8649d429c50abdcef488d59ff8d9009f78e5e05ebde69e4fe
Loaded Image SHA-256: 7067cc3844b1969dd7dd48b223a58ecfc4c9f3369e1e64a7e44a034ab56f1229
SHA-256: 7067cc3844b1969dd7dd48b223a58ecfc4c9f3369e1e64a7e44a034ab56f1229

I cant load up the tiffs so here attached is a PNG showing the original jpg, 1,2, and 3 output tiffs.
![1770c_francescomaggiotto_etchingbygiovannivolpato_puppettheatre-writes](https://cloud.githubusercontent.com/assets/18211861/14215184/551c0084-f839-11e5-9257-a6b6b9f134ab.png)

(Here is the java program - renamed to a txt due to upload restrictions here!)
[TwelveMonkeysImageTest.txt](https://github.com/haraldk/TwelveMonkeys/files/200051/TwelveMonkeysImageTest.txt)
![1770c_francescomaggiotto_etchingbygiovannivolpato_puppettheatre](https://cloud.githubusercontent.com/assets/18211861/14215036/5c97af08-f838-11e5-82bc-718f4e20ca84.jpg)

**Comment by barryspearce** [comment] 2016-04-01 17:47
As my application is image indexing using ORB feature descriptors Im thinking about whats happening and I cant work out whether the reader is at fault or the writer.

**Comment by haraldk** [comment] 2016-04-04 07:51
Hi again Barry,

Thanks for providing a test and sample data!

After some research, I believe this is a duplicate of #220 and that the bug is fixed in the master branch.
With the fix applied, the images seems unchanged between each iteration.

 The fix will be released as part of the next version. Sorry about the inconvenience.

Best regards,

-- 
Harald K

**Comment by barryspearce** [comment] 2016-04-04 08:38
No worries. Ill clone and build. :)
Cheers.

**Comment by barryspearce** [comment] 2016-04-04 20:50
Ah. Would do except the master branch wont build as maven reports issues during tests...
------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.twelvemonkeys.image.ResampleOpTestCase
WARNING: Unable to transform src image, image: BufferedImage@4c75cab9: type = 13 IndexColorModel: #pixelBits = 8 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@1ef7fe8e transparency = 1 transIndex   = -1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 10 height = 10 #numDataElements 1 dataOff[0] = 0
Tests run: 44, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.861 sec - in com.twelvemonkeys.image.ResampleOpTestCase
Running com.twelvemonkeys.image.BufferedImageFactoryTestCase
Tests run: 19, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.118 sec - in com.twelvemonkeys.image.BufferedImageFactoryTestCase
Running com.twelvemonkeys.image.ImageUtilTestCase
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.308 sec <<< FAILURE! - in com.twelvemonkeys.image.ImageUtilTestCase
testToBufferedImage(com.twelvemonkeys.image.ImageUtilTestCase)  Time elapsed: 0.004 sec  <<< FAILURE!
java.lang.AssertionError: 
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at com.twelvemonkeys.image.ImageUtilTestCase.testToBufferedImage(ImageUtilTestCase.java:108)


Results :

Failed tests: 
  ImageUtilTestCase.testToBufferedImage:108 

Tests run: 73, Failures: 1, Errors: 0, Skipped: 2

So its proving awkward to work around this at the mo...As you know the code can I take the commits relating to this and patch 3.2.1? Will the changes play well with the previous release?

**Comment by haraldk** [comment] 2016-04-05 07:27
Hi again,

The master branch builds fine locally, as well as on the [Travis CI server](https://travis-ci.org/haraldk/TwelveMonkeys/branches), so that's very strange...

What JDK and Maven versions are you using?

-- 
Harald K

**Comment by barryspearce** [comment] 2016-04-05 10:27
Hi,
Im on Debian testing on a fully up-to-date system.

java -version
openjdk version "1.8.0_72-internal"
OpenJDK Runtime Environment (build 1.8.0_72-internal-b15)
OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)

mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_72-internal, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-1-amd64", arch: "amd64", family: "unix"

Complete output from mvn package:
[tm-package.txt](https://github.com/haraldk/TwelveMonkeys/files/204247/tm-package.txt)

Its failed the assert in testToBufferedImage():

`testToBufferedImage(com.twelvemonkeys.image.ImageUtilTestCase)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: 
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at com.twelvemonkeys.image.ImageUtilTestCase.testToBufferedImage(ImageUtilTestCase.java:108)`

`// Hmmm...
        assertTrue(new Integer(42).equals(bufferedScaled.getProperty("lucky-number"))
                || bufferedScaled.getPropertyNames() == null
                || bufferedScaled.getPropertyNames().length == 0);`

**Comment by haraldk** [comment] 2016-04-05 10:46
I see. 

It's a known issue that some tests will fail on OpenJDK (the tests may be a little too strict or making some incorrect assumptions). I had the same issue when trying to enable OpenJDK build for Travis.

If possible, try building using an Oracle JDK, or build without tests (you already know the tests passed, from the Travis CI build). There might be some slight differences between the two runtimes, but the compiled code should be the same.

-- 
Harald K

**Comment by haraldk** [comment] 2016-04-20 08:09
Closing for now.

Feel free to reopen if you have further problems with this.


Regards,

-- 
Harald K

**Closed by haraldk** 2016-04-20 08:09 UTC
Labels: Trouble-shooting

**Comment by haraldk** [comment] 2016-11-03 12:31
@barryspearce This bugfix is now included in the official 3.3 release.
