### ISSUE TITLE
WebP: Reading from ImageInputStream with unknown length does not decode (produces black image)

### ISSUE THREAD

**Issue by GauravAshara** [haraldk/TwelveMonkeys#672] opened 2022-04-14 06:11 UTC
I tried to convert webP file to JPG with TwelveMonkeys imageIO 8.2 version. My output jpg image turn black. 

```File inputFile = new File(path + fileName);
String targetFileName = path + "../out/" +  fileName;
targetFileName = targetFileName.substring(0, targetFileName.lastIndexOf(".")) + ".jpg";
File outputFile = new File(targetFileName);
		    	
InputStream is = new FileInputStream(inputFile);
ImageInputStream iis = ImageIO.createImageInputStream(is);
BufferedImage originalImage = ImageIO.read(iis)

BufferedImage newImage = new BufferedImage(Math.round(newSize[0]), Math.round(newSize[1]), BufferedImage.TYPE_INT_RGB);
					
Image scaleImage = originalImage.getScaledInstance( Math.round(newSize[0]-diffAdd),  Math.round(newSize[1]),Image.SCALE_DEFAULT);
					
Graphics g = newImage.getGraphics();
g.setColor(Color.WHITE);
g.fillRect(0, 0, Math.round(orgWidth + 2 * diffAdd), Math.round(newSize[1])); //Adds white bar on right and left.
g.drawImage(scaleImage, Math.round(diffAdd), 0, null);

g.dispose();
					
OutputStream os = new FileOutputStream(outputFile);
ImageOutputStream ios = ImageIO.createImageOutputStream(os);
				        
ImageIO.write(newImage, "jpg", ios); 
```
I added following jars 
common-image-3.8.2.jar
common-io-3.8.2.jar
common-lang-3.8.2.jar
imageio-core-3.8.2.jar
imageio-jpeg-3.8.2.jar
imageio-metadata-3.8.2.jar
imageio-tiff-3.8.2.jar
imageio-webp-3.8.2.jar

**Comment by haraldk** [comment] 2022-04-14 07:45
Can you please (using a debugger) pinpoint at which step the image turns black? 

If the read method returns a black image, please attach a WebP file that shows this behavior. 

If the image is good before writing as JPEG, can you rewrite the code to a failing test case? At least you need to make the code compileable and stand-alone without any undefined variables.

**Comment by GauravAshara** [comment] 2022-04-14 14:20
I debugged it. Read file also shows black. 
I attached the Image and my java code.

[webpToJpg.zip](https://github.com/haraldk/TwelveMonkeys/files/8489875/webpToJpg.zip)

**Comment by haraldk** [comment] 2022-04-14 20:44
Okay,

I’ll try to look into it over the holidays.

**Comment by haraldk** [comment] 2022-04-19 07:28
Odd...

I can reproduce the black image issue using:

```java
File inputFile = new File(args[0]);
InputStream is = new FileInputStream(inputFile);
ImageInputStream iis = ImageIO.createImageInputStream(is);
BufferedImage originalImage = ImageIO.read(iis);
```

However, using:

```java
File inputFile = new File(args[0]);
BufferedImage originalImage = ImageIO.read(inputFile);
```

...reads the image as it should. 🤔 

You can use that form as a workaround for now, but of course, both versions should work exactly the same... I'll investigate.

**Comment by GauravAshara** [comment] 2022-04-19 11:44
Yes, It's work

**Comment by haraldk** [comment] 2022-04-19 12:27
Good!

I found the bug too, it turns out the code has multiple places where the current stream position is compared to the stream length. However, for `ImageInputStream`s based on an `InputStream`, this length is not known, and retuned as `-1`, so the test just returns false and nothing more happens... Thus the black image.

I'll create a fix for this soon.

**Closed** 2022-04-25 08:40 UTC
Labels: Confirmed bug, Trouble-shooting
