### ISSUE TITLE
CMYK jpeg with inverted Colors (adobe image)

### ISSUE THREAD

**Issue by AlexFromStackOverflow** [haraldk/TwelveMonkeys#141] opened 2015-06-03 13:41 UTC
![bytes](https://cloud.githubusercontent.com/assets/12731904/7961271/badcd14a-0a06-11e5-95c7-4adeab7a8bc8.jpg)
Here is the image i get. You told me on StackOverflow to create a new issue and attach the bytes i get from the getImageAsBytes() method

**Comment by AlexFromStackOverflow** [comment] 2015-06-03 13:51
![adobe_with_no_trouble](https://cloud.githubusercontent.com/assets/12731904/7961452/f90fa07c-0a07-11e5-8368-562f3d59bdea.jpg)
This picture is also CMYK and adobe but this works just fine. Colors get right if i write it to a bufferedImage. The first one comes from indesign. this one is from photoshop

**Comment by haraldk** [comment] 2015-06-03 14:25
Good stuff! Thanks for reporting!

Just to make sure what I'm looking at here. The upper image is supposed to be red, with black "things" and white text?

The below image looks correct using the plugin (but inverted here), I think. Right?

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-03 14:26
Exactly!

**Comment by haraldk** [comment] 2015-06-03 18:43
Hmmm..

Unfortunately, there's nothing in the first file/stream that indicates that the image should not be inverted, as is usual for CMYK JPEGs. However, there might be information in the PDF (perhaps the associated `PdfDictionary` or otherwise), outside the JPEG stream, that dictates this.

From what I remember from working with the PDFBox guys (you might want to check with the iText team), this is quite normal.

So, you'll have to do something like (you need this only for YCCK/CMYK images, I think, as RGB is never stored inverted):

    PdfImageObject image = ...;

    byte[] imgBytes = image.getImageAsBytes();
    
    ImageInputStream input = ImageIO.createImageInputStream(new ByteArrayInputStream(imgBytes));
    ImageReader reader = ImageIO.getImageReaders(input).next(); // TODO: Do this safely
    
    reader.setInput(input);
    WritableRaster raster = reader.readRaster(0, null); // Read the data as-is
    IIOMetadata metadata = reader.getImageMetadata(0);

    // TODO: Get source color space from standard metadata, and convert from YCCK to CMYK if needed.
    // TODO: Get ICC profile from native metadata, and create color space/color model.
    // TODO: Create BufferedImage from color space/color model and raster.
    // TODO: Optional, convert from CMYK to RGB for faster display, using ColorConvertOp.

(You can see how to do most of these things, by looking at the source code for the `JPEGImageReader` class).

Hope that helps!

PS: It could be that we should add a parameter to the `ImageReadParam`, that allows overriding the CMYK inversion, as it makes sense for extracting CMYK images from a PDF. Need to think about that for a little while though...


Regards,

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-03 19:59
Thanks so far. But the thing i dont quite understand is that this goes wrong ,even if you write this images to a file and store them on your hard drive and try to load the files into the BufferedImage. They are normal files without any strage informations and you use just the normal java and no pdf files from there. That kind of stuff drives me crazy cause things happen and i cant figure out why. But thanks for your effort.

**Comment by AlexFromStackOverflow** [comment] 2015-06-04 09:30
I did some preflight on the pdf files and the one that doesnt work has an indexed color space and the one that works has a direct embeeded color space. (both cmyk)

**Comment by haraldk** [comment] 2015-06-04 13:00
Well... 

It's really quite simple. The information on how to interpret the CMYK data in the JPEG is stored outside the JPEG stream itself, but in the PDF document. This makes it easy for a PDF reader/viewer to invert and display the values as they should. However, a JPEG decoder can only decode the data in the JPEG (and don't know what it is embedded in), and so it will look inverted. When we store it to disk, we store the same embedded JPEG, without the inversion information, and it will look the same.

I think you'll find that most software capable of displaying CMYK JPEGs will display your images inverted.

I don't really understand what you mean about "indexed color space", or that the one that works contains an embedded color space. There are no ICC profiles embedded in any of the images you have attached. However, one (the first) is in CMYK color space (you can see this from the component ids: C, M, Y & K), while the second is YCCK (from the Adobe/APP14 segment, which has the YCCK transform). YCCK is just a lossless conversion from CMYK.

That is not why one appear inverted though. :-)
In the second image, there's a flag in the Adobe/APP14 segment, indicating non-inverted values, which is missing from the first.


Regards,

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-04 14:07
I see. Well the indexed color space thing is what you see in the logfile if you do preflight with adobe acrobat on a pdf you have created with INDESIGN and exported it with a webcoated eu icc profile. The protoshop and illustrator exported pdfs embeed the profile directly but indesign pdfs have an extra node in the log thas sas indexed colorspace and inside that node there is one more node and there you can see the icc profile and color space. Its kinda hard to explain, but i think you know what i mean if you worked with acrobats preflight function. Thanks for you help

**Comment by haraldk** [comment] 2015-06-05 07:45
Okay, I think I get it now. I only have brief knowledge about the PDF format, sorry. 

I guess you could put the flag in the image, but that requires parsing and re-writing the JPEG. Another option would be to decode the image as CMYK. My `JPEGImageReader` will be default convert the image to sRGB, but you can control it, by looking at the metadata to see if the image is CMYK and pick the `ImageTypeSpecifier` that corresponds to CMYK. Then you could skip inverting (the problem is really that the code *expects* the data to be inverted, while it isn't). 

Another benefit of this approach, is you could optionally convert the image to sRGB using the correct ICC profile (as found in the PDF). As there's no profile segment inside the JPEG stream, the decoding process just uses a "generic" CMYK colorspace for the conversion, so the colors will not be exactly as intended. 

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-05 09:52
To skip the convert algorithm to rgb was my very first thaught but i m kinda new to the whole image and colorspace stuff so i didnt quite get it how to skip the to rgb conversion. Can you give me a little code help please? i mean the part where you read out the color space from the metatdata and say that the JPEGImageReader should let the CMYK stay CMYK and not convert it. Thanks for the tipps so far

**Comment by haraldk** [comment] 2015-06-05 10:45
You can either use the code from my [second comment](https://github.com/haraldk/TwelveMonkeys/issues/141#issuecomment-108570213), which reads the raster as-is (no conversion at all).

Or, you can obtain the `ImageReader` the same way, and iterate over the `ImageTypeSpecifier`s to find the best match (if there is one with CMYK color space, that's the one), and pass it to the read param, like this:

    ImageReader reader; // assumes initalized etc as above

    ImageTypeSpecifier cmykType = null;
    Iterator<ImageTypeSpecifier> types = reader.getImageTypes(0);
    while (types.hasNext()) {
        ImageTypeSpecifier type = types.next();;
        if (type.getColorSpace().getType() == ColorSpace.TYPE_CMYK) {
            cmykType = type;
            break;
        }
    }
    
    ImageReadParam param = reader.getDefaultReadParam();
    param.setDestinationType(cmykType); // May be null, that is okay, but you'll get an RGB image

    BufferedImage image = reader.read(0, param);

    if (cmykType != null) {
        WritableRaster raster = image.getRaster();
        invertRaster(raster);
    }

    ...
    
    static void invertRaster(final Raster raster) {
        byte[] data = ((DataBufferByte) raster.getDataBuffer()).getData();

        for (int i = 0, dataLength = data.length; i < dataLength; i++) {
            data[i] = (byte) (255 - data[i] & 0xff);
        }
    }

Something like that. :-)

No need to change any code in the `JPEGImageReader`.

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-05 11:51
Thank you very much! But the methods 
type.getColorSpace().getType() 
and 
getDataBuffer().getData();
Are troubeling me
the getData method doesn exist for that operation somehow
and for the getColorSpace eclipse says
The method getColorSpace() is undefined for the type ImageTypeSpecifier
I will throw a look at the api of these too

**Comment by haraldk** [comment] 2015-06-05 11:59
As I said, "something like that"... ;-)

It's:

    ImageTypeSpecifier type;
    type.getColorModel().getColorSpace().getType();

And

    ((DataBufferByte) raster.getDataBuffer()).getData();

(ie, the method is only defined for the subclasses, you need the cast. But I really wrote that above).


-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-05 12:32
Iterator<ImageTypeSpecifier> types = r.getImageTypes(0); <- Exception in thread "main" java.lang.IllegalStateException: Input not set
Man, i think i should better use the raster method . The whole loop thing is just a pain xD
and i initalize the reader like you showed me with
ImageInputStream input = ImageIO.createImageInputStream(new ByteArrayInputStream(imgBytes));
ImageReader r = ImageIO.getImageReaders(input).next();

**Comment by haraldk** [comment] 2015-06-05 12:53
Yes,

    reader.setInput(input);

That's what I meant by `// assumes initalized etc as above`. :-)

If you use the raster method, yes, RGB stays RGB and CMYK stays CMYK. However, the same applies for YCbCr and YCCK which are the more common JPEG "color spaces". You can look at the `JPEGImageReader` to see how that is converted to RGB and CMYK respectively.

And, no, you don't need to look for the image type. But you need to get the source color space from the metadata. Otherwise you won't know what conversions to apply.

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-05 13:09
ok right as i thought that everything should be fine now i get a
Exception in thread "main" javax.imageio.IIOException: Invalid argument to native writeImage
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeImage(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1058)
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:360)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageWriter.write(Unknown Source)
	at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	at javax.imageio.ImageIO.write(ImageIO.java:1578)
	at Classes.PDF.main(PDF.java:93)
after trying to execute that code
 PdfImageObject image = new PdfImageObject(stream);
	                // image objekt zu bufferedimage convertieren
	                byte[] imgByte = image.getImageAsBytes();

	                ImageInputStream input = ImageIO.createImageInputStream(new ByteArrayInputStream(imgByte));
	                
	                ImageReader r = ImageIO.getImageReaders(input).next(); 
	                r.setInput(input);
	                ImageTypeSpecifier cmykType = null;
	                Iterator<ImageTypeSpecifier> types = r.getImageTypes(0);
	                while (types.hasNext()) {
	                    ImageTypeSpecifier type = types.next();;
	                    if (type.getColorModel().getColorSpace().getType() == ColorSpace.TYPE_CMYK) {
	                        cmykType = type;
	                        break;
	                    }
	                }

	                ImageReadParam param = r.getDefaultReadParam();
	                param.setDestinationType(cmykType); // May be null, that is okay, but you'll get an RGB image

	                BufferedImage bi = r.read(0, param);

	                
	                FileOutputStream st = new FileOutputStream("dafuk.jpg");
	                ImageIO.write(bi, "JPEG", st);

**Comment by haraldk** [comment] 2015-06-05 17:30
Do you *need* to write the image as CMYK? The `JPEGImageWriter` doesn't support it (it does support writing as CMYK as `Raster` but it's complicated, so I'll skip that for now). 

If you just need to store the image, you can `ColorConvertOp` to convert to RGB (as mentioned in my second comment):

    BufferedImage bi; // The CMYK BufferedImage from your code

    ICC_Profile sourceProfile = ICC_Profile.getInstance(profileBytes); // The profile from your PDF (indexed or embedded)
    ICC_Profile sRGB = ICC_Profile.getInstance(CS_sRGB);

     ColorConvertOp convert = new ColorConvertOp(new ColorProfile[] {sourceProfile, sRGB});
    BufferedImage rgbImage = convert.filter(bi, null);

    FileOutputStream st = new FileOutputStream("dafuk.jpg");
    ImageIO.write(rgbImage, "JPEG", st);

Ok?

-- 
Harald K

**Comment by jahewson** [comment] 2015-06-05 20:23
PDFBox committer here.

> The information on how to interpret the CMYK data in the JPEG is stored outside the JPEG stream itself, but in the PDF document.

Yes, exactly. PDF even allows the APP14 segment flags to be stored in the PDF instead of in the JPEG (I assume that's what's happening here). This can be found in the `ColorTransform` key of the `DCTDecode` filter for the given image. This key is ignored if the JPEG contains an APP14 marker.

> Another benefit of this approach, is you could optionally convert the image to sRGB using the correct ICC profile (as found in the PDF). As there's no profile segment inside the JPEG stream, the decoding process just uses a "generic" CMYK colorspace for the conversion, so the colors will not be exactly as intended.

Worse still, it's common for PDF files to not contain ICC color spaces but instead to rely on PDF's generic color spaces which are not defined. So it's entirely possible that the PDF itself contains an image which uses an unspecified device-specific color space. Acrobat uses *US Web Coated (SWOP) v2* by default, but it's not part of the spec and other viewers (e.g. OS X Preview) don't share this behaviour.

**Comment by haraldk** [comment] 2015-06-06 09:53
@jahewson Thanks for your input! Much appreciated.

My point is that the full information on how to properly decode the JPEG is only available if you have access to the information in the PDF.  Because of this, perhaps it would be a good idea if the PDF library could instruct the JPEG reader how to decode the image. Making it possible to dictate inversion and possibly passing an ICC profile. What do you think?

PS: You probably already know this, but Adobe has quite a few ICC profiles (like the one mentioned) available for [free download](http://www.adobe.com/support/downloads/product.jsp?product=62&platform=Windows). Unfortunately, they are not re-distributable, as far as I understand...

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-11 07:11
Thanks for the advice! I tried to work with the adobe icc profiles allready but without success. Colors are still inverted (but not in the same way, depending on the icc profile they are darker or brighter). Maybe i was aproaching this issue in the wrong place because i tried to decode the images after i allready extracted them from the pdf file.
And @Harald 
I dont need to write the images as CMYK. my thought was to extract them without conversion so they maybe wouldnt be inverted enymore and then bind an ICC profile to them + write them back into the pdf file as an rgb image. I Will look for more information about that whole stream thing and try to figure out how to handle it.

**Comment by haraldk** [comment] 2015-06-11 07:45
Ok,

Re. profiles: I didn't suggest that you should use the Adobe downloadable ICC profiles if you already have an ICC profile in your PDF. Neither that it would fix the color inversion issue. They are only useful if you have a PDF like @jahewson suggested, where the profile isn't embedded.

Re. writing: If you don't need to write as CMYK, the code I posted should work. Did it?

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-12 09:45
I didnt have the time in the last days to try it out . I will give you some feedback when i start doing this again. Should be within the next week. Thank you so far. Sorry that i took so much of your time. Im still learning the whole stuff =).

**Comment by AlexFromStackOverflow** [comment] 2015-06-15 11:23
There is something wrong with this row:
ColorConvertOp convert = new ColorConvertOp(new ColorProfile[] {sourceProfile, sRGB});

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	ColorProfile cannot be resolved to a type
	Type mismatch: cannot convert from ICC_Profile to ColorProfile
	Type mismatch: cannot convert from ICC_ColorSpace to ColorProfile
allso had to change CS_sRGB to ICC_ColorSpace.CS_sRGB

**Comment by haraldk** [comment] 2015-06-15 13:02
Hi Alex,

    Type mismatch: cannot convert from ICC_Profile to ColorProfile

Did you try just changing it to `ICC_Profile`?

Listen, I don't mind helping out a little. But please be reasonable. You should not expect me to write production quality code for you, that compiles and works with no effort on your hand. If you want to fix this yourself, you might need to read up on some subjects, or ask for furter advice (for example on StackOverflow). :-)


Best regards,

-- 
Harald K

**Comment by AlexFromStackOverflow** [comment] 2015-06-15 13:58
yep i tried to change it to icc_profile and also to icc_colorspace im still working on it and just wanted to give the feedback cause you asked if it works or not. didnt expect any help at that time =)

**Comment by haraldk** [comment] 2015-06-17 10:58
Ok, fair enough. :-)

I don't think there's anything special about PS color inversion. It's just that you need to apply the color inversion in CMYK color space. I got the expected colors for your images this way. 

I'm closing this issue for now, feel free to update with a solution, if you like!

PS: Fixed the sample code above, anyway. 

-- 
Harald K

**Closed by haraldk** 2015-06-17 10:58 UTC
Labels: Trouble-shooting
