### ISSUE TITLE
PSD/PSB files with non-transparency alpha channels rendered incorrectly

### ISSUE THREAD

**Issue by vsarya** [haraldk/TwelveMonkeys#384] opened 2017-10-23 05:30 UTC
Incorrect thumbnails (attached) are generated for following psb files - 

1 alpha + 3 channels RGB & flatten.psb - https://drive.google.com/open?id=0B1SBo6BEhvipemFIT1pTYmtkTVE
4 alpha + 3 channels RGB & flatten.psb - https://drive.google.com/open?id=0B1SBo6BEhvipeU9lZmJRVnd3RXc

[1 alpha 3 channels rgb flatten.jpeg](https://user-images.githubusercontent.com/11541786/31873507-23c5800a-b7e1-11e7-9ec8-ceb0fd4793e3.jpeg)
[4 alpha 3 channels rgb flatten.jpeg](https://user-images.githubusercontent.com/11541786/31873508-23ecf306-b7e1-11e7-95e3-647940fb743e.jpeg)

**Comment by haraldk** [comment] 2017-10-23 08:44
Hi again Vishal,

The library does not *generate* thumbnails, it simply *reads* the thumbnails embedded in the files. 

To me, the thumbnails look completely reasonable. They just don't match the image data in the file, but that's up to the software that *writes* the PSD/PSB files. It's not much we can do about that situation.

Re-rendering the composite image data or the thumbnail based on all layers and effects etc. in the file, is outside the scope of the `PSDImageReader` (as it would require re-creating pretty much the entire Photoshop rendering pipeline to do so). 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2017-10-24 08:30
PS: If you need to (re-)generate a thumbnail from the composite data, you may use a tool like [thumbnailator](https://github.com/coobird/thumbnailator) to do so. 

Closing this issue for now, as the `PSDImageReader` works as expected.

-- 
Harald K

**Comment by yann117** [comment] 2017-10-25 09:48
Hello Harald,

I think there is a misunderstanding here.

I had initially reported this issue, so I'd like to provide more details and try to clarify the situation.

We are using the TwelveMonkey library to process image files and create custom web renditions (smaller in size), that we also call _thumbnails_ from our point of view. This is why I used this term initially when speaking with Vishal.

However, from the TwelveMonkey point of view, there is no relation to "thumbnail". We are not using the potential thumbnails embedded within the PSD/PSB image, but just trying to read the actual image itself.

We encounters the described problem as soon as the picture does have **one or more alpha channels** (even when in our case, these alpha channels **are hidden** when looking at the file in Photoshop).

Also, if I convert this picture to use instead the CMYK image mode instead of RGB, then this is working fine (thanks partly to your fix for the multiple alpha channels).

I would add for clarity, that the image is flatten-ed, so having only one layer.

Now there is something I'm unsure, regarding your answer:
> The library does not generate thumbnails, it simply reads the thumbnails embedded in the files.
> Re-rendering the composite image data or the thumbnail based on all layers and effects etc. in the file, is outside the scope of the PSDImageReader

On one hand I quite understand that your library may read the picture from the embedded thumbnail, as it could not re-create it like Photoshop would do.

But as the discussion was originally oriented towards the thumbnails due to the title/description, I'm not sure if you tried to explain that your lib does not generate these embedded thumbnails/renditions, and/or **if it is really required to have these thumbnails in the file to work**.

So at the end, I can't conclude if there is really an issue in the TwelveMonkey library or not.

Best regards,
Yannick.

**Comment by haraldk** [comment] 2017-10-25 10:43
Okay,

There might be some confusion here, as you say. ..

When I talk about thumbnails, I mean what is returned from [`ImageReader.readThumbnail(..)`](https://docs.oracle.com/javase/7/docs/api/javax/imageio/ImageReader.html#readThumbnail(int,%20int)) (and related "thumbnail" methods in the `ImageReader`). These are simply read from what is in the file. They are not rendered in any way by the `ImageReader`. As these thumbnails clearly does not match the image data in the above files, I thought that was your "issue". **It is not required to have these in the file**. In the case they are not, `getNumThumbnails(..)` will simply return 0, and any attempt at `readThumbnail(..)` will fail. 

If instead you are talking about thumbnails that *you* generate (like I now think, after reading your update) from the composite layer, then the above probably doesn't make much of a difference to you. 

It is still not clear to me though, what you mean is the problem with the rendering of the attached files, or what is the meaning of the attached JPEG renderings. Are the JPEGs the output of your "thumbnail generating" process? In this case, it would be useful to attach what you expected them to be (ie. attach a screenshot from another program that you mean display it correctly, like Photoshop). Keep in mind that until someone sponsors the project with a copy of Photoshop license, I don't own the product and can't use that as a test... Or are they what you expect the renderings to look like? If that is the case, they look the same to me here, so I need an actual rendering. 

Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2017-10-25 19:16
Okay,

I have opened the file now on macOS Preview, and I can see the images are interpreted/rendered incorrectly. I'll look into it!

-- 
Harald K

**Comment by yann117** [comment] 2017-10-26 12:10
Hello Harald,

Thank you for having clarified the point with the embedded thumbnails, which are not required as I would expect it.

I think now that we are in line, but just to answer your questions, the two first attached files, were the resulting thumbnails that we have generated on our side by using the TwelveMonkey lib. One was using one single hidden alpha channel, and the other one had 4 hidden alpha channels.

And here (as you already found now) is the expected result:

![the-expected-result](https://user-images.githubusercontent.com/33085811/32052081-5b94883c-ba57-11e7-9449-670090c50957.jpg)

Best regards.

**Comment by haraldk** [comment] 2017-10-26 14:03
Excellent!

Yes, we are on the same page now. 😀

Also good news: I have a fix ready, just need a little clean-up and possibly some test coverage before I push it. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2017-10-27 08:28
PS: Do you have (or can you create) a smaller PSD/PSB with the same issue, that I can include in a test? Doesn't matter much what it contains, as long as it's possible to visually inspect, has 1 or  2 non-transparency alpha channels, and is small in file size (100x100 pixels or so).

**Comment by yann117** [comment] 2017-10-27 09:47
Just tried creating something really simple, and discovered that I could only reproduce the issue when saving it as PSB. Saving the same file as PSD doesn't trigger the problem.

So here is a RGB (8bit/channel) file with a single layer, with one hidden alpha channel. I attached the actual (issue) result, and the expected result as PNG files.

Actual result (for the PSB):
![it-test-actual-result](https://user-images.githubusercontent.com/33085811/32098306-8f60fcc6-bb0c-11e7-8b6c-989837608873.png)

Expected result:
![it-test-expected-result](https://user-images.githubusercontent.com/33085811/32098308-8f7ab8c8-bb0c-11e7-9cc1-b8868728d97c.png)

**Comment by haraldk** [comment] 2017-10-27 10:01
Excellent! 

Out of curiosity, could you also attach the same file stored as PSD? As I would expect the same issue to be present regardless of PSD/PSB format... Perhaps PS just stores slightly different data for PSD for compatibility reasons.

-- 
Harald K

**Comment by yann117** [comment] 2017-10-27 10:41
I already put both the PSD and PSB export of the picture into the it-test.zip archive :-)

Regarding the issue, I did try the original file, by saving it as a PSD file, and here the issue is no more reproducible again. So this is consistent with the manual picture I made for testing, only PSB format is not working.

Adding another it-test2.zip with the following content:
- 4 alpha + 3 channels RGB & flatten.psb -> original file, rendering is incorrect
- 4 alpha + 3 channels RGB & flatten.psd -> same file saved as PSD, rendering is correct
- it-test.psb -> failing, result is as mentioned above, looking like the "Actual result"
- it-test.psd -> same file saved as PSD, working fine, looking like the "Expected result"

Best regards.
[it-test2.zip](https://github.com/haraldk/TwelveMonkeys/files/1421745/it-test2.zip)

**Comment by haraldk** [comment] 2017-10-27 11:07
Ah,

Sorry, didn't have time to look at it yet. :-)

-- 
Harald K

**Comment by yann117** [comment] 2017-10-27 11:27
No problem at all, take your time, it was to add some clarification.

**Comment by haraldk** [comment] 2017-10-27 17:52
Fixed now, in master. Will be included in the next proper release.

-- 
Harald K

**Closed by haraldk** 2017-10-27 17:52 UTC
Labels: Bug

**Comment by yann117** [comment] 2017-10-31 16:50
Thank you Harald.
