### ISSUE TITLE
Some PSD File Look Weird

### ISSUE THREAD

**Issue by KlausSchaefers** [haraldk/TwelveMonkeys#211] opened 2016-01-27 23:24 UTC
I have tried to convert some newer psd files and something is really wrong with the colors and so on. Everything is a kind of reddish. Also it is a file with multiple art boards which all got merged into one big image...

**Comment by haraldk** [comment] 2016-01-28 07:47
Hi Klaus,

Interesting... I've never seen such a PSD myself, but I guess Adobe continues to advance their file format.

Do you have a sample file to share with me? Preferably not too big, and also good if I can use it in a future test case (although that is not a requirement).


Best regards,

-- 
Harald K

**Comment by KlausSchaefers** [comment] 2016-01-28 09:33
Hi,

the current file I have is some how confidential. I will ask for another
file and make it available. I know it was done with the latest version of
PhotoShop and contained multiple Art Boards. Btw that leads also to a
strange situation the the output Image is huge and contains the different
arts boards. Is there I way to take out the different arts boards?

Cheers,

Klaus

On Thu, Jan 28, 2016 at 8:47 AM, Harald Kuhr <notifications@github.com>
wrote:

> Hi Klaus,
>
> Interesting... I've never seen such a PSD myself, but I guess Adobe
> continues to advance their file format.
>
> Do you have a sample file to share with me? Preferably not too big, and
> also good if I can use it in a future test case (although that is not a
> requirement).
>
> Best regards,
>
> Harald K
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haraldk/TwelveMonkeys/issues/211#issuecomment-176038470>
> .
>



-- 
“Overfitting” is not about an excessive amount of physical exercise...

**Comment by haraldk** [comment] 2016-01-28 09:51
Hi again Klaus,

I understand. I'm not a Photoshop user myself, so I don't really know what an "Art Board" is, and how they are supposed to work. 

The [Adobe Photoshop File Formats Specification](http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/) is what I have and use to implement the `PSDImageReader`, but it makes no mention of this feature. It's probably a new thing introduced in the later version of the product.

So, would I need a specification and a test document preferably, or if no specification is available; a couple of test documents with some variation, and then reverse engineer the specification from there. This could be easy or hard. I would need to look at some files before I can say much more.


Best regards,

-- 
Harald K

**Comment by KlausSchaefers** [comment] 2016-01-28 10:18
Hi,

I will try to provide some test files as soon as possible. I am also not a
PhtoShop expert but I get these files into my system...

Cheers,

Klaus

On Thu, Jan 28, 2016 at 10:51 AM, Harald Kuhr <notifications@github.com>
wrote:

> Hi again Klaus,
>
> I understand. I'm not a Photoshop user myself, so I don't really know what
> an "Art Board" is, and how they are supposed to work.
>
> The Adobe Photoshop File Formats Specification
> <http://www.adobe.com/devnet-apps/photoshop/fileformatashtml/> is what I
> have and use to implement the PSDImageReader, but it makes no mention of
> this feature. It's probably a new thing introduced in the later version of
> the product.
>
> So, would I need a specification and a test document preferably, or if no
> specification is available; a couple of test documents with some variation,
> and then reverse engineer the specification from there. This could be easy
> or hard. I would need to look at some files before I can say much more.
>
> Best regards,
>
> Harald K
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haraldk/TwelveMonkeys/issues/211#issuecomment-176092254>
> .
>



-- 
“Overfitting” is not about an excessive amount of physical exercise...

**Comment by haraldk** [comment] 2016-01-28 11:36
Update!

I got a colleague to send me a PSD sample file with artboards, and surprisingly the reader seems to just read it without problems.

The first image returned by the `PSDImageReader` (and `ImageIO.read(...)` in the case of a PSD) is always what is referred to as the "composite layer", which has been in PSD documents since the beginning. This is the same thing displayed by OS X preview and most other viewers. The fact that it displays all boards as one image, is a choice made my Adobe.

I will still need one of your samples to figure out why you get wrong colors though, as I don't experience the issue with the sample I have.

The reader will also read individual layers, and it seems these layers contain the art boards. There might be some more metadata parsing required to fully re-create the boards as seen in Photoshop CC, if that is something you need to do.


Regards,

-- 
Harald K

**Comment by KlausSchaefers** [comment] 2016-01-28 11:44
Hi,

 > The reader will also read individual layers, and it seems these layers
contain the art boards. There might be
> some more metadata parsing required to fully re-create the boards as seen
in Photoshop CC,
> if that is something you need to do.

OK thanks for the fast reply. Is there any specific API or so to work the
the PSD files? If you can give my a hint were to start, I will have a look!

Thanks,

Klaus




On Thu, Jan 28, 2016 at 12:36 PM, Harald Kuhr <notifications@github.com>
wrote:

> Update!
>
> I got a colleague to send me a PSD sample file with artboards, and
> surprisingly the reader seems to just read it without problems.
>
> The first image returned by the PSDImageReader (and ImageIO.read(...) in
> the case of a PSD) is always what is referred to as the "composite layer",
> which has been in PSD documents since the beginning. This is the same thing
> displayed by OS X preview and most other viewers. The fact that it displays
> all boards as one image, is a choice made my Adobe.
>
> I will still need one of your samples to figure out why you get wrong
> colors though, as I don't experience the issue with the sample I have.
>
> The reader will also read individual layers, and it seems these layers
> contain the art boards. There might be some more metadata parsing required
> to fully re-create the boards as seen in Photoshop CC, if that is something
> you need to do.
>
> Regards,
>
> Harald K
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haraldk/TwelveMonkeys/issues/211#issuecomment-176137258>
> .
>



-- 
“Overfitting” is not about an excessive amount of physical exercise...

**Comment by haraldk** [comment] 2016-01-28 11:50
Hi,

Have a look at the general ImageIO metadata API (form Oracle), and the specific classes:

* `com.twelvemonkeys.imageio.plugins.psd.PSDMetadata`
* `com.twelvemonkeys.imageio.plugins.psd.PSDMetadataFormat`

Other than that, there's not much specific API for PSD.


Regards,

-- 
Harald K

**Comment by haraldk** [comment] 2016-02-15 14:34
Closing this, until we have a test file that can reproduce the issue.

Feel free to reopen, if you find one. :-)

-- 
Harald K

**Closed by haraldk** 2016-02-15 14:34 UTC
Labels: Trouble-shooting
