### ISSUE TITLE
JPEG CMYK without ICC

### ISSUE THREAD

**Issue by hirenshah** [haraldk/TwelveMonkeys#181] opened 2015-10-07 13:27 UTC
Is it possible to use JPEGs in CMYK but without colour profiles?

**Comment by haraldk** [comment] 2015-10-07 13:48
Hi,

Not sure if I understand the question...

Can a JPEG store CMYK data without ICC profiles? Yes, certainly (you'll find one in the [JPEG test data](https://github.com/haraldk/TwelveMonkeys/blob/master/imageio/imageio-jpeg/src/test/resources/jpeg/cmyk-sample-no-icc.jpg)).

Can the library read such a JPEG? Yes, it can. The colors won't necessarily appear as you expect, but that's because without an ICC profile, we can't really tell.

Can the library write such a JPEG? See #25 


Best regards,

-- 
Harald K

**Comment by hirenshah** [comment] 2015-10-07 13:55
Thanks for the speedy response.  We are using Twelve Monkeys in a document generation software called Thunderhead and if place JPEGs without ICC then the resulting AFP file shows black boxes where the images should be.  If I use the same images but with ICC profiles then the images appear fine.  

The issue we have is that by embedding the ICC profile the size of each image is increased by around 500KB which causes an issue with our archive PDF as that also ends up being bigger in size.

**Comment by haraldk** [comment] 2015-10-07 14:11
Hmmm..

Are you actually writing CMYK JPEGs with the library? That is cool. :-)
(It's possible, it's just very hard to implement in a nice, generic way, without messing with `Raster`s and `IIOMetadata`, that's why the issue is still open).

I understand the issue with large profiles. I would think the resulting PDF would only need this profile once, and be able to reuse it. Or perhaps convert all embedded images to a common profile.  But I'm not a PDF expert. The PDF-generating software would have to handle that. 

Unfortunately, I'm not familiar with Thunderhead or AFP, so I won't be much of help there... But I would expect the problem to be there, if you see black boxes.


-- 
Harald K

**Comment by haraldk** [comment] 2015-10-23 07:21
Closing for now. Feel free to reopen if you have further questions!

-- 
Harald K

**Closed by haraldk** 2015-10-23 07:21 UTC
Labels: Trouble-shooting

**Comment by leolux** [comment] 2016-02-01 20:32
Following the discussion above lets me assume that it might be possible to write CMYK JPEGs. I really hope that this is true :) 

At the moment I couldn't find any proper way to write such a color typ. I failed with JRE, the JPEGImageEncoder from Sun's JDK, as well as with the apache imaging library.

Do you have any sample code which I could use as a starting point for writing CMYK JPEGs? Does the following code go into the right direction: https://community.oracle.com/thread/1265114?start=0&tstart=0

Additionaly I like to set an ICC profile, x/y density and no-compression (for printing) my images.

**Comment by haraldk** [comment] 2016-02-03 09:30
@leolux 

Your problem seems to be different than the one reported in the original issue. 

Please keep in mind that this is not a general discussion forum, it is an issue tracker. If you have a problem with the library, feel free to post a new issue. You can link to other issues (like this one) if you feel it is relevant, using a hash symbol '#' and the issue number. 

If you have a general programming problem, please use a relevant forum, like StackOverflow or the Oracle Community.

:-)


Thanks,

-- 
Harald K
