### ISSUE TITLE
SVG crashes the running process.

### ISSUE THREAD

**Issue by RitwikSrivastava** [haraldk/TwelveMonkeys#515] opened 2020-01-22 11:28 UTC
Svg that contains clipPath on images crashes with OutOfMemory Error.
Attaching the SVG 
[test.svg.zip](https://github.com/haraldk/TwelveMonkeys/files/4096863/test.svg.zip)
ThreadDump StackTrace: 

```
"JobHandler: /var/workflow/instances/server0/2020-01-16_1/update_asset_12:/content/dam/build_via_inkscape.svg/jcr:content/renditions/original" #1717 daemon prio=1 os_prio=31 tid=0x00007fca6382d000 nid=0x34903 runnable [0x0000700018246000]
   java.lang.Thread.State: RUNNABLE
        at sun.awt.geom.Order3.nextVertical(Order3.java:532)
        at sun.awt.geom.Curve.compareTo(Curve.java:969)
        at sun.awt.geom.Edge.compareTo(Edge.java:90)
        at sun.awt.geom.AreaOp.pruneEdges(AreaOp.java:278)
        at sun.awt.geom.AreaOp.calculate(AreaOp.java:159)
        at java.awt.geom.Area.pathToCurves(Area.java:195)
        at java.awt.geom.Area.<init>(Area.java:126)
        at org.apache.batik.bridge.SVGClipPathElementBridge.createClip(SVGClipPathElementBridge.java:158)
        at org.apache.batik.bridge.CSSUtilities.convertClipPath(CSSUtilities.java:725)
        at org.apache.batik.bridge.AbstractGraphicsNodeBridge.buildGraphicsNode(AbstractGraphicsNodeBridge.java:146)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:224)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:219)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:171)
        at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:82)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.transcode(SVGImageReader.java:309)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.init(SVGImageReader.java:549)
        - locked <0x000000070448a3e0> (a com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader$Rasterizer.getDefaultWidth(SVGImageReader.java:562)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.getWidth(SVGImageReader.java:229)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.paramsToHints(SVGImageReader.java:169)
        at com.twelvemonkeys.imageio.plugins.svg.SVGImageReader.read(SVGImageReader.java:120)


```

**Comment by haraldk** [comment] 2020-01-22 12:37
Hi,

What versions of Java, Batik and TwelveMonkeys do you use?

I can't read the image either, but I get a different exception stack trace. Using Oracle Java 1.8 or 11, Batik 1.9 and TwelveMonkeys 3.4.3 on MacOS. 

In either case, I believe this is an issue in Batik, and you need to report it there. If unsure, try to open the file in their tools, and see if works as expected there.


Best regards,

-- 
Harald K

**Comment by RitwikSrivastava** [comment] 2020-01-23 05:54
Thanks for the reply. 
We are using twelve monkeys version 3.4 and batik version 1.11 and java 8. iam also trying on MacOs. 

-Ritwik

**Comment by RitwikSrivastava** [comment] 2020-01-24 06:54
I tried to debug the values being passed at at org.apache.batik.bridge.SVGClipPathElementBridge.createClip(SVGClipPathElementBridge.java:158)
I found out this: 
"new Area(outline)"	 (id=75)	
	cachedBounds	null	
	curves	Vector<E>  (id=77)	
		capacityIncrement	0	
		elementCount	3	
		elementData	Object[10]  (id=85)	
			[0]	Order0  (id=87)	
				direction	1	
				x	291.0	
				y	284.0	
			[1]	Order1  (id=90)	
				direction	1	
				x0	291.0	
				x1	291.0	
				xmax	291.0	
				xmin	291.0	
				y0	284.0	
				y1	6252.0	
			[2]	Order1  (id=92)	
				direction	-1	
				x0	6259.0	
				x1	6259.0	
				xmax	6259.0	
				xmin	6259.0	
				y0	284.0	
				y1	6252.0	
			[3]	null	
			[4]	null	
			[5]	null	
			[6]	null	
			[7]	null	
			[8]	null	
			[9]	null	
		modCount	3	

Any idea if ther wrong something with this values?

**Comment by haraldk** [comment] 2020-01-24 10:50
Hi again Ritwik,

Unfortunately, no. I don't know SVG in that detail, neither did I write the code you refer to. As mentioned, my code is just a thin wrapper around Apache Batik. 

You might get better answers on a Batik mailing list or their issue tracker.


Best regards,

-- 
Harald K

**Comment by j-p-sequeira** [comment] 2020-01-28 16:21
Same problem. I'm using Batik 1.12.
I'm not sure, but it seems to be an old Java bug instead of a Batik one.

https://bugs.openjdk.java.net/browse/JDK-6955969

**Comment by KoenDG** [comment] 2020-01-28 18:40
Saw the same thing with a local app.

If it's a Java bug that's currently unresolved, how can we guard against this?

Other SVG image do not produce a similar problem.

Is there a way to detect the particular problem with this image before processing it?

**Comment by haraldk** [comment] 2020-01-29 08:20
@j-p-sequeira Thanks! I wasn't aware of these JDK bugs. Unfortunately, skimming through the descriptions, they seem to be non-trivial to fix (and as you mention, have been around for some time, ie. since Java 8). 

@KoenDG Thanks for verifying! The best thing would obviously to have this fixed in the JDK, as [other software](https://issues.apache.org/jira/browse/BATIK-1277) run into the [same bug](https://issues.apache.org/jira/browse/PDFBOX-4718) as well.

I believe it would be possible to guard against some of the situations (read the JDK bugs for background and tips), but it will require parsing the SVG and analysis of the paths... I believe this is out of scope for the TwelveMonkeys plugins. But it may make sense to implement a guard/workaround in Batik, as it's a more general problem. 


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2020-01-29 08:21
Related [Batik issue](https://issues.apache.org/jira/browse/BATIK-1277).

**Comment by j-p-sequeira** [comment] 2020-01-29 09:29
> Is there a way to detect the particular problem with this image before processing it?

Ok, the problem is in the group with id "g34" (which has the child group g40 which in turn has an image). If you go to the file and remove the `clip-path="url(#clipPath38)"` from g34, everything works. Alternatively, you can remove the path nested inside `clipPath38`.

All the evil that triggers these Java bugs seem to be related to gradients somehow. I've come across other SVG problems that are related to gradients, like the gradient effect `<feGaussianBlur stdDeviation="2 3" />` in the batikYin.svg in Batik samples folder (though, this one is not so nasty, it fails fast and without consuming memory).

Like you, I've been thinking of detecting these problematic gradients and remove them from the files. It would be a major headache to do, and in the end, maybe it's best to not show the image at all than an incomplete one.

These problems generate exceptions that can be caught to avoid breaking your application. But these OutOfMemory ones  (which I was already defending against) are quite nasty. First, because they take a while to consume all memory, and in worst case, if the JVM has plenty memory available, it can hang forever (though it seems the call may succeed after several minutes, as someone commented in the bug links I posted).

**Comment by KoenDG** [comment] 2020-01-31 16:19
Did some debugging and I'm kinda worried there's just no way to detect this before passing it along to `SVGAbstractTranscoder.transcode(TranscoderInput input, TranscoderOutput output)`

The problem seems to occur inside Java's `AreaOp.pruneEdges`, which just goes on forever/builds up too much stuff in memory.

Something tells me that actually adding code to catch this, and I don't know how yet, would be a massive undertaking. Almost as much as all the code traveled to reach that point.

And I don't even know SVG.

Another problematic issue I've seen with this: it doesn't quickly or reliably crash the JVM. Sometimes it just keeps going, just not hitting OOM, cleaning, getting back to the limit, cleaning,... but never going over it.

Which is a thing talked about here: https://medium.com/@NetflixTechBlog/introducing-jvmquake-ec944c60ba70

**Comment by j-p-sequeira** [comment] 2020-01-31 16:49
> Another problematic issue I've seen with this: it doesn't quickly or reliably crash the JVM.

It is a problem indeed. So far, my app always recuperates after a few seconds because it catches the out of memory exception, but not consuming all the memory (or taking too long to do it) is a scenario that I've anticipated and I still haven't applied a fix to it. Since it is not easy....

I've thought about loading the image in a different thread and starting a Timer. This is not too difficult to do (just a bit of hard work), but the problem is how to [kill the thread safely](https://docs.oracle.com/javase/1.5.0/docs/guide/misc/threadPrimitiveDeprecation.html) after we reach our timeout. We can't just use a variable to stop execution...

Starting the JVM with the option to use a defined amount of memory is also no good for several reasons (and what would be a good value?).

**Comment by haraldk** [comment] 2020-08-08 10:06
Closing this for now, as I think this has to be fixed either in the JDK or in Batik. 

-- 
Harald K

**Closed by haraldk** 2020-08-08 10:06 UTC
Labels: Trouble-shooting
