### ISSUE TITLE
TGA files with 32-bit format (ARGB) but no extension headers are missing the alpha

### ISSUE THREAD

**Issue by jmailhot** [haraldk/TwelveMonkeys#680] opened 2022-05-16 19:52 UTC
**Describe the bug**
There are a class of TGA files in the wild that have 8-bit RGB plus alpha, but do not have the extension headers.  The current TGA library successfully identifies them as 8-bit RGB inside a 32-bit int, and also successfully parses the attribute bits of the base header to know that there are 8 bits of "attribute" (the alpha value).   But there is a logic bug in using that information.  In TGAImageReader.java, around line 130, where it has:
       case TGA.IMAGETYPE_TRUECOLOR:
            case TGA.IMAGETYPE_TRUECOLOR_RLE:
                ColorSpace sRGB = ColorSpace.getInstance(ColorSpace.CS_sRGB);

                boolean hasAlpha = header.getAttributeBits() > 0 && extensions != null && extensions.hasAlpha();
                boolean isAlphaPremultiplied = extensions != null && extensions.isAlphaPremultiplied();

This bug is fixed (for me) if I change that one line to read:
      boolean hasAlpha = header.getAttributeBits() > 0 || (extensions != null && extensions.hasAlpha());

My reasoning is that its perfectly valid to have extensions == null and yet have alpha in the attribute bits, and it seems a reasonable assumption that if a file does have an extension header, the hasAlpha() information from that header should supercede the attribute bits.

I have a small file that demonstrates the issue, but github will not let me attach a tga file to an issue.  so i made a zip of it.
[HD-bug.zip](https://github.com/haraldk/TwelveMonkeys/files/8702860/HD-bug.zip)

**Version information**
This problem is present in imageio-tga version 3.8.x
I am running java runtime 1.8.0_191-b12

**To Reproduce**

use the TGA plugin to read the attached (after unzipping it) hd_bug.tga file.
in current version (3.8.x) it will show up as 8-bit RGB with no alpha.
after repair, it will show up as 8-bit RGB with 8-bit alpha

note - in this file, the RGB part of the image is flat white, and the alpha channel forms a mask that reveals the content (the chinese characters for "high definition").  So if all you see is a blank white rectangle, you have no alpha.

**Sample file(s)**
noted above.

**Screenshots**
The graphic should look like this (this screenshot from irfanview):
![image](https://user-images.githubusercontent.com/10361068/168671262-c5be3c3d-3b84-43bb-b5e7-6c042a65db7e.png)

**Additional context**

**Comment by haraldk** [comment] 2022-05-18 08:12
Hi,

I kind of agree with you. It would be great if we could support this, however, the suggested fix breaks the following samples in the `imageio-tga/src/test/resources` folder: 

    CTC16.TGA, CTC32.TGA, UTC16.TGA, UTC32.TGA

These files now render completely transparent, which is probably not as intended.

**Comment by haraldk** [comment] 2022-05-18 14:43
After some more thinking and re-reading the specs, the correct test is probably:

```java
boolean hasAlpha = header.getAttributeBits() > 0 && (extensions == null || extensions.hasAlpha());
````

This will allow the attribute bits to be treated as alpha, either by default if there is no extensions area, or if the extensions area explicitly says there is alpha. 

This works for both your sample file and the existing samples.

**Comment by haraldk** [comment] 2022-05-18 20:49
Fixed in latest master, will be in next release. Hopefully soon.

**Closed** 2022-05-18 20:49 UTC
Labels: Reported bug
