### ISSUE TITLE
IndexOutOfBoundsException when trying to get jpeg metadata

### ISSUE THREAD

**Issue by THausherr** [haraldk/TwelveMonkeys#101] opened 2015-02-27 15:59 UTC
The attached jpeg file is broken, but opening it with ImageIO.read() fails gracefully: "javax.imageio.IIOException: Bogus marker length". However trying to gets its metadata brings an IndexOutOfBoundsException :-( My wish would be that reader.getImageMetadata(0) also fails with some IIOException.

Exception in thread "main" java.lang.IndexOutOfBoundsException: off < 0 || len < 0 || off+len > b.length || off+len < 0!
	at 
![485945-badjpeg](https://cloud.githubusercontent.com/assets/6665575/6415860/01f71262-bea2-11e4-8cfe-9b067c47f102.jpg)
javax.imageio.stream.MemoryCacheImageInputStream.read(MemoryCacheImageInputStream.java:100)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGSegmentImageInputStream.read(Unknown Source)
	at com.sun.imageio.plugins.jpeg.JPEGBuffer.loadBuf(JPEGBuffer.java:106)
	at com.sun.imageio.plugins.jpeg.JPEGMetadata.<init>(JPEGMetadata.java:171)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(JPEGImageReader.java:1018)
	at com.twelvemonkeys.imageio.plugins.jpeg.JPEGImageReader.getImageMetadata(Unknown Source)
	at TwelveMonkeysTest.main(TwelveMonkeysTest.java:191)

**Comment by haraldk** [comment] 2015-02-27 19:15
Hi,

Thanks for reporting!

Sounds reasonable to me. :-)
I'll investigate, and see what I can do. 

Update: A quick debug session revealed that the problem is caused by a "bug" (or lack of input sanitizing, really) in `com.sun.imageio.plugins.jpeg.JPEGBuffer`, that passes a negative array offset down to the `JPEGSegmentImageInputStream.read(bytes, off, len)` method. I should be able to create a fix for this.


Best regards,

-- 
Harald K

**Comment by haraldk** [comment] 2015-03-02 09:34
All right,

Fixed in 1f990409278453cf5ce51d3cf43bef7a49011a20.

The attached image is now "readable" as shown above (ie. the stream ends after some 15% or so), if you a) pass a destination in the `ImageReadParam` and b) catch the `IIOException` that occurs during read (and ignore it). Java exception handling will still prevent the `read` method from returning normally, as before.

In any case, the exception thrown will be an `IIOException`.


-- 
Harald K

**Closed by haraldk** 2015-03-02 09:34 UTC
Labels: Bug
