### ISSUE TITLE
NullPointerException on JPEGImageReader.getRawImageType

### ISSUE THREAD

**Issue by Paulo-Weber** [haraldk/TwelveMonkeys#180] opened 2015-09-30 13:05 UTC
I'm getting a error while reading a jpg image through this lib, for the record, in the default javaio it doesn't work as well, but in your lib I see that shows a NullPointerException and I'm quite confusing, in a quick look I would say that the image shouldn't really work, but I'm opening the issue so you can see and maybe find a way to make the image open...

In JPegImageReader.getImageType(int code), the code passed is 0, (I believe that it's referring to JCS_UNKNOWN), and then it compares if it's bigger than 0 (code > 0), but, in the ImageTypeProducer.getTypeProducer(int code), if the code was 0 it would still return a ImageTypeProducer, but in ImageTypeProducer.produce(), being csCode = 0, it would return null and possibly would occur a NullPointerException somewhere else...

I attach the image on this ticket so you can see if there's something to do about it...
![exif-jfif-app13-app14ycck-3channel](https://cloud.githubusercontent.com/assets/14895907/10193601/7b636996-675a-11e5-988c-0880a82377c2.jpg)

Since I wasn't able to find the answer nor an email or somewhere else to ask, I'll ask here. Do you intend to improve the lib? supporting new types of images? I ask because I downloaded a pack of almost 2000 jpeg images and I'm testing to see the results, so far all the images that don't work in this lib also doesn't work in the javaIO default, but if you want to improve your lib I could send you the images that doesn't work and maybe you can improve your tool to deal with some of the images...

**Comment by haraldk** [comment] 2015-09-30 13:23
Hi Paulo,

Thanks for reporting! I constantly work on improving the library, feel free to suggest (or contribute) new formats.

I believe the issue you have found is fixed in the main branch (to be released as 3.2). It's a duplicate of (actually, the exact same image as) #169 .

If you are able to build from sources, please do, before testing with your 2000 images. :-)

Sorry for the inconvenience.


Best regards, 

-- 
Harald K

**Comment by haraldk** [comment] 2015-09-30 13:43
Closing as duplicate of #169 . 

Feel free to file another issue, if you find more images that can't be read using the latest version.

-- 
Harald K

**Closed by haraldk** 2015-09-30 13:43 UTC
Labels: Trouble-shooting
