### ISSUE TITLE
TIFF Planar YCbCr 4:4:4 JPEG Color matrix incorrectly decoded

### ISSUE THREAD

**Issue by ccodere** [haraldk/TwelveMonkeys#678] opened 2022-05-11 16:08 UTC
**Describe the bug**
My tool has generated a YCbCr 4:4:4 TIFF Planar image compressed using LZW. When opening in GIMP and in my internal viewer the image is correctly displayed, but with the latest official release of the JAR files of Twelvemonkeys, i get incorrect colors. 

**Version information**
1. The version of the TwelveMonkeys ImageIO library in use is version 3.8.1. I think it never worked beforehand.

3. The *exact* output of `java --version` (or `java -version` for older Java releases). 
openjdk version "1.8.0-272"
OpenJDK Runtime Environment (build 1.8.0-272-b10)
OpenJDK Server VM (build 25.71-b10, mixed mode)

4. Extra information about OS version, server version, standalone program or web application packaging, executable wrapper, etc. Please state exact version numbers where applicable.

I tested this on both Windows 10 with Java 11 and Windows XP with Java 8. 
Log from my small utility confirming loaded plugins:
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.CURImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.psd.PSDImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.wbmp.WBMPImageReader 1.0
TwelveMonkeys com.twelvemonkeys.imageio.plugins.dcx.DCXImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.jpeg.JPEGImageReader 0.5
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pict.PICTImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.CURImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.BMPImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.bmp.BMPImageReader 1.0
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.ICOImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.gif.GIFImageReader 1.0
TwelveMonkeys com.twelvemonkeys.imageio.plugins.psd.PSDImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.webp.WebPImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pcx.PCXImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.icns.ICNSImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pnm.PNMImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.sgi.SGIImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.iff.IFFImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.png.PNGImageReader 1.0
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pcx.PCXImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.psd.PSDImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.webp.WebPImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.psd.PSDImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.psd.PSDImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.BMPImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.CURImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.dcx.DCXImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.mac.MACImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.iff.IFFImageReader 3.8.1
Oracle Corporation com.sun.imageio.plugins.png.PNGImageReader 1.0
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pnm.PNMImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.ICOImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.sgi.SGIImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pnm.PNMImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.BMPImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.pict.PICTImageReader 3.8.1
TwelveMonkeys com.twelvemonkeys.imageio.plugins.bmp.ICOImageReader 3.8.1

**To Reproduce**
Try to view this TIFF image using your library. See attachment

**Expected behavior**
Compare when opening the image in GIMP. Colors are correct in GIMP.

**Example code**
Not applicable

**Sample file(s)**
See attached file.

**Screenshots**
N/A

**Additional context**
This may be completely unrelated but the TIFF *may* be wrong when converting the data because it may be slightly off. In lines  138-140 of YCbCrConverter.java:
           // Custom values
            y = ((yCbCr[offset] & 0xff) - referenceBW[0]) * 255.0 / (referenceBW[1] - referenceBW[0]);
            cb = ((yCbCr[offset + 1] & 0xff) - referenceBW[2]) * 127.0 / (referenceBW[3] - referenceBW[2]);
            cr = ((yCbCr[offset + 2] & 0xff) - referenceBW[4]) * 127.0 / (referenceBW[5] - referenceBW[4]);
This will result in slight distortions, but is probably unrelated to this issue at hand. 

### More information from TIFFInfo:
TIFF Directory at offset 0x200faa (2101162)
  Image Width: 1392 Image Length: 968
  Resolution: 73, 73 pixels/inch
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 1, 1
  Samples/Pixel: 3
  Rows/Strip: 968
  Planar Configuration: separate image planes
  DateTime: 2022:05:03 02:33:23
  YCbCrCoefficients: 0.299000,0.587000,0.114000
  Reference Black/White:
     0:    16   235
     1:   128   240
     2:   128   240
  Predictor: horizontal differencing 2 (0x2)

[marbles_cropped_II_yuv444p8_jpeg_Planar_LZW.zip](https://github.com/haraldk/TwelveMonkeys/files/8671561/marbles_cropped_II_yuv444p8_jpeg_Planar_LZW.zip)

**Comment by haraldk** [comment] 2022-05-12 21:01
Hi,

Sorry for not responding to this request, I initially thought it was a duplicate of #679. I see now that the original code would actually read this file, but not apply the YCC -> RGB conversion, making the colors completely off. Anyway. I fixed this too, when working on the planar subsampled issue. 😀

**Closed by haraldk** 2022-05-12 21:01 UTC
Labels: Reported bug

**Comment by ccodere** [comment] 2022-05-13 02:10
Thanks for your quick response and help, great framework! :)
