### ISSUE TITLE
Exception: TGA Extension Area size 494 written by Autodesk 3ds Max

### ISSUE THREAD

**Issue by superzhangzl** [haraldk/TwelveMonkeys#466] opened 2019-01-02 01:27 UTC
When I use this tool to read a small tga file, throw an exception.
`TGA Extension Area size less than 495: 494`
 file size is 512*512.

**Comment by haraldk** [comment] 2019-01-02 17:04
Hi!

Thanks for reporting! Can you please attach such a small TGA file to the issue, to be used as a test case? 

-- 
Harald K

**Comment by haraldk** [comment] 2019-01-08 14:16
Hi again,


Have you found a sample file for me yet? :-)

PS: All of the following documents [TGA File Format Summary](https://www.fileformat.info/format/tga/egff.htm), [WikiPedia: Truevision TGA](https://en.wikipedia.org/wiki/Truevision_TGA#Extension_area_(optional)) and [TGA File Format](http://tfc.duke.free.fr/coding/tga_specs.pdf) explicitly states that the only valid value for the field is indeed `495`. Newer versions of the format may define a larger value, but never smaller. I believe that the file you have is written by a "bad" encoder. 


Best regards,

-- 
Harald K

**Comment by 553234736** [comment] 2019-01-09 03:53
Sorry, I have no way to provide this sample. It cannot be transmitted from the intranet segment to the extranet segment on the intranet segment of the company. It is provided by the art department to detect whether it contains hidden content. I wrote a decoder to read the original information of each block from binary.
Thank you very much for your reply. If I get this sample on the extranet segment, I will send it to you in time.

Zzl
=================
抱歉，我没有办法提供这个样本。它在公司的内网网段，无法从内网网段传送到外网网段。它是美术部门提供的用于检测是否含有隐藏内容。我写了一个解码器用于从二进制读取各个数据块的原始信息。
非常感谢你的回复，如果我在外网网段获得了这个样本，我会及时将它发送给你。

zzl

**Comment by 553234736** [comment] 2019-01-09 03:57
I am also very sorry, I replied late, forgot to look at my mailbox, there are a lot of advertising emails.

**Comment by haraldk** [comment] 2019-01-09 09:08
No worries!

I usually use a USB-stick for such tasks, but there may be strict policies about this in your company, so better ask a manager for permission first. I'm closing the issue as not reproducible for now. Feel free to reopen when you get the sample file, and attach it to the issue.

Best regards,

-- 
Harald K

**Comment by 553234736** [comment] 2019-01-09 09:10
ok~ ^_^

**Comment by darekjanik** [comment] 2020-08-05 18:27
Hi!

I have the same issue. Here's a sample file:

[image.tga.zip](https://github.com/haraldk/TwelveMonkeys/files/5030405/image.tga.zip)

**Comment by haraldk** [comment] 2020-08-05 20:15
Hi Darek,

Thank you for providing a sample file! It seems to be written by Autodesk 3ds Max, still they seem to have got the extension size wrong... Anyway, as both your sample file and the the one reported by @superzhangzl had the exact size of 494 (off-by-one bug?), we could probably detect this size and allow it (with a warning). The file seems fine otherwise. I'm a little unsure about what to do with the flag byte at offset 494, though. It *seems* to contain a valid flag. Do you have more files with this problem, for validation? 

Best regards,

-- 
Harald K

**Comment by darekjanik** [comment] 2020-08-06 13:46
Yes, it looks like all files has exact size of 494. I've attached some more files.
[tga.zip](https://github.com/haraldk/TwelveMonkeys/files/5035162/tga.zip)

**Comment by haraldk** [comment] 2020-08-07 09:15
Great! 

I was hoping for that to be the case, and I have a fix ready soon. I'll use the smallest sample file you provided for the test case.

-- 
Harald K

**Closed** 2020-08-07 11:19 UTC
Labels: Trouble-shooting
