### ISSUE TITLE
LZWDecoder - IndexOutOfBoundsException when reading some files

### ISSUE THREAD

**Issue by balamuru** [haraldk/TwelveMonkeys#272] opened 2016-07-07 21:29 UTC
When attempting to read and write certain grayscale tiffs, the following happens
1. The resulting image is always corrupted
2. Sometimes, an IndexOutOfBoundsException exception is raised when the LZWDecoder is is invoked via a call to com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read . This doesn't always happen. I needed to run the test class a few times to see the exception.

Some files don't have this issue, others do . See the code and test files for details

Thanks

[test_and_data.zip](https://github.com/haraldk/TwelveMonkeys/files/353090/test_and_data.zip)

Exception details
`Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:532)
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:172)
	at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder$LZWString.writeTo(LZWDecoder.java:330)
	at com.twelvemonkeys.imageio.plugins.tiff.LZWDecoder.decode(LZWDecoder.java:129)
	at com.twelvemonkeys.io.enc.DecoderStream.fill(DecoderStream.java:178)
	at com.twelvemonkeys.io.enc.DecoderStream.read(DecoderStream.java:122)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:423)
	at com.twelvemonkeys.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:396)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.readStripTileData(TIFFImageReader.java:1417)
	at com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:931)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1308)
	at ImagingIssue.main(ImagingIssue.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)`

**Comment by haraldk** [comment] 2016-07-11 16:54
Hi Vinay,

Thanks for reporting!

At first sight, it looks like the "page.tif" file is corrupted, but I'll look into it in some detail when I find the time (I'm on holidays at the moment). The "trump.tif" picture looks fine (from a technical point of view... ;-) ). 

Do you know of any other software that can open this particular file? I can't open it in any of the standard tools on OS X.


Best regards,

-- 
Harald K

**Comment by balamuru** [comment] 2016-07-11 20:36
Hi Harald,
I used the standard linux gnome image viewer and the image opened fine. A co-worker of mine had the same issues you describe with this image using mac / windows .

That said, here is an image (zipped up) that he generated that can be viewed on his mac but exhibits the same exception (i had to run the program 3 times before it showed up). For what it's worth, It seems slightly larger than my image .

[page_b.tif.zip](https://github.com/haraldk/TwelveMonkeys/files/358031/page_b.tif.zip)

**Comment by haraldk** [comment] 2016-07-26 10:15
Thanks!

I need to look into this some more when I find the time, but it looks like there's a problem with the LZW decoding.

-- 
Harald K

**Comment by balamuru** [comment] 2016-10-07 15:20
Any luck ? Thanks

**Comment by haraldk** [comment] 2016-10-09 09:14
Sorry, no. 

Haven't had the time to look at this properly yet.
Have patience! :-)

-- 
Harald K

**Comment by haraldk** [comment] 2016-10-10 19:49
Fixed in master. 

I have tested and successfully read all your supplied sample files. One of them is now included in the test file set, for effective regression testing.


Thank you!

-- 
Harald K

**Closed by haraldk** 2016-10-10 19:49 UTC
Labels: Bug, Trouble-shooting

**Comment by balamuru** [comment] 2016-10-21 08:11
Thanks for getting this done

**Comment by haraldk** [comment] 2016-11-03 12:24
@balamuru This bugfix is now included in the official 3.3 release.
